### ISSUE TITLE
Memory leak: fix the cyclic-ness of the DAG

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1010]
The DAG has cycles on `BlockRef` but it is tagged `{.acyclic.}`.

With the default refcounting GC, it's a guaranteed memory leak as `acyclic` means "trust me, you don't need to run cycle detection" to the GC.

https://github.com/status-im/nim-beacon-chain/blob/9636ca3e17628d4bfbdc2a29006e5385fc398e66/beacon_chain/beacon_node_types.nim#L158-L172

Either we lose the {.acyclic.} tag (which means BlockRef alloc/dealloc will trigger both refcounting and mark-and-sweep). Or we remove either the parent field or the children field.

Using pointers for weak ref is not possible as the GC can relocate ref objects in memory and invalidate the pointer and `{.cursor.}` is for GC:ARC.

**Comment by stefantalpalaru** [comment]
> the GC can relocate ref objects in memory

Only a compacting GC would do that, right?

**Comment by mratsim** [comment]
Nim GC does relocate refs and I was bitten by it:

I tried this: https://github.com/nim-lang/Nim/issues/9974

but in the end it led to very hard to investigate bugs in my DAG and I had to remove `ptr` (https://github.com/mratsim/Arraymancer/pull/329/commits/30749e58a0c8fb4d933d2be6e448b2b5dbe1bdf1)

The worse is that when the ref was moved, it was replaced not by uninitialized or invalid memory that would crash but by another valid ref.

To detect that I had to print my DAG link and then i realize that I was somehow not jumping from child to parent but there were missing links.

**Comment by arnetheduck** [comment]
don't sweat it: https://github.com/status-im/nim-beacon-chain/issues/669

**Comment by stefantalpalaru** [comment]
Just remove the `{.acyclic.}` pragma. Who knows how much time will pass until the complete removal.

**Comment by arnetheduck** [comment]
indeed.
