### ISSUE TITLE
[Windows 32-bit Perf] Passes through epoch update, empty block is slow

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#102]
This part of the test suite is very slow and takes several minutes on Windows with beacon-chain built for 32-bit:

[OK] Passes through epoch update, empty block

https://github.com/status-im/nim-beacon-chain/blob/4747477160c60e456a43b837564934caa16198b5/tests/test_state_transition.nim#L66-L83

**Comment by tersec** [comment]
There have been several rewrites since this bug of the epoch state transition code. Is this still reproducible?

**Comment by mratsim** [comment]
This probably needs a proper benchmark, closing

**Comment by mratsim** [comment]
Actually confirmed still current with https://github.com/status-im/nim-beacon-chain/issues/308

**Comment by mratsim** [comment]
Outdated checked in CI, the improvement from the past 3 months (EpochRef, Cache) has removed spurious hashTreeRoot
