### ISSUE TITLE
process_slots slowness

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1023]
From nbench on voluntary_exits:

![image](https://user-images.githubusercontent.com/22738317/81942089-f6e7c080-95f9-11ea-821d-d84c4d2fb076.png)

https://github.com/status-im/nim-beacon-chain/blob/2d691b2e1461ccc5e0d40fc07ae329617d8647c9/beacon_chain/state_transition.nim#L126-L170

**Comment by mratsim** [comment]
with nbench that tracks advance_slot and hash_tree_root

![image](https://user-images.githubusercontent.com/22738317/81952082-4e8c2900-9606-11ea-955d-1bf792d0bdff.png)

Though it's quite possible that many hashTreeRoot calls are for very small types and only a portion on BeaconState which would skew the average reported.

**Comment by arnetheduck** [comment]
indeed, it doesn't make sense to annotate the individual HTR overloads with this kind of performance tool really, the numbers will be garbage - a sampling profiler will do a better job.

possibly, one could have a `htr_bench` "outer" function that measures the time of the whole tree calculation, but even that is a stretch.

**Comment by arnetheduck** [comment]
this is fixed now with the htr cache
