### ISSUE TITLE
Windows compilation error 

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-beacon-chain#1071]
Right now at https://github.com/status-im/nim-beacon-chain/commit/28128f4d2f65865ffec3cb5877ea5a396d1068fc

I'm not able to bootstrap `nim-beacon-chain` on Windows anymore.

There 2 PCs has been tested and two different Windows 10 x64 builds tested, behavior is absolutely same.
1. Desktop Xeon-W3690 with 48GB RAM with Windows 10 Pro OS Build 18363.778.
2. Laptop i7-7550U with 16GB RAM and Windows 10 Pro OS Build 18363.836.

3 different `mingw64` distributions has been tested.
1. gcc.exe (Rev2, Built by MSYS2 project) 10.1.0
2. gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
3. gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0

```
nim-beacon-chain\beacon_chain\validator_keygen.nim(61, 23) Error: type mismatch: got <seq[Deposit]>
but expected one of:
proc attachMerkleProofs(deposits: var seq[Deposit])
  first type mismatch at position: 1
  required type for deposits: var seq[Deposit]
  but expression 'result' is of type: seq[Deposit]

expression: attachMerkleProofs(result)
mingw32-make: *** [Makefile:117: beacon_node] Error 1
```

To reproduce i'm following next steps (assuming you have `mingw64\bin` in PATH and `Git For Windows` bash environment installed and accessible from PATH):
```
bash
git clone git@github.com:status-im/nim-beacon-chain.git
cd nim-beacon-chain
mingw32-make
```

Our investigation with @stefantalpalaru produces this weird difference in logs of building `beacon_node` using `mingw32-make V=1 beacon_node 2>&1 | tee log.txt`:

1. Working https://gist.github.com/stefantalpalaru/149c8e659130f4c87cd2d2f218a27148#file-beacon_node_log-txt-L905
2. Broken https://gist.github.com/cheatfate/44318de9ea6550ec821da1f3511c695d#file-desktop-txt-L905

This shows that something broken in Nim compilation order.

**Comment by cheatfate** [comment]
For some reason this problem disappeared when i stopped using TortoiseGit.

**Comment by cheatfate** [comment]
Could not reproduce anymore...

**Comment by cheatfate** [comment]
Right now i'm able to reproduce this problem on both my PCs (laptop & desktop) on this commit https://github.com/status-im/nim-beacon-chain/commit/1fef9765a0269c4e81d505ef418b3918a613e1a9

**Comment by stefantalpalaru** [comment]
Modules being processed more than once during the same compilation, in @cheatfate's output: https://gist.github.com/stefantalpalaru/f108cc4583b328be4fb9502f88e94336

**Comment by cheatfate** [comment]
I was able to reproduce bug using `clang` bootstrapped Nim compiler too.
I've used https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe

**Comment by stefantalpalaru** [comment]
Debugging tips from @zah that shouldn't be lost in a chat:

`To debug the issue, I would add an echo line at the begging of fileInfoIdx in compiler/msgs.nim  (this will show you what's going on with path canonicalization)`

`I might also look at modules.nim/compileModule to see if there is something unusual there`

**Comment by sinkingsugar** [comment]
> Modules being processed more than once during the same compilation, in @cheatfate's output: https://gist.github.com/stefantalpalaru/f108cc4583b328be4fb9502f88e94336

Ah that is crazy, cannot reproduce here tho when I'm on Windows.
There is something that @cheatfate is using that maybe is messing with file attributes/hashing, it might be Unix/Windows permissions being touched ( I had some issue when folder was mounted from docker for Windows, Altho didn't cause this )

**Comment by cheatfate** [comment]
@sinkingsugar attributes/hashes/permissions are not manually touched (only if Git For Windows touching it). And right now i moved everything to C drive and i even do not have spaces in my folder names.

**Comment by cheatfate** [comment]
Ok problem found and fixed, i was always started my Git's Bash For Windows using `<Git installation path>\bin\(bash.exe or sh.exe)`. And this is problem.

Use Git Bash from Windows Start Menu, which points to `<Git installation path>\git-bash.exe" --cd-to-home`
