### ISSUE TITLE
[Simulation] Slot skipping

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#109]
From time to time the simulation skips slots.

Example in https://gist.github.com/mratsim/1060f973b38c915db3172c27cc7e8e5f

Slot 6 and 8 were skipped. This can also happen later, in the same run slot 25 and 27 were skipped.

**Comment by zah** [comment]
This is correct and expected. 10% of the validators are missing in the network simulation on purpose. We do this to see how the system will handle the missing block proposals when it's their turn.
