### ISSUE TITLE
Suggestions & Priority of the Nim Beacon Chain Manual

### ISSUE THREAD

**Issue by tina1998612** [status-im/nim-beacon-chain#1107]
Feel free to leave suggestions about the manual below (for example, the key points that set us apart from lighthouse). Thanks!

The latest version of the manual: https://status-im.github.io/nim-beacon-chain/

**Comment by tina1998612** [comment]
I've updated the lastest link of the manual, so feel free to check it out~

**Comment by stefantalpalaru** [comment]
Broken link: "Open sourced at github.com/status-im/nim-beacon-chain/docs." - points to https://status-im.github.io/nim-beacon-chain/github.com/status-im/nim-beacon-chain/docs
(maybe it needs "https://")

https://status-im.github.io/nim-beacon-chain/nimbus.html - Under the "Nimbus" umbrella there are 2 separate projects with separate repositories for Eth1 and Eth2 support. You just link the first repo.
Drop the "Why should you choose Nimbus?" section if you don't have the copy ready for it.

https://status-im.github.io/nim-beacon-chain/beacon-chain.html - "You can also see it as a hybrid PoS + PoW solution." - where is the "hybrid" part coming from?
"while validators rely on just software" - and a good network connection

https://status-im.github.io/nim-beacon-chain/validator.html - "cornor" - typo. Have you considered using a spell checker regularly? It would catch these typos immediately.
It's better to replace "testnet0" with "witti" in the examples.

https://status-im.github.io/nim-beacon-chain/install.html - "Nimbus beacon chain" a third name to increase the confusion? I'd go with "beacon chain". I see it's also in the book title. Maybe it should be "The nim-beacon-chain Book".
BTW, we need to link it in the main "README.md".
"PCRE Nim is not an external dependency, Nimbus will build its own local copy." - these should be 2 separate bullet points
"MacOS" should be "macOS"
"You can install the developer tools by following the instruction in our Windows dev environment section." - wrong link href. Needs "https://"?

https://status-im.github.io/nim-beacon-chain/api.html - empty page. Should be removed, along with the intro link.

https://status-im.github.io/nim-beacon-chain/advanced.html#linux-macos - update this after the README. We no longer need a separate `make` step.
"Rasbian Buster Lite" - should be "Raspbian ..."

https://status-im.github.io/nim-beacon-chain/faq.html - remove empty page and the link pointing to it

**Comment by tina1998612** [comment]
@stefantalpalaru thanks for your detailed review:) I need to following clarifications: 
What does "update this after the README. We no longer need a separate make step." mean? In the latest readme in the devel branch, there is still make.

Others are fixed in the new readme branch. I'll submit another pull request. Thanks again.

**Comment by tina1998612** [comment]
I restructured the book and opened a PR here: https://github.com/status-im/nim-beacon-chain/pull/1206/files?file-filters%5B%5D=

**Comment by stefantalpalaru** [comment]
> In the latest readme in the devel branch, there is still make.

Not as a separate step. Make sure you look at a recent "devel".

**Comment by tina1998612** [comment]
There is a separate make here: https://github.com/status-im/nim-beacon-chain/tree/devel#linux-macos

**Comment by stefantalpalaru** [comment]
Clarified in a comment.

**Comment by tina1998612** [comment]
So the updated one is this?


make -j4

# Run tests
make test

# Update to latest version
git pull
make update

**Comment by stefantalpalaru** [comment]
Yes, including the comments above that section.

The point is that we moved from requiring a special post-cloning `make` command to fetch the submodules. Now any Make invocation gets them.

**Comment by tina1998612** [comment]
I see, so should I remove this line in the readme? 
```
# The first `make` invocation will update all Git submodules.
```

**Comment by stefantalpalaru** [comment]
> so should I remove this line in the readme?

No.

**Comment by tina1998612** [comment]
Why not? There is no need to have the first make now.

**Comment by stefantalpalaru** [comment]
That's not the expression of a requirement, but an explanation of what happens whenever Make is invoked for the first time after a fresh clone, regardless of its target.

**Comment by tina1998612** [comment]
So do u mean that running make and running make witti both can fetch all sub modules? Thanks again:)

**Comment by stefantalpalaru** [comment]
> running make and running make witti both can fetch all sub modules?

Yes, that's it.

**Comment by arnetheduck** [comment]
let's document the json rpc interface as well - there's an example in https://github.com/status-im/nim-beacon-chain/pull/1196 (though default port has changed now). 

things do document:
* rough description of what the rpc does
* copy-pasteable `curl` example

the calls that already exist are defined here: https://github.com/status-im/nim-beacon-chain/blob/devel/beacon_chain/beacon_node.nim#L605

**Comment by tina1998612** [comment]
Ok~
