### ISSUE TITLE
[HowTo] Allow simulation past 99 validators and 9 validator nodes

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#111]
This was a bit tricky are many ranges are implicitly assumed in the code at the moment.

To allow simulation on more than 99 validators and 9 validators node you need to change 5 things:
- `tests/simulation/start.sh`
  - padding in the enumerator
  - padding in the master node address
  - padding in the tcp/udp port
  - padding in the beacon node CLI call for validator config
- `validator_keygen.nim`
  - padding in validator keygen generated json

Example commits in https://github.com/status-im/nim-beacon-chain/tree/allow-more-than-99-validators

**Comment by arnetheduck** [comment]
this would be nice as command line options (`./start.sh 5 50`)
