### ISSUE TITLE
Remote peer disconnects us with fault or error

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#1117]
`make witti`

very common - we get disconnected by remote peers with fault:

```
DBG 2020-06-04 08:53:23+02:00 Received Goodbye message                   topics="sync" tid=12715 file=sync_protocol.nim:172 reason=FaultOrError
```

bcbfa736c9501ab420615f4a6b2350d35727dac5

**Comment by cheatfate** [comment]
CC @sinkingsugar @dryajov

**Comment by arnetheduck** [comment]
this was a bad enum value - should have been invalidnetwork
