### ISSUE TITLE
Peers not getting disconnected though score is low

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#1133]
because of #1132, peers are getting descored but we keep requesting the blocks from them anyway (notably, the block is correct, but that shouldn't matter - we should disconnect from the peer regardless)

```
DBG 2020-06-05 22:01:25+02:00 Peer's syncing status                      topics="syncman" tid=367841 file=sync_manager.nim:758 local_head_slot=70688 peer=16Uiu2HAkvfDTKtFoSU5CHoA47BRwcJhN2zfvmr1kZXAwbweV3pq2 peer_score=-146800 remote_head_slot=70777 wall_clock_slot=70816
```

**Comment by cheatfate** [comment]
Fixed in https://github.com/status-im/nim-beacon-chain/commit/3ce98d5bca5a90c98f1fbff5d052848b1371a4c1
