### ISSUE TITLE
Dedicate some always-on servers to run Altona validators

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#1144]
@jakubgs's help will be required for creating Ansible playbooks for deploying nodes with validators targetting a specific testnet.

All nodes should have a proper metrics setup and log aggregation. It is expected that these will become our primary source of information for the general health of our beacon node implementation.

**Comment by jakubgs** [comment]
Shouldn't this be in https://github.com/status-im/infra-nimbus/issues ?

Also, what do those need? Can you give some more context? I've never heard of this.

**Comment by stefantalpalaru** [comment]
Done. We're using node-06 to node-09 for that.
