### ISSUE TITLE
June optimisation goals

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#1146]
* [ ] Let validator use case prioritise optimisations
* [x] Sync performance
* [x] Overall block processing
* [ ] Invalid attestation/block handling
* [ ] DoS protection (connection attempts, spam, invalid data, etc - discard early)

**Comment by zah** [comment]
LibP2P-related goals (by @dryajov):

* [ ] Figure out the optimal way to validate the GossipSub traffic in NBC before re-transmission
* [ ] Improve the general resource consumption and eliminate all resource leaks

**Comment by dryajov** [comment]
> Figure out the optimal way to validate the GossipSub traffic in NBC before re-transmission

@mratsim @tersec I believe this is something that you guys need to figure out according to what the expected/correct flow is. Have you had a chance to examine it any and do you need support from libp2p side?

**Comment by tersec** [comment]
> > Figure out the optimal way to validate the GossipSub traffic in NBC before re-transmission
> 
> @mratsim @tersec I believe this is something that you guys need to figure out according to what the expected/correct flow is. Have you had a chance to examine it any and do you need support from libp2p side?

I just saw it come up again in the v0.12.1 transition: https://github.com/status-im/nim-beacon-chain/pull/1170#discussion_r440848392

So it's been percolating up as a priority for me.

**Comment by dryajov** [comment]
> LibP2P-related goals (by @dryajov):
> 
> * [ ]  Figure out the optimal way to validate the GossipSub traffic in NBC before re-transmission
> * [x]  Improve the general resource consumption and eliminate all resource leaks

Item two was partly covered with the work done on `LPChannel` consumption.

**Comment by tersec** [comment]
Closing in favor of more specific issues
