### ISSUE TITLE
[RFC] epoch and slots - Distinct types

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#119]
We have many issues related to epochs and slots and their unique treatment in the specs:

  - https://github.com/status-im/nim-beacon-chain/issues/89
  - https://github.com/status-im/nim-beacon-chain/issues/97
  - https://github.com/status-im/nim-beacon-chain/pull/105
  - https://github.com/status-im/nim-beacon-chain/issues/109
  - https://github.com/status-im/nim-beacon-chain/pull/116
  - https://github.com/status-im/nim-beacon-chain/pull/118

We probably need 4 distinct types. 2 for each epoch and slots.

```Nim
type
  Slot = distinct uint64
  Epoch = distinct uint64
  PrintableSlot = distinct string
  PrintableEpoch = distinct string
```

With Slot and Epoch having no conversion to string defined and PrintableSlot/Epoch having only conversion to string defined.

**Comment by arnetheduck** [comment]
re `PrintableSlot`, what I've done in the past is to improve the logging framework to add an override hook separate from the normal to-string conversion (`$`) that allows customizing the displayed output

**Comment by zah** [comment]
This has been addressed in
https://github.com/status-im/nim-beacon-chain/pull/172
https://github.com/status-im/nim-beacon-chain/pull/173
