### ISSUE TITLE
Azure tests are green even when there is an error

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1226]
See https://dev.azure.com/nimbus-dev/nim-beacon-chain/_build/results?buildId=5386&view=logs&j=2e1ef983-081d-5c63-b72a-d9f329364ee0&t=69fb04d4-8d32-57d9-fbcf-c139b9f5d9e0&l=3118

![image](https://user-images.githubusercontent.com/22738317/85538151-e5400280-b614-11ea-9108-fe86fe391f18.png)

In branch https://github.com/status-im/nim-beacon-chain/pull/1223/commits/206ff7f9d6085d9e192644513626feed9d28f3d8

**Comment by tersec** [comment]
This was still an issue a couple months later -- see the linked bug.

**Comment by tersec** [comment]
Switched from Azure to GitHub Actions CI.

**Comment by mratsim** [comment]
Azure has been disabled #1693 

![image](https://user-images.githubusercontent.com/22738317/94142927-4aeb9700-fe6f-11ea-8f02-a48d63bf4941.png)
