### ISSUE TITLE
Block proposer node can crash when receiving its own proposal

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#124]
After fixing #101 via #123 and other epochs issues (#105, #118).

Here is the latest one, a node can:
  - propose a block
  - receive its own proposal a couple of slots later
  - crash with unexpected block slot.

![deepinscreenshot_select-area_20190219163745](https://user-images.githubusercontent.com/22738317/53027190-b9cb6780-3464-11e9-8036-45a67214d3bc.png)

With the assert being at the soon infamous :) "Could this fail somehow" 

https://github.com/status-im/nim-beacon-chain/blob/e1efdd4349a35903861a5384df0a96f07005fa56/beacon_chain/beacon_node.nim#L220-L229

**Comment by mratsim** [comment]
Maybe solved by #125

**Comment by arnetheduck** [comment]
state replay from last known point implemented, so this should be fixed
