### ISSUE TITLE
Unused importBlock (Forward Sync)

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1241]
This is unused:
https://github.com/status-im/nim-beacon-chain/blob/322a12fed77bb37efdab04d8992736f6f3d4e0bf/beacon_chain/sync_protocol.nim#L69-L73

I suppose this was supercded by

https://github.com/status-im/nim-beacon-chain/blob/322a12fed77bb37efdab04d8992736f6f3d4e0bf/beacon_chain/beacon_node.nim#L532-L568

**Comment by cheatfate** [comment]
Fixed by #1328
