### ISSUE TITLE
Improve confutils display in logs

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1242]
confutils variables are not properly replaced by their value in chronicles log.

![image](https://user-images.githubusercontent.com/22738317/85855727-05a7c280-b7b7-11ea-9ed2-d9200999a265.png)

**Comment by zah** [comment]
Can you clarify the issue? 

At the time this log line is produced, Confutils has already done its job - the configuration is stored in a regular Nim object and this object is what gets passed to Chronicles. The "raw" command-line is also printed for reference (again as a regular sequence of string params).

If you are referring to variables such as `$head_root`, this is the just the textual configuration of the status bar. It has its own custom "prompt template" system for modifying the content displayed there.

**Comment by mratsim** [comment]
Ah I see, it's the status bar content.
