### ISSUE TITLE
Review RNG usage

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1277]
As per discussion following https://github.com/status-im/nim-secp256k1/pull/23

Nim `random` module should be only used in case where non-crypto-secure RNG are suitable. This should be only tests (or require an explanation in the file)

For example: https://github.com/status-im/nim-beacon-chain/blob/db92c2f2549a339be60896c3907cefdb394b5e11/beacon_chain/nimbus_binary_common.nim#L12

**Comment by arnetheduck** [comment]
https://github.com/status-im/nim-beacon-chain/pull/1284 fixes most places where this matters
