### ISSUE TITLE
[Doc] Namespace books in gh-pages

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1281]
The commit https://github.com/status-im/nim-beacon-chain/commit/f74fad70cdd3609f493b3a791a86dd521b9cdde3 erased the updates from https://github.com/status-im/nim-beacon-chain/pull/1280

**Comment by arnetheduck** [comment]
ping @stefantalpalaru - we can have a single `make books` that publishes all books for all that I care - it's trivially fast anyway, no need to have separate targets
