### ISSUE TITLE
Issues with installing on macos

### ISSUE THREAD

**Issue by Buttaa** [status-im/nim-beacon-chain#1282]
discussion: https://discordapp.com/channels/613988663034118151/616299964242460682/729626990629617744

`/Users/butta/nim-beacon-chain/config.nims`

https://github.com/status-im/nim-beacon-chain/blob/4a2e1806533aedc80d850b7a9a6911705a5b15c5/config.nims#L75

**Comment by stefantalpalaru** [comment]
Doesn't show up in CI: https://travis-ci.org/github/status-im/nim-beacon-chain/jobs/704507360

**Comment by stefantalpalaru** [comment]
Cannot replicate. Blaming it on the full moon.
