### ISSUE TITLE
State slot can get stuck

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#133]
The simulation can (always ?) get stuck in a state slot as of https://github.com/status-im/nim-beacon-chain/commit/2d52d5cbfe14f2cd9d1f0eae9c0447c7569c57b4

![deepinscreenshot_konsole_20190222113044](https://user-images.githubusercontent.com/22738317/53236841-8f142580-3695-11e9-8674-95158a53831a.png)

**Comment by arnetheduck** [comment]
this is probably a thing of the past - if it's not, lots of logging has been added since then to help debug
