### ISSUE TITLE
Finalization issues with latest libp2p master

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-beacon-chain#1392]
This issues is here to track the ongoing efforts to fix finalization.

- Commit https://github.com/status-im/nim-libp2p/commit/a52763cc6dfa92b5a6ad374ba7b802f57eed8ac7 broke NBC finalization. 
- The specific change that seems to have introduce this behavior was the removal of the delayed send functionality - https://github.com/status-im/nim-libp2p/commit/a52763cc6dfa92b5a6ad374ba7b802f57eed8ac7#diff-e0b26345ee1b1e15968d513e9b2aad60L125-L156, this is further proved by https://github.com/status-im/nim-beacon-chain/pull/1382, which re-adds the "send queue". 
- PR https://github.com/status-im/nim-beacon-chain/pull/1360 attempts to reintroduce delayed sending but this time with a proper timeout (https://github.com/status-im/nim-libp2p/pull/295).
- There might be other unrelated issues that are causing finalization to fail, such as idle timeouts introduced to prevent inactive channels from piling up. This also affects pubsub publishing, since I suspect that some peers will not notify of a reset in certain situations (when shutting down for example, resetting is optimistic and there is no way for the sender to know if the channel is still alive, hence I suspect that most implementations will "send and forget" resets), this allows dead channels to further accumulate, hence, timeouts are necessary in the absence of a more sophisticated keepalive/ping mechanism, which is missing from mplex.

**Comment by stefantalpalaru** [comment]
Tangential, but this is an example of commit squashing making bisection harder.

**Comment by arnetheduck** [comment]
#1413 addresses this, to a certain extent
