### ISSUE TITLE
Azure CI doesn't properly register failure

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#1404]
https://github.com/status-im/nim-beacon-chain/pull/1388#issuecomment-666438500

Expected result: when a CI subtask fails, the the whole task fails.

Actual result: when the attestation test fails on 32-bit Azure, 32-bit Azure passes those builds.

**Comment by stefantalpalaru** [comment]
Can we get a small reproduction, or does it depend on stack contents?

**Comment by tersec** [comment]
There are a couple aspects of this:

- (1) the concrete test failure here. @arnetheduck seems to have understood what's going on there, but I've not checked firsthand.

- (2) the fact that this failure doesn't prevent 32-bit Azure from passing. This (probably?) is separate from the specific test failure in (1). I'm more concerned about (2) here than the specifics of (1), except to the extent it matters.

**Comment by arnetheduck** [comment]
the concrete issue here is that https://github.com/status-im/nim-beacon-chain/blob/40c2714ff30c811978fcc234f438ddd473851009/beacon_chain/fork_choice/fork_choice_types.nim#L59 confuses things: `Delta` is a balance/Gwei type, not an index

**Comment by tersec** [comment]
And trustworthy testing is especially important given https://github.com/status-im/nim-beacon-chain/pull/1398

**Comment by tersec** [comment]
Oh, @mratsim already found this or something like it: https://github.com/status-im/nim-beacon-chain/issues/1226

**Comment by tersec** [comment]
Closing in favor of https://github.com/status-im/nim-beacon-chain/issues/1226
