### ISSUE TITLE
Validator running but client is not submitting attestations

### ISSUE THREAD

**Issue by dangerousfood** [status-im/nim-beacon-chain#1443]
I have had my client with keys running for 8 hours with no attestations submitted and no blocks proposed
<img width="788" alt="Screen Shot 2020-08-04 at 10 43 29 PM" src="https://user-images.githubusercontent.com/4099038/89369602-3deacc80-d6a4-11ea-9f6b-873422f64f1b.png">

<img width="1616" alt="Screen Shot 2020-08-04 at 10 46 15 PM" src="https://user-images.githubusercontent.com/4099038/89369640-58bd4100-d6a4-11ea-9af6-fdf275e2dc6f.png">

https://beaconcha.in/validator/8d4aa75dbbd435e7e23ddf54e4ba1b3372d022c21f5b3247b2f8f8b0f0be0819eff0e2c530274014f9dffacef092ee0f

**Comment by jangko** [comment]
@dangerousfood I've transfer your issue to the correct repo.

**Comment by dangerousfood** [comment]
It stopped running again after reset. Is there a log file I can provide?

**Comment by zah** [comment]
This issue is affecting all Nimbus users right now, including ourselves. We are working hard on tracking the root cause.

**Comment by Phistr90** [comment]
Same issue for me.

**Comment by 3esmit** [comment]
Same issue for me.

**Comment by mratsim** [comment]
Following September significant updates, I think this is outdated. Feel free to reopen or comment if not.
