### ISSUE TITLE
Revive multinet scripts

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#1496]
These should ideally be running as part of CI to launch a limited network, testing basic connectivity and block/attestation exchange

**Comment by sinkingsugar** [comment]
Progress here so far https://github.com/sinkingsugar/multinet

Should we converge them in the original eth2 repo? or a status org repo?

**Comment by mratsim** [comment]
The eth2 repo seems OK. We want to share the maintenance burden once it's useful for everyone.

**Comment by sinkingsugar** [comment]
I will need permissions to push there then as I cannot currently btw.

**Comment by zah** [comment]
@sinkingsugar, I've sent you an invite for the eth2-clients organization.

**Comment by mratsim** [comment]
Merged: https://github.com/eth2-clients/multinet/pull/6
