### ISSUE TITLE
Stay unsubscribed until synced

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#1498]
While forward sync is running, it's not possible to validate attestations or blocks, and thus not possible to forward gossip traffic - this gets us descored and eventually kicked from the network while we're syncing.

**Comment by cheatfate** [comment]
It also slows us down because all the blocks received from gossip will be moved into `quarantine` and so it will raise cost of `addResolvedBlock` call without any reason.

**Comment by tersec** [comment]
Fixed by https://github.com/status-im/nim-beacon-chain/pull/1532
