### ISSUE TITLE
All nimbus nodes stuck syncing at slot 75006 

### ISSUE THREAD

**Issue by protolambda** [status-im/nim-beacon-chain#1516]
See https://eth2stats.io/medalla-testnet

- zah
- sudo (x2)
- proto (x2)
- michaelb(status)

All stuck on slot 75006, and no other nimbus nodes seem to be able to get past it.

## Logs

Here are some sync logs from one of my nimbus nodes (running the gossipsub rework branch):

https://gist.github.com/protolambda/bd574aa0c87e755969fa4fc000703b7d

I think this some kind of sync bug? It keeps retrying, but always fetches a later block with a different parent root, and cannot get past it. Or maybe it is because of bad sync responses (@agemanning from lighthouse was experiencing such a problem during sync).

**Comment by tersec** [comment]
It's worth rechecking with https://github.com/status-im/nim-beacon-chain/pull/1514 -- I was getting invalid block root errors until that bug was fixed.

**Comment by tersec** [comment]
Is this still an issue?

I'm syncing past slot 100k on `devel`.

**Comment by protolambda** [comment]
Not an issue for me anymore, it worked after updating
