### ISSUE TITLE
BLST SHA256 requires SSSE3, which not all x86 CPUs have

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#1555]
For example, https://cpu-benchmarks.com/cpu/amd-athlon-ii-x4-630/ does not support SSSE3.

https://github.com/supranational/blst/blob/d661d16655385b6d5d0dcabbd09995c2cae131e8/src/asm/sha256-x86_64.pl suggests that:
```
# sha256_block procedure for x86_64.
#
# This module is stripped of AVX and even scalar code paths, with
# raionale that
#
# a) AVX1 is [justifiably] faster than SSSE3 code path only on *one*
#    processor, venerable Sandy Bridge;
# b) AVX2 incurs costly power transitions, which would be justifiable
#    if AVX2 code was executing most of the time, which is not the
#    case in the context;
# c) all comtemporary processors support SSSE3, so that nobody would
#    actually use scalar code path anyway;
```

In particular, it uses `pshufb`/`pshufd` extensively.

It's possible that BLST requires SSSE3 or newer elsewhere.

This has resulted in `SIGILL` when running with default settings, while `make NIMFLAGS="-d:BLS_FORCE_BACKEND=miracl" medalla` works fine.

x86 machines which don't support SSSE3, which AMD only started doing by 2011 or so, should be able to run nimbus.

**Comment by mratsim** [comment]
Fixed by https://github.com/status-im/nim-beacon-chain/pull/1560 and https://github.com/status-im/nim-blscurve/pull/72
