### ISSUE TITLE
BLST compact unwind warning on mac

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1634]
libbacktrace gives the following warning when compiling any library (beacon_node, ncli_db, ...) on MacOS

> ld: warning: could not create compact unwind for _sha256_block_data_order: does not use RBP or RSP based frame

This is non-blocking but will likely trigger questions from user.

The code that is pointed at is an assembly proc from BLST when libunwind tries to create a stacktrace for it.

**Comment by stefantalpalaru** [comment]
I don't think this has anything to do with libbacktrace or libunwind - both disabled on macOS, until this PR lands, BTW: https://github.com/status-im/nim-beacon-chain/pull/935

It's just the linker complaining about Assembly code in BLST that prevents it from generating smaller DWARF debugging info.

There is a flag to disable that compact format: `-Wl,-no_compact_unwind` but the Rust guys found it to be buggy on some old macOS version, and modified their Asm code instead to have the linker skip specific objects: https://github.com/rust-lang/rust/pull/10013

The libffi folks went further and wrote their own compact unwinding sections in Asm: https://github.com/libffi/libffi/pull/440/files

All these Asm shenanigans are too complicated for us, so just use the compiler/linker flag instead.

**Comment by mratsim** [comment]
Fixed by #1789
