### ISSUE TITLE
Disable LTO for crypto libraries

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#1666]
https://github.com/status-im/nim-beacon-chain/pull/1661 enables LTO but doing so has little benefit for already-optimized code and the more aggressive compiler-based optimizations may interfere with efforts to make crypto code constant-time - thus libraries like blst and bearssl should see LTO disabled in their builds.

see also https://www.cl.cam.ac.uk/~rja14/Papers/whatyouc.pdf

To investigate:

* [x] blst
* [ ] libsecp256k1
* [ ] milagro
* [x] bearssl

**Comment by mratsim** [comment]
Closed by #1789
