### ISSUE TITLE
Sync stalling

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1678]
Master: https://github.com/status-im/nim-beacon-chain/tree/4b38619c4f51847fc591e85327ed226ad46d24ac

![image](https://user-images.githubusercontent.com/22738317/93429590-ae9b2080-f8c1-11ea-8b2a-13f474abf8a6.png)

**Comment by mratsim** [comment]
Related #1654 apparently didn't fix the sync

**Comment by cheatfate** [comment]
I think this should be fixed by https://github.com/status-im/nim-beacon-chain/pull/1707
