### ISSUE TITLE
Keystore Scrypt test on 32-bit platforms: integer outside of valid range

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1701]
https://github.com/status-im/nim-beacon-chain/runs/1134992428?check_suite_focus=true#step:12:563

![image](https://user-images.githubusercontent.com/22738317/93630108-b8b83e80-f9e9-11ea-8f20-690972932a32.png)

I'm curious why Azure Pipelines 32-bit didn't catch that while Github Action does.

Also, I think all crypto libraries should be `{.push: [Defect].}` at the very least and `{.push: [].}` ideally.

**Comment by tersec** [comment]
Azure does catch it, sort of, if one views the logs. It just erroneously doesn't cause the CI to fail: https://github.com/status-im/nim-beacon-chain/pull/1716#issuecomment-696204490

https://github.com/status-im/nim-beacon-chain/issues/1226 / https://github.com/status-im/nim-beacon-chain/issues/1404 is why it wasn't more visible.

**Comment by mratsim** [comment]
The issue is this integer 3141592653 in https://github.com/status-im/nim-beacon-chain/blob/4b38619c4f51847fc591e85327ed226ad46d24ac/tests/test_keystore.nim#L136-L140

It requires 32-bit and `int` on 32-bit platforms is 32-bit.

**Comment by stefantalpalaru** [comment]
> It requires 32-bit

64 bits.
