### ISSUE TITLE
Spadina - EIP2333 update?

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1722]
For release tracking

EIP2333 has been updated with non-backward compatible key generation changes.

The change is somewhat trivial https://github.com/ethereum/EIPs/pull/2985/files, it just loop if someone generated a 0 secret key (with 2^-255 probability)

In terms of timing we need to know if we have to release it for Spadina, see https://github.com/ethereum/eth2.0-deposit-cli/pull/108#issuecomment-696509418

**Comment by CarlBeek** [comment]
Indeed the change is trivial to implement, yet unfortunately it is still not backwards compatible. ([See the discussion on the BLS specs repo for why](https://github.com/cfrg/draft-irtf-cfrg-bls-signature/issues/28#issuecomment-693651086).)

For Spadina, the CLI will be using the updated EIP2333 key generation as discussed in https://github.com/ethereum/eth2.0-deposit-cli/pull/108#issuecomment-696630501

**Comment by mratsim** [comment]
Closed by #1742
