### ISSUE TITLE
Azure CI running out of space

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1727]
https://dev.azure.com/nimbus-dev/nim-beacon-chain/_build/results?buildId=9149&view=logs&j=2e1ef983-081d-5c63-b72a-d9f329364ee0&t=69fb04d4-8d32-57d9-fbcf-c139b9f5d9e0&l=669

![image](https://user-images.githubusercontent.com/22738317/93892372-c2dd8400-fcec-11ea-8ed9-b6f121d0e283.png)
![image](https://user-images.githubusercontent.com/22738317/93892425-cd981900-fcec-11ea-9929-18dc1eab2054.png)

**Comment by mratsim** [comment]
A quick look shows that `vendor`+`.git` take 7.1 GB. Azure is limited to 10GB but we might reach that with the extra MinGW and binary downloading.

![image](https://user-images.githubusercontent.com/22738317/93898931-11dae780-fcf4-11ea-8fa1-4268c0d652d5.png)

We might want to GC all of our git repos and also ensure that no binary files remain in history.

**Comment by tersec** [comment]
We don't use 3GB of it at all:
```
$ find vendor/nim-eth2-scenarios/tests-v0.12.3/ -name phase1 -print0 | xargs -0 du -sh
183M	vendor/nim-eth2-scenarios/tests-v0.12.3/minimal/phase1
3.0G	vendor/nim-eth2-scenarios/tests-v0.12.3/mainnet/phase1
```

We can either remove `phase1` directories after tarball extraction or, ideally, not extract `phase1` at all.

Eventually, of course, we'll have to deal with this, but that should keep things working for months.

**Comment by mratsim** [comment]
For now Github Actions #1693 will replace Azure and Azure has been disabled.

![image](https://user-images.githubusercontent.com/22738317/94142775-1677db00-fe6f-11ea-8e29-6cdf2a4906f4.png)
