### ISSUE TITLE
hash_tree_root vs hash_tree_root_final

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#174]
our code confuses the naming here vs spec with regards to zero padding - needs updating (`hash_tree_root` is the padded version in spec)

**Comment by mratsim** [comment]
I think the spec evolved to finally produce digests from the hash_tree_root function but we kept the old name for the old meaning in https://github.com/status-im/nim-beacon-chain/commit/eb369cee4e5e5773fe98238ee34b1fefb765ad06
