### ISSUE TITLE
Validator being slashed due to double voting

### ISSUE THREAD

**Issue by deni64k** [status-im/nim-beacon-chain#1741]
**Describe the bug**

My validator (index=57389) was slashed due to double voting.
https://beaconcha.in/block/366747#attester-slashings

**To Reproduce**
1. Platform details (OS, architecture): macOS Catalina
2. Branch/commit used: 4b38619c4f51847fc591e85327ed226ad46d24ac
3. Commands being executed:
Beacon chain:
```
beacon_node
    --log-file=/Volumes/Brick/Nimbus/beacon_node.log
    --data-dir=/Volumes/Brick/Nimbus
    --network=medalla
    --web3-url=http://127.0.0.1:8545  # geth
    --rpc
    --rpc-port=32000
    --metrics
    --metrics-address=127.0.0.1
    --metrics-port=32800
    --tcp-port=32900
    --udp-port=32900
    --nat=upnp
    --max-peers=128
    --bootstrap-node=/ip4/127.0.0.1/udp/30900/p2p/16Uiu2HAmNyYXoDNs8UQdQTw68iCiEbrA35HFn4XY8iftpBcapTfH
    --bootstrap-node=/ip4/127.0.0.1/udp/31900/p2p/16Uiu2HAm5Dy171dMk8pGa8CJGSTpjZCKHPB91ge5cEhiM6WTMWNH
    --bootstrap-node=enr:-LK4QIPlgLPBLIyaH8PUT6751AjvIqHCNKmQthhu15zcXXbUaR5hrgv2_iDq_tNwll6yrx6FFSN8R7UuP9dRl2iXWctVh2F0dG5ldHOIBAAAAAAAAAGEZXRoMpDnp11aAAAAAf__________gmlkgnY0gmlwhBg0-F2Jc2VjcDI1NmsxoQOZVbYQfaALkrCWIa3oQ8HwAawsuzTSWM-Qjao7UHk2nIN0Y3CCdTCDdWRwgni-
    --graffiti=poap/82gTkKFPl2OurOGCJWA72XufMUD
```
   Validator:
```
validator_client
    --data-dir=/Volumes/Brick/Nimbus
    --validators-dir=/Volumes/Brick/Nimbus/validators
    --graffiti=poap/82gTkKFPl2OurOGCJWA72XufMUD
    --rpc-port=32000
```
4. Relevant log lines:
Here are all logs I collected:
https://ipfs.io/ipfs/QmcUxL7gG7mwonPP1z2UzvmHGL5jM4NrKZfKUHCtyJeM2S?filename=nimbus-report.tar.lzma

I can also share the validator's keypair if needed.

**Screenshots**

**Additional context**

**Comment by mratsim** [comment]
Sorry, I forgot to reply. This has been found by the auditor as well and I've fixed the issue the day after your issue. It's in master since the weekend.

Thanks for your support.
