### ISSUE TITLE
Drastically reduce logging verbosity

### ISSUE THREAD

**Issue by q9f** [status-im/nim-beacon-chain#1785]
I'm running a nimbus node on Medalla from latest master.

Related to #1779 it's difficult to see what the node is doing. Mainly due to too many messages in INFO level.

The default logging should be changed from DEBUG to INFO.

The INFO level should be drastically reduced.

24h of JSON log file create a 2+ GB file:

```
2.1G -rw-r--r-- 1 user users 2.1G Oct  1 12:42 beacon_node.log
```

24h of piping the standard output to a file, generates 3+ GB:

```
3.0G -rw-r--r-- 1 user users 3.0G Oct  1 12:49 nimbus-out.log
```

It should be reduced by 3 orders of magnitude if possible :)

**Comment by tersec** [comment]
> The default logging should be changed from DEBUG to INFO.

https://github.com/status-im/nim-beacon-chain/pull/1777 does exactly this. It's in `devel` already and will be merged into `master` whenever the next merge happens.

**Comment by mratsim** [comment]
This has been solved in master. Log level have been significantly shuffled, and INFO has been made the default.

You should expect 2 log lines per slot/every 6 seconds + the occasional finality message with default logging.

![image](https://user-images.githubusercontent.com/22738317/94930245-689baa80-04c6-11eb-9bc9-b55f8702ee11.png)

Logging strategy has been documented as well at https://github.com/status-im/nim-beacon-chain/blob/c5a58555/docs/logging.md
