### ISSUE TITLE
Error: cannot export: blscurve.update

### ISSUE THREAD

**Issue by lufa23** [status-im/nim-beacon-chain#1814]
Nimbus node could not connect with other peers, so i made a git pull to try to fix the problem.

Now, when launching "make medalla" i get:
"nim-beacon-chain/beacon_chain/spec/digest.nim(42, 18) Error: cannot export: blscurve.update"

How can i fix it?

Thanks

**Comment by mratsim** [comment]
did you do a `make update`?

**Comment by lucafra23** [comment]
yep, it works! thanks a lot for the fast reply
