### ISSUE TITLE
Same state hash with different slots

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#198]
![DeepinScreenshot_select-area_20190322172237](https://user-images.githubusercontent.com/22738317/54837662-41f09700-4cc7-11e9-8f7c-1b974f621fd0.png)

Following the "Preparing for fork choice" logs, during the replay of state transition, the replay starts from the same state hash but seemingly at different slots.

**Comment by arnetheduck** [comment]
that's a block hash. what happened was that someone did not see any block at slot 1, hence used the block from the previous slot.
