### ISSUE TITLE
RFC: Logging levels

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#205]
so regarding logging, to tune it so that operators can run `INF` and developers `DBG`, I would suggest the following guidelines:

* `NOT` noteworthy events that are unusual as far as normal operation goes: (deep?) chain reorgs, slashings etc
* `INF` logs anything that is sufficient to recreate the state along important checkpoints in the application, but does so in a minimal way, so as not to overwhelm log collectors - minimal in this sense means that it strives to avoid duplicating the same information - kind of like a normalized database - people running the app on a server should not be discouraged from always keeping INF on
* `DBG` denormalizes the above and adds more checkpoints - repetition for convenience is ok, but we still keep it out of tight loops - developers will have this on by default
* `TRC` anything goes

we can stick these in a document somewhere once we have a bit more agreement on the practical application of them, in nimbus specifically

**Comment by mratsim** [comment]
Given that it didn't raise any wave, I assume it's accepted, now in both wikis:

- https://github.com/status-im/nim-beacon-chain/wiki/Log-levels
- https://github.com/status-im/nimbus/wiki/Log-levels
