### ISSUE TITLE
build error for v1.0.6 on arm

### ISSUE THREAD

**Issue by johba37** [status-im/nim-beacon-chain#2224]
**Describe the bug**

can't build beacon node from source.

**To Reproduce**
1. Platform details (OS, architecture): `raspberry pi 4b, arm`
2. Branch/commit used: `87955f2d37c7b7e8b9f8ae1c47c9d354c59a1c34`
3. Commands being executed: `make nimbus_beacon_node`
4. Relevant log lines: 
```
Building: build/nimbus_beacon_node
/home/pi/nimbus-eth2/beacon_chain/eth2_network.nim(1598, 14) Error: expression 'subscribe(node.pubsub, topic & "_snappy", dummyMsgHandler)' is of type 'Future[system.void]' and has to be discarded; start of expression here: /home/pi/nimbus-eth2/beacon_chain/eth2_network.nim(1595, 3)
make: *** [Makefile:173: nimbus_beacon_node] Error 1
```

**Comment by stefantalpalaru** [comment]
What's the output of `file /bin/bash` ?

**Comment by arnetheduck** [comment]
this looks like a case of missing `make update` before running `make nimbus_beacon_node`, did you run that first? See also https://status-im.github.io/nimbus-eth2/keep-updated.html

**Comment by johba37** [comment]
> this looks like a case of missing make update before running

exactly. thanks for the reminder.
