### ISSUE TITLE
Remove std/random

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#2256]
We reintroduced std/random in https://github.com/status-im/nimbus-eth2/pull/2255 to unbreak the `unstable` branch.

It is used here: https://github.com/status-im/nimbus-eth2/blob/718feef802a7aacdfa972a9b67aed83414848e19/beacon_chain/nimbus_beacon_node.nim#L650-L664

We should remove its usage (except in test) and err on the side of safety.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/commit/960666d1ed936aadb3982eb06fb58be8389e8d23 removes this usage and `nimbus_beacon_node`'s import of `random`.

Remaining users are:
https://github.com/status-im/nimbus-eth2/blob/960666d1ed936aadb3982eb06fb58be8389e8d23/beacon_chain/validator_duties.nim#L537-L557

https://github.com/status-im/nimbus-eth2/blob/960666d1ed936aadb3982eb06fb58be8389e8d23/beacon_chain/deposit_contract.nim#L259-L261

https://github.com/status-im/nimbus-eth2/blob/960666d1ed936aadb3982eb06fb58be8389e8d23/beacon_chain/nimbus_binary_common.nim#L44-L45

The last one presumably only supporting the existence of the other two.

With those gone, only cases where Nim PRNG weaknesses don't matter, such as `state_sim`, `block_sim`, tests, and benchmarks will use it in the `nimbus-eth2` repo itself.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/2442 removes these.
