### ISSUE TITLE
Eth1 sync: Corrupted deposits history detected

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-beacon-chain#2261]
Node on mainnet seems to be in a state where the deposits from eth1 that this node got from the eht1 provider diverged from the ones seen in eth2 block?
It doesn't recover and no new requests to the eth1 provider (infura) are done. Haven't restarted the node, yet.

Repeated log message
```
{"lvl":"ERR","ts":"2021-01-25 10:44:05.293+01:00","msg":"Corrupted deposits history detected","topics":"eth1","tid":52736,"file":"eth1_monitor.nim:630","ourDepositsCount":88037,"taretDepositsCount":88042,"ourDepositsRoot":"22339c10","targetDepositsRoot":"76504b41"}
{"lvl":"DBG","ts":"2021-01-25 10:44:05.294+01:00","msg":"No acceptable eth1 votes and no recent candidates. Voting no change","topics":"eth1","tid":52736,"file":"eth1_monitor.nim:691"}
```

Proposal data:
```
curl -d '{"jsonrpc":"2.0","id":"id","method":"getEth1ProposalData","params":[] }' -H 'Content-Type: application/json' localhost:9190 -s | jq '.result'
{
  "vote": {
    "deposit_root": "0x76504b41c63af66b116b87f0816447c46000da183e5e24fda72cabd40eeaec47",
    "deposit_count": 88042,
    "block_hash": "0xf062284ff4a0214c696812a7efd5cfc18c279c02958457b24f0661f8d35a5369"
  },
  "deposits": [],
  "hasMissingDeposits": false
}
```

When I run `curl -d '{"jsonrpc":"2.0","id":"id","method":"getEth1Chain","params":[] }' -H 'Content-Type: application/json' localhost:9190 -s | jq '.result'` however, the last block  returned shows:

```
"voteData": {
      "deposit_root": "0xc1cfc6514811abe6f0a2d75a2867b7452dedef61f141dca5e1c5fdb1d49c75bc",
      "deposit_count": 101386,
      "block_hash": "0x5d908ac3c6a5864c9af0008502a457776f410907a70b97abcc1cc694ab27a9a5"
    }
```

There is also a block in there with `deposit_count: 88037` and `deposit_root: 0x22339c10`, but not with `88042` and `76504b41`.

**Comment by zah** [comment]
A fix for this will be shipped in the next release. Until then, restarting the node is a safe way to restore normal operation (the error should have low probability of appearing again).

**Comment by kdeme** [comment]
One pointer from @zah was to check the (new) `eth1_chain_len` metric. When this issue happens a huge increase is seen which is followed by the chain being stuck.

An alarm (for example in Grafana) can be set on such increase and/or on a rate of 0 to warn you of this (or any other) issue.
