### ISSUE TITLE
Show default options on nimbus --help

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#2284]
For configuration it would be helpful to show default option in confutils on --help.

**Comment by stefantalpalaru** [comment]
I don't see a way to inject code execution at the time nim-confutils generates the help message (which is needed for anything other than static string default values) nor a way to do string manipulation in the pragma-based DSL used for declaring options.

**Comment by arnetheduck** [comment]
Done in https://github.com/status-im/nim-confutils/commit/bb6cbf6e0d407934b9dabeff712c5b69264285cf and other places
