### ISSUE TITLE
Cannot compile Nimbus 1.0.7: make: *** No rule to make target 'beacon_node'.  Stop.

### ISSUE THREAD

**Issue by ZaneCEO** [status-im/nim-beacon-chain#2295]
**Describe the bug**
The new version 1.0.7 cannot be compiled.  `make beacon_node` gives this error:

`make: *** No rule to make target 'beacon_node'.  Stop.`

**To Reproduce**

On Ubuntu 20.04:

````
git clone https://github.com/status-im/nimbus-eth2.git
cd nimbus-eth2
make -j4 beacon_node
````

**Additional context**
In 1.0.6, `make` worked  just fine.

**Comment by ZaneCEO** [comment]
Ok, I found the issue. The old version had this into the [makefile](https://github.com/status-im/nimbus-eth2/blob/v1.0.6/Makefile):

````
# Targets for backwards compatibility
beacon_node: | nimbus_beacon_node
	cp build/nimbus_beacon_node build/beacon_node
````
It's now removed, so the only working command is `make nimbus_beacon_node`

Did you guys announced this change anywhere?

**Comment by kdeme** [comment]
Yes, we forgot to mention this in the release notes initially.

They have been updated to address this: https://github.com/status-im/nimbus-eth2/releases/tag/v1.0.7

Thanks for mentioning this!

**Comment by ZaneCEO** [comment]
Got it, thanks!
