### ISSUE TITLE
Give user feedback on why metrics are missing

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#2303]
Currently if I compile the beacon node without `-d:insecure` the metrics server returns an empty response:
```
 > curl -sv localhost:9300/metrics
*   Trying 127.0.0.1:9300...
* Connected to localhost (127.0.0.1) port 9300 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:9300
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
```
That's pretty bad user experience. Would it be possible to at least return to a user some kind of hint like:
```
This node binary was compiled without -d:insecure flag, metrics are not available.
```
Or something like that, to avoid confusing the users.

**Comment by zah** [comment]
hrm, without `-d:insecure` the metrics port should not be opened at all (instead you get a warning during initialiasation telling you that `--metrics:on` was ignored). I'm wondering whether this failed to work for some reason or it was `curl` that tricked you to believe that the port is open, but an empty response was received.

**Comment by jakubgs** [comment]
Nope:
```
 > d exec -it -u root nimbus-eth2 bash
root@273afd7b9104:/home/user/nimbus-eth2# netstat -lpnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:11000           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.11:36067        0.0.0.0:*               LISTEN      -                   
tcp        1      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      -       
```
If I used a port that wasn't open this is what I'd get from Curl:
```
 > curl -sv localhost:1234/metrics
*   Trying 127.0.0.1:1234...
* connect to 127.0.0.1 port 1234 failed: Connection refused
* Failed to connect to localhost port 1234: Connection refused
* Closing connection 0
```

**Comment by jakubgs** [comment]
Ah wait, I see why it appears as open. It's because of the port remapping done by Docker. So the error isn't `Connection refused`.

**Comment by jakubgs** [comment]
That might be confusing to users, but it's an edge case since it's just Docker. I guess it's fine.
