### ISSUE TITLE
CT/RT table hash mismatch when using a first iteration Nim-1.2.6 compiler [experimental setup; debugging aid]

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nim-beacon-chain#2310]
In order to replicate this, you need to change "vendor/nimbus-build-system/scripts/build_nim.sh" so it saves "nim1":

```diff
@@ -167,7 +167,8 @@ build_nim() {
                        --skipParentCfg \
                        compiler/nim.nim
                cp -a compiler/nim bin/nim
-               rm bin/nim1
+               cp -a compiler/nim bin/nim2
+               #rm bin/nim1
        fi
 
        # record the last commit's timestamp
```

Then rebuild the Nim compiler and copy "nim1" over "nim":

```text
rm vendor/nimbus-build-system/vendor/Nim/bin/timestamp
make -j8 QUICK_AND_DIRTY_COMPILER=1 build-nim
cp -a vendor/nimbus-build-system/vendor/Nim/bin/nim1 vendor/nimbus-build-system/vendor/Nim/bin/nim
```

Rebuild "nimbus_beacon_node":

```text
rm -rf nimcache; make -j8 nimbus_beacon_node
```

Try to run the beacon node on mainnet:

```text
$ WEB3_URL="wss://mainnet.infura.io/ws/v3/YOUR_TOKEN" ./run-mainnet-beacon-node.sh
# ...
INF 2021-02-10 19:19:38.971+01:00 Loading block dag from database            topics="beacnde" tid=26569 file=nimbus_beacon_node.nim:213 path=build/data/shared_mainnet_0/db
INF 2021-02-10 19:20:08.981+01:00 Block dag initialized                      topics="beacnde" tid=26569 file=chain_dag.nim:440 head=d4d1d01d:107258 finalizedHead=25180773:107168 tail=4d611d5b:0 totalBlocks=104997
INF 2021-02-10 19:20:08.982+01:00 Starting JSON-RPC HTTP server              topics="JSONRPC-HTTP-SERVER" tid=26569 file=httpserver.nim:215 url=http://127.0.0.1:9190
FAT 2021-02-10 19:20:08.988+01:00 Could not obtain PeerID from network key   topics="networking" tid=26569 file=eth2_network.nim:1390
# quits with an exit code of 1
```

**Comment by stefantalpalaru** [comment]
Mystery solved. Nim-0.20.0, the bootstrapping compiler, doesn't define "nimToOpenArrayCString" (in "compiler/condsyms.nim") and that changes the contents of `hash(x: string)` in "lib/pure/hashes.nim" (used for the VM): https://github.com/nim-lang/Nim/blob/bf320ed172f74f60fd274338e82bdc9ce3520dd9/lib/pure/hashes.nim#L220

This means that `nim1`, the first iteration of 1.2.6, compiled by 0.20.0, has different string hash implementations in the VM and in the standard library, leading to key mismatches in tables built at compile time and accessed at run time, hence the fatal error above.

It also means that `nim2` - the second bootstrap iteration of 1.2.6 - is the first usable one, because the VM was built using the same defines as those enabled by default when using the new compiler.

The number of defines involved is quite large: https://gist.github.com/stefantalpalaru/af3e8296e68ac3e94ff40c5e8c99605b

**Comment by mratsim** [comment]
So we need updated csources? @Araq thoughts?

**Comment by Araq** [comment]
You need to build Nim like every officially supported version of Nim is built...
