### ISSUE TITLE
Add a metric for attestation inclusion distance

### ISSUE THREAD

**Issue by jclapis** [status-im/nim-beacon-chain#2324]
This came from a conversation with @arnetheduck regarding the Grafana challenge. I'm looking for metrics that capture Nimbus's performance as seen by the Beacon chain, which I use https://beaconcha.in for now. One thing I'd like to see is the inclusion distance for each attestation, so I can try to understand what caused it via the rest of the collected metrics. 

I'm not sure how this would actually be implemented because the distance might end up being different than what the canonical chain reports over time. Maybe look back at the last finalized epoch, and report the numbers from that? There would be a delay while you wait for an epoch to finalize, but at least you know it'll be correct.

**Comment by zah** [comment]
Besides the inclusion distance, we'll be looking into all factors that affect the profitability of the node:

* Was our attestation missed?
* Did it end in an orphaned block?
* Did our votes match the consensus?

**Comment by arnetheduck** [comment]
#2925 adds these metrics and more
