### ISSUE TITLE
Implement light client syncing

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#2337]
To be broken down into smaller steps that will be tracked here as an epic.

**Comment by etan-status** [comment]
References:
- EF sync protocol spec (applying `LightClientUpdate` to `LightClientStore`)
   https://github.com/ethereum/consensus-specs/blob/v1.1.0/specs/altair/sync-protocol.md
- EF test suite (applying `LightClientUpdate` to `LightClientStore`)
   https://github.com/ethereum/consensus-specs/blob/v1.1.0/tests/core/pyspec/eth2spec/test/altair/unittests/test_sync_protocol.py
- Lodestar light client demo (requires some tweaks to run)
   https://github.com/ChainSafe/eth2-light-client-demo/tree/dapplion/update-to-prater
- Lodestar REST API (API and light client implementation is Apache 2, other components may be GPL)
   https://github.com/ChainSafe/lodestar/blob/v0.31.0/packages/api/src/routes/lightclient.ts
- C# light client demo
   https://github.com/uink45/Beacon-Chain-Light-Client-Prototype
- EF merkle multiproof spec
   https://github.com/ethereum/consensus-specs/blob/v1.1.3/ssz/merkle-proofs.md#merkle-multiproofs
- Lodestar merkle multiproof spec (different ordering than EF, plus metadata)
   https://github.com/protolambda/eth-merkle-trees/blob/master/tree_offsets.md
- Lodestar discord (ETH2 -> #light-client)
   https://discord.gg/b8WpNbPtqX
- Nimbus discord (DEV -> #light-client)
   https://discord.gg/xEYQ7RPS6k
- EF discord (CONSENSUS R&D -> #light-clients)
   https://discord.gg/FwhpbfwXUt
- Telegram (beacon-chain-light-client-implementers)
- https://github.com/ethereum/consensus-specs/pull/2267
- https://github.com/ethereum/consensus-specs/pull/2746
- https://github.com/ethereum/consensus-specs/pull/2786
- https://github.com/ethereum/consensus-specs/pull/2829
- https://github.com/jinfwhuang/prysm/pull/5

Specs:
1. https://github.com/ethereum/consensus-specs/pull/2805
2. https://github.com/ethereum/consensus-specs/pull/2916 
3. https://github.com/ethereum/consensus-specs/pull/2924 
4. https://github.com/ethereum/consensus-specs/pull/2927 
5. https://github.com/ethereum/consensus-specs/pull/2929
6. https://github.com/ethereum/consensus-specs/pull/2932
7. https://github.com/ethereum/consensus-specs/pull/2935
8. https://github.com/ethereum/consensus-specs/pull/2938
9. https://github.com/ethereum/consensus-specs/pull/2944
10. https://github.com/ethereum/consensus-specs/pull/2947
11. https://github.com/ethereum/consensus-specs/pull/2951
12. https://github.com/ethereum/consensus-specs/pull/2802

Implementation progress:
- [x] Light client bootstrap (interfacing with checkpoint sync)
    https://github.com/status-im/nimbus-eth2/pull/4736
- [x] Drive EL from LC
    https://github.com/status-im/nimbus-eth2/pull/3865
- [x] Persisting light client data on server
    https://github.com/status-im/nimbus-eth2/pull/3832
    https://github.com/status-im/nimbus-eth2/pull/3823
- [x] Optimistic sync
   https://github.com/status-im/nimbus-eth2/pull/3715
   - [x] Integrate light client into beacon node
          https://github.com/status-im/nimbus-eth2/pull/3557
- [x] Light client mode
       https://github.com/status-im/nimbus-eth2/pull/3653
- [x] Enable light client data serving
       https://github.com/status-im/nimbus-eth2/pull/3623
       https://github.com/status-im/nimbus-eth2/pull/3559
    - [x] https://github.com/status-im/infra-nimbus/pull/91
    - [x] https://github.com/status-im/infra-nimbus/pull/89
       - [x] https://github.com/status-im/infra-nimbus/pull/90
          - [x] https://github.com/status-im/infra-role-beacon-node-linux/pull/7
          - [x] https://github.com/status-im/infra-role-beacon-node-macos/pull/3
          - [x] https://github.com/status-im/infra-role-beacon-node-windows/pull/2
- [x] Light client server
  https://github.com/status-im/nimbus-eth2/pull/3341
  - [x] Gossip broadcasts
         https://github.com/status-im/nimbus-eth2/pull/3499
      - [x] Gossip validation
               https://github.com/status-im/nimbus-eth2/pull/3486
  - [x] Light client data collection (server side)
         https://github.com/status-im/nimbus-eth2/pull/3474
- [x] Light client LibP2P protocols
       https://github.com/status-im/nimbus-eth2/pull/3465
  - [x] Propose spec to EF, based on iterations on Lodestar REST API to bring it as close as possible to something compatible with P2P
       https://github.com/ethereum/consensus-specs/pull/2802
- [x] REST endpoints to allow light client syncing to latest block header (Lodestar compatible), when a startup flag is specified, and documentation on how to run it
        https://github.com/status-im/nimbus-eth2/pull/3775
  - [x] Update `eth2-light-client-demo` to Lodestar v0.32
          https://github.com/ChainSafe/eth2-light-client-demo/pull/9
          https://github.com/ChainSafe/eth2-light-client-demo/pull/12
  - [x] Chronos support for long-running REST handler
          https://github.com/status-im/nim-chronos/pull/234
  - [x] Helpers to access merkle multiproof generation
         #3119
    - [x] 64-bit `GeneralizedIndex`
           https://github.com/status-im/nim-ssz-serialization/pull/13
    - [x] Merkle multiproof generation / Merkle proof for non-root indices
         https://github.com/status-im/nim-ssz-serialization/pull/16
      - [x] Prepare merkleization code for code-reuse with multiproofs / non-root indices
             https://github.com/status-im/nim-ssz-serialization/pull/14
             https://github.com/status-im/nim-ssz-serialization/pull/12
    - [x] Compile-time optimization support
           https://github.com/nim-lang/Nim/pull/19035
    - [x] Merkle multiproof verification
           #2980
  - [x] Make `/eth/v1/config/spec` compatible with Lodestar light client
          #2962 
- [x] EF light client tests
       #2923
