### ISSUE TITLE
Support HF1 in local sim

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#2338]
We should prepare all necessary changes to be able to simulate a network of HF1-enabled clients or to participate in a shared testnet with other teams. The introduction of the sync committees and related structures is a necessary part of this effort, but the implementation of light client sync will be tracked in a [separate issue](https://github.com/status-im/nimbus-eth2/issues/2337).

**Comment by tersec** [comment]
Done months ago.
