### ISSUE TITLE
Upgrade to Nim 1.2.10

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#2340]
As part of this effort, we'll improve our ability to test the same commit in CI against multiple versions of Nim.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/2353

**Comment by tersec** [comment]
Currently blocked by https://github.com/status-im/nimbus-eth2/pull/2297

**Comment by tersec** [comment]
Currently blocked by https://github.com/status-im/nimbus-eth2/issues/2430

**Comment by tersec** [comment]
Closed by https://github.com/status-im/nimbus-eth2/pull/2508
