### ISSUE TITLE
sync fails, too much data in single message

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#236]
```
DBG 2019-04-03 20:31:12-06:00 Ending dispatchMessages loop               topics="rlpx" tid=5421 err="RLPx message exceeds maximum size" peer=Node[188.166.38.238:9000]
```

cf2b9e5a84e41639935909eab2fb1a4e41812baf

**Comment by cheatfate** [comment]
If i remember correctly maximum size of RLP message is 16,777,216 bytes, because length is encoded via 24bit integer.

**Comment by arnetheduck** [comment]
1mb: https://github.com/status-im/nim-eth/blob/master/eth/p2p/rlpx.nim#L16
