### ISSUE TITLE
Add a metric for nextActionWait

### ISSUE THREAD

**Issue by jclapis** [status-im/nim-beacon-chain#2362]
As of v1.0.8, Nimbus now provides the `nextActionWait` information in the log which indicates how long until the next attestation / block proposal. I would like to include this in my Grafana dashboard. Can it be exported as a metric?

**Comment by tersec** [comment]
To clarify slightly, it doesn't yet show information about the next block proposal. They're rare enough, at .03% per epoch per validator currently and dropping, that it was worth getting in this way at first, and it seemed better not to change the name of the field when, yes, that's the obvious next step, and why it's named more generally.

The other sometimes-broadcast-validator-role is aggregate attestations, but they only occur when a validator's already not-aggregate attesting in that slot/committee, so it's only important to get beacon block proposal to complete this.

But I agree, this seems like a worthwhile metric.

In the meantime, one can get this from the RPC call (so the information is definitely available):
```
curl -d '{"jsonrpc":"2.0","method":"get_v1_validator_duties_proposer","params":[${EPOCH_NUMBER_OF_INTEREST}],"id":1}' -H 'Content-Type: application/json' localhost:9190 -s | jq ".result[]" | grep ${PATTERN_WHICH_MATCHES_VALIDATOR_PUBLIC_KEYS}
```

**Comment by tersec** [comment]
Implemented in https://github.com/status-im/nimbus-eth2/pull/2399
