### ISSUE TITLE
Error: cannot export: SignatureSet

### ISSUE THREAD

**Issue by q9f** [status-im/nim-beacon-chain#2379]
**Describe the bug**
I cannot compile nimbus_beacon_node 1.0.8

```
~/nimbus-eth2 tags/v1.0.8* user@gudja
❯ make -j $(nproc) nimbus_beacon_node
Building: build/nimbus_beacon_node
/home/user/nimbus-eth2/beacon_chain/spec/signatures_batch.nim(19, 8) Error: cannot export: SignatureSet
make: *** [Makefile:294: nimbus_beacon_node] Error 1
```

**To Reproduce**
1. Platform details (OS, architecture): Archlinux, kernel `Linux gudja 5.10.11-arch1-1 x86_64 GNU/Linux`
2. Branch/commit used: `tags/v1.0.8`
3. Commands being executed: `make -j $(nproc) nimbus_beacon_node`
4. Relevant log lines: `/home/user/nimbus-eth2/beacon_chain/spec/signatures_batch.nim(19, 8) Error: cannot export: SignatureSet`

**Additional context**
Compiling 1.0.6 that way used to work fine.

**Comment by arnetheduck** [comment]
did you run `make update`? https://nimbus.guide/keep-updated.html

**Comment by q9f** [comment]
ok, that worked - thanks!

I proposed adding a link to the build page :)

**Comment by arnetheduck** [comment]
thanks! the next time you update, `make` will print a friendly reminder if you forget `update`, but for that to work.. well... `make update` was needed :)
