### ISSUE TITLE
FDs leaking if ETH1 fails to connect

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nim-beacon-chain#2386]
My Geth node crashed, I failed to notice and nimbus kept going on eating file descriptors while attempting to connect to geth.

![image](https://user-images.githubusercontent.com/7008900/110228829-9f7b5e00-7f47-11eb-8581-f10db2a098ea.png)

Reaching 1024 limit metrics failed to open `stat` but this could have lead to losing connections etc.

**Comment by arnetheduck** [comment]
#2388
