### ISSUE TITLE
Publish a Docker image for ARM64

### ISSUE THREAD

**Issue by jclapis** [status-im/nim-beacon-chain#2401]
I'm posting this request at the suggestion of @arnetheduck.

While helping a user stand up a new eth2 validation node, Rocket Pool's installer uses Docker as its solution for setting up the eth1 and eth2 clients. It links to the official images maintained by the client teams on Docker Hub. This poses a challenge for users on ARM platforms, because none of the eth2 client teams publish official ARM images - everything is all x64. For the others, I can understand this focus on x64 but Nimbus openly claims to embrace ARM64 platforms like the Raspberry Pi [in its description](https://nimbus.team/) so it would make sense to support them with an official Docker image as well.

As a workaround, I build my own Docker image that just houses the `nimbus_beacon_node` binary and replicates the x64 image's folder structure. This is probably acceptable while Rocket Pool is still in beta but in the coming production release to mainnet, it would be ideal if it could link to an official ARM64 image for two reasons:

1. Official releases are far more trustworthy than using an image published by some random guy on the Internet
2. The current setup relies on my maintaining the images / building and pushing new releases

I see that there's some action on the ARM64 Dockerfile in PR #2391 but don't know if that's in preparation to support an official release or not. If it is, then this issue will probably get resolved pretty quickly.

**Comment by stefantalpalaru** [comment]
Solved.
