### ISSUE TITLE
Add Support for Prysm's Graffiti File Format

### ISSUE THREAD

**Issue by jclapis** [status-im/nim-beacon-chain#2405]
This is a request from the Rocket Pool and EthStaker community. We would like the ability to coordinate drawing on the [beaconcha.in graffiti wall](https://beaconcha.in/graffitiwall). Currently this ability appears to be only supported by Prysm, via their [graffiti file](https://docs.prylabs.network/docs/prysm-usage/graffiti-file/) standard. Would it be possible to implement support for something like this file in Nimbus, so that we could further encourage its use by the Rocket Pool community for this purpose? It would go a long way towards promoting client diversity, otherwise anyone involved in this project would be forced to use Prysm.

The exact format isn't strictly necessary; it can be migrated to JSON without issue.

Note that this file may be updated after launching Nimbus, so the ideal solution would update from it dynamically - either by being notified of changes and reloading, or by simply re-reading it prior to each attestation.

**Comment by stefantalpalaru** [comment]
This API should be safer for dealing with potentially hostile YAML: https://nimyaml.org/yaml.dom.html

**Comment by zah** [comment]
Would it be reasonable for the graffiti string to be updated through a RPC call? Besides being more flexible, this approach is also easier to implement.

**Comment by zah** [comment]
A new `setGraffiti` JSON-RPC call has been added to the `unstable` branch in 1af07ad1247b43bd79e775b7b466e767ec3f0ecf. Here is the added documentation:

### setGraffiti

Set the graffiti bytes that will be included in proposed blocks. The graffiti bytes can be
specified as an UTF-8 encoded string or as an 0x-prefixed hex string specifying raw bytes.

```
curl -d '{"jsonrpc":"2.0","id":"id","method":"setGraffiti","params":["Mr F was here"] }' -H 'Content-Type: application/json' localhost:9190 -s | jq
```

A similar end-point was added to our upcoming REST API beta in the `restapi` branch [here](https://github.com/status-im/nimbus-eth2/commit/69e41301fbd0e8d1b2edffab9308022f51442afe).
