### ISSUE TITLE
Validator APIs return validator's effective balance in place of actual balance

### ISSUE THREAD

**Issue by moles1** [status-im/nim-beacon-chain#2407]
**Describe the bug**
The following nimbus API endpoints return a validator's *effective balance* only, in place of its actual balance:
```
get_v1_beacon_states_stateId_validators
get_v1_beacon_states_stateId_validators_validatorId
get_v1_beacon_states_stateId_validator_balances
```

**To Reproduce**
Steps to reproduce the behavior: Call any of the above endpoints via JSON-RPC
1. Platform details (OS, architecture): Official docker image `statusim/nimbus-eth2:amd64-v1.0.10`
2. Branch/commit used: (as above)
3. Commands being executed: N/A
4. Relevant log lines:

Logged validator output from external code consuming the nimbus APIs:
```
// get_v1_beacon_states_stateId_validators
validator.Index: 101457
validator.Balance: 32000000000 // Effective balance; should be actual balance
validator.Status: active_ongoing
validator.Validator.Pubkey: 968bcf4081af4a10d054c1cde1dadfd6e85a120a397174173ca869f66bdc72835f9918ea251930778e5ba67a7907e30e
validator.Validator.WithdrawalCredentials: 00d77be6277f1cdcfce33fdcb127b95fe91e09eec04aecc521dc94866f0055f0
validator.Validator.EffectiveBalance: 32000000000
validator.Validator.Slashed: false
validator.Validator.ActivationEligibilityEpoch: 321
validator.Validator.ActivationEpoch: 684
validator.Validator.ExitEpoch: -1
validator.Validator.WithdrawableEpoch: -1

// get_v1_beacon_states_stateId_validator_balances
validator.Index: 101457
validator.Balance: 32000000000 // Effective balance; should be actual balance
```

Note that the validator queried has a balance greater than 32 ETH: https://pyrmont.beaconcha.in/validator/968bcf4081af4a10d054c1cde1dadfd6e85a120a397174173ca869f66bdc72835f9918ea251930778e5ba67a7907e30e

**Comment by arnetheduck** [comment]
fixed in #2480 which was released with 1.1.0
