### ISSUE TITLE
JSON logs contain non-JSON messages

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#2450]
Despite logs normally being JSON, sometimes the node outputs a log line that is not JSON:
```
message repeated 3 times: [ {"lvl":"DBG","ts":"2021-03-23 13:51:51.980+00:00","msg":"Could not establish send connection","topics":"libp2p pubsubpeer","tid":1,"file":"pubsubpeer.nim:201","msg":"Couldn't get muxed stream"}]
```
This causes errors on Logstash side when parsing, as well as when piping logs into [jq](https://stedolan.github.io/jq/):
```
admin@stable-large-03.aws-eu-central-1a.nimbus.prater:~ % tail -f /var/log/docker/beacon-node-prater-stable-large/docker.log | jq -c '. | select(.msg | contains("block"))'
parse error: Invalid numeric literal at line 127, column 8
```

**Comment by arnetheduck** [comment]
> message repeated 3 times

this is something the logging daemon adds most likely - Nimbus itself doesn't print this..

**Comment by arnetheduck** [comment]
https://serverfault.com/questions/30303/is-there-a-way-to-remove-last-message-repeated-x-times-from-logs
