### ISSUE TITLE
Deactivate Doppelganger Protection during genesis

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#2451]
Seen on prater launch, we wait for ~13min before the first attestations

![image](https://user-images.githubusercontent.com/22738317/112161399-67347a80-8beb-11eb-971a-04aff7f74028.png)

**Comment by tersec** [comment]
https://github.com/prysmaticlabs/prysm/issues/7985#issuecomment-843209422

**Comment by tersec** [comment]
Implemented in https://github.com/status-im/nimbus-eth2/pull/3362
