### ISSUE TITLE
Fix deprecated asyncCheck usage warnings

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#2458]
- [x] nimbus-eth2/tests/test_peer_pool.nim(458, 5) Warning: Raises Defect on future failure, fix your code and use asyncSpawn!; asyncCheck is deprecated [Deprecated]

- [x] nimbus-eth2/ncli/inspector.nim(741, 3) Warning: Raises Defect on future failure, fix your code and use asyncSpawn!; asyncCheck is deprecated [Deprecated]

- [x] nimbus-eth2/ncli/inspector.nim(751, 7) Warning: Raises Defect on future failure, fix your code and use asyncSpawn!; asyncCheck is deprecated [Deprecated]

- [x] nimbus-eth2/ncli/inspector.nim(754, 5) Warning: Raises Defect on future failure, fix your code and use asyncSpawn!; asyncCheck is deprecated [Deprecated]

- [x] nimbus-eth2/beacon_chain/nimbus_validator_client.nim(276, 5) Warning: Raises Defect on future failure, fix your code and use asyncSpawn!; asyncCheck is deprecated [Deprecated]

- [x] nimbus-eth2/beacon_chain/nimbus_validator_client.nim(340, 7) Warning: Raises Defect on future failure, fix your code and use asyncSpawn!; asyncCheck is deprecated [Deprecated]

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/commit/646923c3ddc03f7fb1cca65ff8c9839be6c246f9 fixes the `nimbus-eth2/tests/test_peer_pool.nim` one.

**Comment by bernardoaraujor** [comment]
@tersec Nim beginner here.
~How do I reproduce these warnings?~

nevermind, just got them by building via `make`.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/2737 got the three `ncli/inspector.nim` ones.
