### ISSUE TITLE
/eth/v1/beacon/states/{state_id}/validators does not return 400 on invalid state

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#2486]
Bug report for the ETH2.0 standard API.

A call to the `/eth/v1/beacon/states/{state_id}/validators` endpoint with an invalid state ID (_e.g._ 'invalid') returns a 404, however the spec states that it should return a 400.

This is against current unstable.

Note that this is appears to be the case for all endpoints that take a state_id, and all should return a 400 on invalid state.

**Comment by cheatfate** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/2494
