### ISSUE TITLE
/eth/v1/validator/duties/proposer/{epoch} does not return duties for current epoch

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#2487]
Bug report for the ETH2.0 standard API.

A call to the /eth/v1/validator/duties/proposer/{epoch} endpoint with the current epoch returns an error:

```
{
  "code": "400",
  "message": "Block header/data has not been found"
}
```

This is against current unstable.

The beacon chain is confirmed to be synced.

**Comment by cheatfate** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/2494
