### ISSUE TITLE
/eth/v1/validator/duties/proposer/0 returns duty for slot 0

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#2488]
Bug report for the ETH2.0 standard API.

A call to the /eth/v1/validator/duties/proposer/0 endpoint returns a duty for slot 0, which is invalid as slot 0 has no proposer.

This is against current unstable.

**Comment by cheatfate** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/2494
