### ISSUE TITLE
/eth/v1/debug/beacon/states/{state_id} justification_bits incorrect format

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#2489]
Bug report for the ETH2.0 standard API.

A call to the /eth/v1/debug/beacon/states/{state_id} endpoint returns `justification_bits` as an integer string; the spec requires this to be a hex string.

This is against current unstable.

**Comment by cheatfate** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/2494
