### ISSUE TITLE
/eth/v1/beacon/pool/attestations ignores slot query parameter

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#2490]
Bug report for the ETH2.0 standard API.

A call to the `/eth/v1/beacon/pool/attestations` endpoint with a `slot` query parameter does not filter returned values by the slot, instead returning all attestations with the pool regardless of slot value.

This is against current unstable.

**Comment by cheatfate** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/2494
