### ISSUE TITLE
REST API root path

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#2491]
The Ethereum 2 standard REST API presents at the '/api' path.  All other known implementations present at the '/' path; consider using the same path for standardisation between implementations.

**Comment by arnetheduck** [comment]
The API path here is suggested by the spec itself - is this difficult to handle on the client side? I imagine anything that consumes REST would use an URL as config parameter?

![Screenshot from 2021-04-13 08-59-56](https://user-images.githubusercontent.com/1382986/114510337-da536e80-9c36-11eb-98f4-58eaa7e773e3.png)

**Comment by mcdee** [comment]
Yes, the docs should probably be updated because everyone went with / rather than /api.

It isn't a problem in terms of handling the base URL, it's just a point for conformance.

**Comment by cheatfate** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/2494
