### ISSUE TITLE
Nimbus guide: how to set a backup web3 provider

### ISSUE THREAD

**Issue by unixpi** [status-im/nim-beacon-chain#2499]

**Comment by pepa65** [comment]
Did anything happen, or was the work done somewhere else?

**Comment by mratsim** [comment]
It happened in v1.1.0 https://github.com/status-im/nimbus-eth2/releases/tag/v1.1.0

"Support for fallback `--web3-url` providers."

And the book is up-to-date: https://nimbus.guide/web3-backup.html

**Comment by pepa65** [comment]
So it no longer asks you to enter one on the commandline if you don't set WEB3_URL in the environment?

**Comment by stefantalpalaru** [comment]
> So it no longer asks you to enter one on the commandline if you don't set WEB3_URL in the environment?

As long as you pas at least one `--web3-url=...` argument to the wrapper script, you won't be prompted any more.

**Comment by pepa65** [comment]
Great, because I no longer use(d) the wrapper script because of these kind of issues.

**Comment by arnetheduck** [comment]
The wrapper script is more of a configuration file than anything else, it's not needed _really_
