### ISSUE TITLE
Makefile:50: recipe for target 'testnet0' failed

### ISSUE THREAD

**Issue by Caamper** [status-im/nim-beacon-chain#250]
Hi,
I am runnig OS, 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
on a rasberry pi 3+

I have an issues trying to set up the testnet with command, make testnet0.

i get the, Makefile:50: recipe for target 'testnet0' failed
[error.txt](https://github.com/status-im/nim-beacon-chain/files/3083390/error.txt)

then if i try the command, build testnet0_node, i get a faild to cennect to boostrap node but it continues and leaves it at the, GossipSub Peer disconnected

**Comment by stefantalpalaru** [comment]
That Makefile recipe is no longer on line 50. Please go up 2 directories in the Nimbus repo and run `make update` there, then try again.

**Comment by Caamper** [comment]
[error2.txt](https://github.com/status-im/nim-beacon-chain/files/3084134/error2.txt)
i then get an error on makefile:170

**Comment by Caamper** [comment]
and when i run make testnet0 from /nimbus/vendor/nim-beacon-chain:

nim c -d:release --lineTrace:on -d:chronicles_log_level=DEBUG -d:SECONDS_PER_SLOT=30 -d:SHARD_COUNT=16 -d:SLOTS_PER_EPOCH=16 -d:DEFAULT_NETWORK=testnet0 --hints:off --verbosity:0 -o:build/testnet0_node beacon_chain/beacon_node
Failed to download key
Permission denied; Additional info: "/home/ubuntu/.cache/nimbus/BeaconNode/testnet0/validators"Makefile:53: recipe for target 'testnet0' failed
make: *** [testnet0] Error 1

**Comment by stefantalpalaru** [comment]
Did you happen to use `sudo` at any point in the past, thus creating a mix of files and directories as root, besides your regular user?

**Comment by Caamper** [comment]
dude I am the biggest noob….sorry for that. I did not make the commands in sudo.

![image](https://user-images.githubusercontent.com/49671831/56206802-8284cb80-604d-11e9-93c7-1cb197024d6c.png)


Thanks for the help but it was a bug in my knowlege in unix. I will try to Close this false repport
