### ISSUE TITLE
Web3url provider text

### ISSUE THREAD

**Issue by unixpi** [status-im/nim-beacon-chain#2500]
**Is your feature request related to a problem? Please describe.**
If you run the beacon node with a web3-url option , e.g. `./run-mainnet-beacon-node.sh --web3-url="wss://mainnet.infura.io/ws/v3/ae0e57122a1e49af8e835e82a5e35e60"`, you're still asked to provide a web3 url:

`Please enter a Web3 provider URL: `

I think this is confusing. My first impression was that the `--web3-url` option I had passed in had been ignored.

**Describe the solution you'd like**

`Please enter a Web3 provider URL (if you've already set one, feel free to leave this blank or enter a backup option):`

**Describe alternatives you've considered**
Perhaps we could even skip this step entirely if a `--web3-url` has been passed, or else just directly ask if they'd like to provide a backup option?

**Additional context**
None

**Comment by zah** [comment]
The merged PR above detects when `--web3-url` was provided on the command-line and avoids asking the user to enter it. If you use the `WEB3_URL` env variable, this still takes precedence and the provider URL is used as the default provider.

**Comment by pepa65** [comment]
Does that also work when specifying multiple URLs? What is the way to run that, set one URL in WEB3_URL and give the other one(s) after the commandline flag??

**Comment by zah** [comment]
To use multiple fallback providers, just keep adding additional `--web3-url` parameters on the command line. The client will try to use the primary provider (the first `--web3-url` value) until it fails. It will then cycle in round-robin fashion between all providers and keep using the ones that appear to function well.

Using the `WEB3_URL` env var is not strictly necessary anymore, but if you provide it, it will be used as your primary provider.
