### ISSUE TITLE
Apple Silicon M1 support?

### ISSUE THREAD

**Issue by Sajjon** [status-im/nim-beacon-chain#2534]
I would like to know if Nimbus supports Apple Silicon M1 chip?

**Comment by mratsim** [comment]
Not yet.

There is nothing that prevents Nimbus from supporting it, it's just a matter of testing and releasing pre-built binaries for it.

FYI, Nim supports Apple M1 since December through a trivial change (https://github.com/nim-lang/Nim/pull/16279/files).

**Comment by Sajjon** [comment]
@mratsim can I do anything to help? (I'm a coder, but never tried Nim, heard good stuff about it though.)

**Comment by arnetheduck** [comment]
Hey @Araq, are all M1 changes on the nim 1.2.x branch?

**Comment by Araq** [comment]
Yes, I have tested it myself, works on my M1.

**Comment by stefantalpalaru** [comment]
Please test the "macOS_arm64" binary release in here: https://github.com/status-im/nimbus-eth2/releases/tag/v1.3.0

**Comment by unixpi** [comment]
@Sajjon ^

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/2759 also resolves an aspect of this.
