### ISSUE TITLE
Fix REST API test in CI

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#2569]
**Describe the bug**
The REST API test sporadically fails in CI (and elsewhere).

**Screenshots**
https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fprs/detail/PR-2562/1/pipeline:
![2021-05-16-222143_797x668_scrot](https://user-images.githubusercontent.com/11422416/118411480-5a308680-b684-11eb-9be7-d4aa7152928c.png)
![2021-05-16-222656_797x444_scrot](https://user-images.githubusercontent.com/11422416/118411653-19853d00-b685-11eb-90e6-e0abbe93e915.png)

https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fprs/detail/PR-2565/1/pipeline/62:
![2021-05-16-222424_793x467_scrot](https://user-images.githubusercontent.com/11422416/118411607-daef8280-b684-11eb-9b3f-ece58f3745ae.png)
![2021-05-16-222549_797x279_scrot](https://user-images.githubusercontent.com/11422416/118411617-eb9ff880-b684-11eb-99cf-87158dc0cd16.png)

**Comment by cheatfate** [comment]
From what i see at https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fprs/detail/PR-2565/1/pipeline/62
there is last message that beacon_node failed to start discovery service. It means that there one more `beacon_node` running already.

**Comment by tersec** [comment]
Since, apparently, the Jenkins CI nodes are sometimes running multiple tests at a time, is that incompatible with the REST API tests as written?

**Comment by tersec** [comment]
Another example of multiple beacon nodes is https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fprs/detail/PR-2687/1/pipeline/62:
![2021-06-29-174008_779x133_scrot](https://user-images.githubusercontent.com/11422416/123827608-4bc6c300-d8f0-11eb-8f5e-510d311c17af.png)

**Comment by tersec** [comment]
In https://github.com/status-im/nimbus-eth2/pull/2673 reducing an apparently innocuous/arbitrary big round number of 10,000 to either 1,000 or 2,000 seems to reliably induce CI failures:
```
nimbus_beacon_node has been successfully started
Ethereum2 REST API Tester, Version 0.0.1 [linux: amd64]
Copyright(C) 2021 Status Research & Development GmbH
NOT 2021-06-29 12:04:44.937+00:00 Rules file loaded                          tid=2793930 file=resttest.nim:280 total_rules_count=282 rules_count=279
NOT 2021-06-29 12:04:44.937+00:00 Waiting for initial connection attempt     tid=2793930 file=resttest.nim:1105 time=30
NOT 2021-06-29 12:05:14.966+00:00 Exploring remote server hostname           tid=2793930 file=resttest.nim:1112 hostname=127.0.0.1:5052
NOT 2021-06-29 12:05:14.966+00:00 Connection with remote host established    tid=2793930 file=resttest.nim:347 host=127.0.0.1:5052
DBG 2021-06-29 12:05:14.967+00:00 Test worker has been started               tid=2793930 file=resttest.nim:967 worker=0
DBG 2021-06-29 12:05:14.967+00:00 Test worker has been started               tid=2793930 file=resttest.nim:967 worker=1
DBG 2021-06-29 12:05:14.967+00:00 Test worker has been started               tid=2793930 file=resttest.nim:967 worker=2
DBG 2021-06-29 12:05:14.967+00:00 Test worker has been started               tid=2793930 file=resttest.nim:967 worker=3
DBG 2021-06-29 12:05:14.967+00:00 Opened new connection with remote host     tid=2793930 file=resttest.nim:974 address=127.0.0.1:5052 worker=0
DBG 2021-06-29 12:05:14.967+00:00 Running test                               tid=2793930 file=resttest.nim:832 name=/eth/v1/beacon/genesis test_index=0 worker_index=0
DBG 2021-06-29 12:05:14.967+00:00 Opened new connection with remote host     tid=2793930 file=resttest.nim:974 address=127.0.0.1:5052 worker=1
DBG 2021-06-29 12:05:14.967+00:00 Running test                               tid=2793930 file=resttest.nim:832 name=/eth/v1/beacon/states/head/root test_index=1 worker_index=1
DBG 2021-06-29 12:05:14.968+00:00 Opened new connection with remote host     tid=2793930 file=resttest.nim:974 address=127.0.0.1:5052 worker=2
DBG 2021-06-29 12:05:14.968+00:00 Running test                               tid=2793930 file=resttest.nim:832 name=/eth/v1/beacon/states/genesis/root test_index=2 worker_index=2
DBG 2021-06-29 12:05:14.968+00:00 Opened new connection with remote host     tid=2793930 file=resttest.nim:974 address=127.0.0.1:5052 worker=3
DBG 2021-06-29 12:05:14.968+00:00 Running test                               tid=2793930 file=resttest.nim:832 name=/eth/v1/beacon/states/finalized/root test_index=3 worker_index=3
DBG 2021-06-29 12:05:14.968+00:00 Request sent                               tid=2793930 file=resttest.nim:879 name=/eth/v1/beacon/genesis elapsed=429us155ns test_index=0 worker_index=0
DBG 2021-06-29 12:05:14.968+00:00 Request sent                               tid=2793930 file=resttest.nim:879 name=/eth/v1/beacon/states/head/root elapsed=378us919ns test_index=1 worker_index=1
DBG 2021-06-29 12:05:14.968+00:00 Request sent                               tid=2793930 file=resttest.nim:879 name=/eth/v1/beacon/states/genesis/root elapsed=298us676ns test_index=2 worker_index=2
DBG 2021-06-29 12:05:14.968+00:00 Request sent                               tid=2793930 file=resttest.nim:879 name=/eth/v1/beacon/states/finalized/root elapsed=257us335ns test_index=3 worker_index=3
Sending interrupt signal to process
Terminated
tests/simulation/restapi.sh: line 131: kill: (2793928) - No such process
Some of the tests failed!
```
Where the explicit interrupts/terminations/failure only occurred after it was externally stopped. It ran for hours otherwise.

**Comment by cheatfate** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/2688

**Comment by tersec** [comment]
Does this resolve the separate issue in https://github.com/status-im/nimbus-eth2/issues/2569#issuecomment-870712035 (hanging on some REST API queries) too?

**Comment by tersec** [comment]
Nope. https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fprs/detail/PR-2690/1/pipeline/77 shows:
![2021-07-01-141141_1498x96_scrot](https://user-images.githubusercontent.com/11422416/124122356-869e3780-da65-11eb-993d-a9d5076c74d0.png)

**Comment by tersec** [comment]
I'd note that PR changes only comments.

**Comment by tersec** [comment]
Seems not to start at all, or at least be unavailable for connections (https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fmultibranch/detail/unstable/422/pipeline/76):
![2021-07-02-214537_738x462_scrot](https://user-images.githubusercontent.com/11422416/124321959-1929fe00-db6e-11eb-8867-b52884ee84ab.png)

**Comment by tersec** [comment]
https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fmultibranch/detail/PR-2716/1/pipeline:
![2021-07-13-111815_881x937_scrot](https://user-images.githubusercontent.com/11422416/125426370-f066319a-cba3-441d-8dcc-c2e27e4a3391.png)

**Comment by tersec** [comment]
There probably are additional failure modes left, but it's mostly reliable now.
