### ISSUE TITLE
Lower minimum required libc version for binaries

### ISSUE THREAD

**Issue by bauerj** [status-im/nim-beacon-chain#2583]
**Is your feature request related to a problem? Please describe.**
Currently, on my Raspberry Pi I have to compile nimbus-eth2 myself since the binaries don't work with the latest Raspbian version. The system ships glibc version 2.28-10 while the latest nimbus-eth2 binary has a minimum constraint of 2.29.

Since compiling takes a lot of time (about 15 minutes) it would be nice if the precompiled binaries could be used instead.

**Describe the solution you'd like**
If the binaries would be compiled against an older version of libc, they would probably work just fine.

**Describe alternatives you've considered**
Of course I could switch to e.g. Ubuntu but since most Raspberry Pi users will run Raspbian, a solution for Raspbian would be preferred.

**Comment by bauerj** [comment]
I guess simply changing https://github.com/status-im/nimbus-eth2/blob/stable/docker/dist/base_image/Dockerfile.arm64#L9 to `FROM ubuntu:18.04` and then uploading a new base-image would work.

**Comment by stefantalpalaru** [comment]
Done.
