### ISSUE TITLE
Keep getting "Current slot older than attestation pool view, clock reset?"

### ISSUE THREAD

**Issue by uvizhe** [status-im/nim-beacon-chain#2595]
I'm continuously getting the error *"Current slot older than attestation pool view, clock reset?"*

I just synced up with _Prater_ and noticed the error in logs. After setting up chrony I expected to get rid of it but the error persists.
I run Nimbus v1.3.0 on x86_64 with Ubuntu Server 20.04 LTS.

Chrony output:
```$ chronyc tracking 
Reference ID    : 25E48102 (37.228.129.2)
Stratum         : 3
Ref time (UTC)  : Mon May 24 09:54:32 2021
System time     : 0.001164366 seconds fast of NTP time
Last offset     : +0.001360056 seconds
RMS offset      : 0.001915362 seconds
Frequency       : 85.022 ppm slow
Residual freq   : +0.023 ppm
Skew            : 1.928 ppm
Root delay      : 0.032912757 seconds
Root dispersion : 0.010096268 seconds
Update interval : 2060.9 seconds
Leap status     : Normal
```

And here is (rather short) Nimbus log: https://gist.githubusercontent.com/uvizhe/a4cbcf4c2f3e774105757b25d87b05fe/raw/dd60e21fdaf6f80835f9f2c0696c8dc2048f9e1c/gistfile1.txt

**Comment by arnetheduck** [comment]
@mratsim 

This is likely because with batched attestations, `wallSlot` is reordered sometimes - we take the a `wallSlot` snapshot before the `await` and use it after
