### ISSUE TITLE
Option to force syncing Eth1

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#2685]
When migrating validators we prepare a node by syncing Eth2. However Nimbus only sync Eth1 when a validator is attached.

To avoid additional delay and miss a block proposal on migration we probably want a `--force-sync-eth1` flag to enforce Eth1 syncing even with no validators.

**Comment by arnetheduck** [comment]
actually, the simpler option here might be to simply always sync eth1 when an eth1 address is specified, avoiding the extra option - it's cheap enough

**Comment by zah** [comment]
This is already present with the parameter `--web3-mode=enabled` (the default value is `auto` which means "enable when validators are attached"). Right now, this is considered a hidden parameter, but exposing it would be a one-line change.

**Comment by arnetheduck** [comment]
> This is already present with the parameter --web3-mode=enabled (the default value is auto which means "enable when validators are attached"). Right now, this is considered a hidden parameter, but exposing it would be a one-line change.

Do we really need an option for it though? We're already expressing the desire to use web3 by feeding in a web3-url or not, having one more option just creates more invalid states that the application can be in.
