### ISSUE TITLE
[RFC] ETH2 constants, presets and custom chain configuration

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#270]
From #269

## Open design questions

Do we want to support:
- compile-time only presets (as it's done today)
    with presets known at compile-time (for example testing "mainnet" and "minimal")
- multiple presets within a single binary without recompilation
    with presets known at application start-time (for example for testnets)
- custom presets with a custom configuration file support
- a mix of all 3

Importantly `DEPOSIT_CONTRACT_TREE_DEPTH`, `SHARD_COUNT`, `SLOTS_PER_HISTORICAL_ROOT`,  `LATEST_ACTIVE_INDEX_ROOTS_LENGTH`, `LATEST_SLASHED_EXIT_LENGTH` are used as the size of arrays datatypes and changing those to runtime values would have a large design and performance impact.

If we want application start-time presets or runtime-configuration, we would need to introduce a config object as proposed here: https://github.com/status-im/nim-beacon-chain/blob/8da71715eb7951bca996162d3b8407792b970934/beacon_chain/spec/datatypes.nim#L41-L42

At a user-level those questions translate to how flexible do we want to be?
  - In the current solution they only have to provide a compile-time switch?
  - Do we want a start-time preset switch?
  - Do we want a start-time configuration file from [confutils](https://github.com/status-im/nim-confutils)?
  - A mix of the previous 3?

**Comment by Swader** [comment]
Hardcoded default to mainnet, and config file support. Anything else is too much, a config file is just enough customization

**Comment by Swader** [comment]
Having to recompile for a testnet is a DX nightmare. IMO we must support runtime config in one way or another. I understand the trickiness about fixed size arrays, but the extra work would be worth it. We'd lose out on a lot of users (think devs!) if we made them recompile just for different settings.

Let's vote? Use emoji votes.

- 👍 In the current solution they only have to provide a compile-time switch?
- 🎉 Do we want a start-time preset switch?
- ❤ Do we want a start-time configuration file from confutils?
- 🚀 A mix of the previous 3?

**Comment by arnetheduck** [comment]
#1274 mostly establishes the new balance here
