### ISSUE TITLE
Ability to send validators and secrets to the node via RPC

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#2701]
What I think would be cool, is if the validators and secrets could be provided to an already started node via JSON RPC.

This would allow user to never store validators and their keys on a vps storage and always have to provide it explicitly via RPC call, most probably over an SSH tunnel, and SSL for RPC wouldn't hurt either. This way keys would only be held in memory while the process runs.

This would allow for storing of the validators offline most of the time, and could even allow for making an automated setup using something like an [RPi Zero](https://www.raspberrypi.org/products/raspberry-pi-zero/) to have a device with validators that is offline most of the time, but when necessary is powered on and connects to the host via SSH(probably also over VPN) and calls a dedicated binary/script to provide the validators into the already running node.

**Comment by zah** [comment]
This is now possible through the use of the [Keymanager API](https://nimbus.guide/keymanager-api.html)
