### ISSUE TITLE
REST parser too strict on json with extra fields

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#2751]
Generally, in json it is customary that extra fields can be added to a response as a backwards-compatible change that doesn't require a new version - in order to be future-proof against such additions, the rest client should not raise an error in such cases.

**Comment by cheatfate** [comment]
@zah this is not enough to fix the issue, because there is a lot of procedures which performs deserialization manually via `readObjectFields(reader)`.

**Comment by cheatfate** [comment]
And there also one more reason to keep parser strict. There is no specification on how to treat duplicate field values.

**Comment by zah** [comment]
This was fixed in https://github.com/status-im/nimbus-eth2/pull/3647
