### ISSUE TITLE
Detect clang on M1 build scenario and disable -march=native

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#2758]
clang doesn't support `-march=native` on ARM platforms, including Apple's M1.

https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1
https://github.com/DMOJ/judge-server/issues/303
https://developer.apple.com/forums/thread/672654
https://github.com/microsoft/mimalloc/issues/340

**Comment by stefantalpalaru** [comment]
Done.
