### ISSUE TITLE
Wrong weak-subjectivity-checkpoint parsing

### ISSUE THREAD

**Issue by NetherStar64** [status-im/nim-beacon-chain#2776]
**Describe the bug**
When using --weak-subjectivity-checkpoint, the argument is parsed wrongly:
    blockroot:epoch
the epoch is treated as ":epoch" (so with the colon)

**To Reproduce**
1. Platform details (OS, architecture): Windows 10
2. Branch/commit used: stable
3. Commands being executed: `./run-prater-beacon-node.sh --web3-url=(infura) --weak-subjectivity-checkpoint="0x3c1e98bf132530c669723f58aa3d395be0d0bfaa653152eecb04605`
e203bfeb5:31714"
4. Relevant log lines:
 `Error while processing the weak-subjectivity-checkpoint=0x3c1e98bf132530c669723f58aa3d395be0d0bfaa653152eecb04605e203bfeb5:31714 parameter: invalid unsigned integer: :31714`

Maybe related to #2530

**Comment by zah** [comment]
A fix for this has been merged in the `unstable` branch and will be shipped in Nimbus v22.6.0
