### ISSUE TITLE
Nimbus is single-core, make multi-core

### ISSUE THREAD

**Issue by paulmillr** [status-im/nim-beacon-chain#2778]
**Describe the bug**
Testing Nimbus right now and it seems to utilize only one core while syncing the testnet. Is this a known issue? Is this on-purpose? Even RPI4 has 4 cores nowadays, so unsure if it's optimal.

**To Reproduce**
1. Platform details (OS, architecture): Linux, x86
2. Branch/commit used: 1.4.2

**Comment by tersec** [comment]
It's on purpose.

https://github.com/status-im/nimbus-eth2/pull/2718 does address one aspect of this.

**Comment by mratsim** [comment]
For syncing, multiple cores is expected to not be as efficient as weak subjectivity sync / snapshot sync which would download a snapshot of one of the latest finalized blockchain state from a somewhat trusted source and then would backfill the missing blocks. The main advantage being that we can verify blocks without running the chain state transition function by just using the hashes.

Teku/Infura currently can "sync" in less than 10mins (as in be ready for validation) when the source is fully trusted.

Hence our plan to improve syncing speed is to first implement weak subjectivity sync and then parallelize block verification of it.

**Comment by paulmillr** [comment]
Regarding snap sync. If I understand correctly, Geth implemented snapshot sync that does not require nodes to be fully trusted. They seem to use cryptography to check validity of the data: https://blog.ethereum.org/2021/03/03/geth-v1-10-0/

If you're implementing it right now, does it make sense to think of this also?

**Comment by TennisBowling** [comment]
you can use `--num-threads` to parallelize *some* parts of nimbus.

**Comment by arnetheduck** [comment]
#2718 implements multi-core support - trused node sync added to 1.7.0 which completes this arc
