### ISSUE TITLE
review test_ssz_merkleization

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#2789]
#2785 removes a seemingly obsolete test - it no longer compiles and the parts that do compile no longer pass - a final review of this removal should be done at some point.

Latest version before removal: https://github.com/status-im/nimbus-eth2/blob/6e46445da2c17080817800568f7a390000923978/tests/test_ssz_merkleization.nim

**Comment by mratsim** [comment]
So the datatypes introduced are those from merkle_minimal https://github.com/ethereum/eth2.0-specs/blob/v1.1.0-beta.2/tests/core/pyspec/eth2spec/utils/merkle_minimal.py

https://github.com/status-im/nimbus-eth2/blob/6e46445da2c17080817800568f7a390000923978/tests/test_ssz_merkleization.nim#L10-L78

The testMerkleMinimal is property-based testing that MerkleMinimal should pass https://github.com/status-im/nimbus-eth2/blob/6e46445da2c17080817800568f7a390000923978/tests/test_ssz_merkleization.nim#L80-L157 (upstream https://github.com/ethereum/eth2.0-specs/blob/1235e58a8db09efd058f31087d53d91b97b83011/tests/core/pyspec/eth2spec/utils/test_merkle_minimal.py)

Then everything below L157 is I suppose using this merkle minimal implementation as a reference to generate test cases for the full blown implementation.

https://github.com/status-im/nimbus-eth2/blob/6e46445da2c17080817800568f7a390000923978/tests/test_ssz_merkleization.nim#L159-L269

The merkle_minimal code should still compile and be used as a reference test vector generator to supplement the EF tests.

There was some merkle proofs fixes related to sync committees in December it seems though https://github.com/ethereum/eth2.0-specs/commit/d01a4ad82374dbfbabf047315536f90fe90bf928

Note:

Iirc at one point that code was used to mock deposits generation completely independently from production code https://github.com/status-im/nimbus-eth2/blob/1e958cfb0a15122206773cb815fd3c58b8e98158/tests/mocking/mock_deposits.nim#L126, but it seems like it got replaced by production code https://github.com/status-im/nimbus-eth2/blob/1e958cfb0a15122206773cb815fd3c58b8e98158/beacon_chain/eth1/merkle_minimal.nim
