### ISSUE TITLE
Eth1 fallback: recheck if fallback comes back online

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#2806]
From TennisBowling

> so currently when having backup web3 providers if the primary goes down it will switch to the fallback permanently, I would prefer it to every slot check if the prefered is up, then if it is usable, switch back to it

This is quite useful for local Geth or Erigon updates otherwise nodes might inadvertantly all depends on Infura.

In terms of check, I'm unsure about the frequency (every slot? every epoch?).

**Comment by TennisBowling** [comment]
We should _at least_ check every slot, otherwise we may have problems if we check and switch during a slot, but every slot seems a bit excessive, granted, these are very light calls, but I say every 2 slots.

**Comment by TennisBowling** [comment]
#3354 
close this

**Comment by tersec** [comment]
Indeed.
