### ISSUE TITLE
fatal error, network mismatch

### ISSUE THREAD

**Issue by 3cl1ps** [status-im/nim-beacon-chain#2815]
got this error when starting nimbus : 

FAT 2021-08-25 10:02:11.165+00:00 The specified web3 provider serves data for a different network topics="eth1" tid=16797 file=eth1_monitor.nim:1063 expectedNetwork=5 providerNetwork=1

1. Platform details (OS, architecture): nanopct4, arm
2. Branch/commit used: geth 1.10.8 & nimbus 1.4.2
3. Commands being executed: 
geth --ws --datadir /ethereum --cache 1024 --maxpeers 30
nimbus_beacon_node --network=mainnet --data-dir=/var/lib/nimbus --web3-url=ws://127.0.0.1:8546 --nat=extip:${ClientIP} --log-level=INFO

fyi, i've been following this guide : 
https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-nimbus-e86bdee8c550

**Comment by arnetheduck** [comment]
Can you print the output of `build/nimbus_beacon_node --version`? This appears to be an issue in `unstable` but it should not be present in the released 1.4.2 version - it could happen if you download a pre-release version from the releases page.

**Comment by arnetheduck** [comment]
https://github.com/status-im/nimbus-eth2/pull/2819 fixes the issue in the pre-releases.

**Comment by 3cl1ps** [comment]
thx, waiting next nightly build to try it

**Comment by 3cl1ps** [comment]
fixed on Nimbus beacon node v1.4.2-fb42a3-stateofus
