### ISSUE TITLE
add more metrics to Grafana

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nim-beacon-chain#2820]
Jacek, on Discord:

---

that said, there are a few metrics I'd like to see on the dashboards:
* these agent metrics: https://github.com/status-im/nim-libp2p#use-identify-metrics - these are needed to see if we have problems staying connected to a particular client type (for example @Tanguy discovered an issue with teku the other day)
* bandwidth metrics: https://github.com/status-im/nim-libp2p/pull/607
* gossip metrics: https://github.com/status-im/nimbus-eth2/blob/unstable/beacon_chain/networking/eth2_network.nim#L266

if you can help make them appear on the grafana's , that 'd be excellent

**Comment by arnetheduck** [comment]
done, all metrics are present
