### ISSUE TITLE
bad sync performance

### ISSUE THREAD

**Issue by 3cl1ps** [status-im/nim-beacon-chain#2833]
hi, i think i have bad synchronization performance.
geth is alraedy synchronized so i'm just syncing the beacon chain.

`Aug 29 09:02:23 nanopct4 bash[2048]: INF 2021-08-29 09:02:23.187+00:00 Slot start                                 topics="beacnde" tid=2048 file=nimbus_beacon_node.nim:1060 lastSlot=1950309 wallSlot=1950
310 delay=180ms525us710ns peers=3 head=1aca43f5:742446 headEpoch=23201 finalized=23c5dcc1:742368 finalizedEpoch=23199 sync="wwPPwwPwww:3:0.2770:1.8193:07d16h25m (742432)" 
Aug 29 09:02:23 nanopct4 bash[2048]: NOT 2021-08-29 09:02:23.254+00:00 Syncing in progress; skipping validator duties for now topics="beacval" tid=2048 file=validator_duties.nim:622 slot=1950310 headSlot
=742446 
Aug 29 09:02:30 nanopct4 bash[2048]: INF 2021-08-29 09:02:30.510+00:00 Slot end                                   topics="beacnde" tid=2048 file=nimbus_beacon_node.nim:1003 slot=1950310 nextSlot=1950311 
head=1aca43f5:742446 headEpoch=23201 finalizedHead=23c5dcc1:742368 finalizedEpoch=23199 nextAttestationSlot=-1 nextProposalSlot=-1 nextActionWait=n/a`

1. Platform details (OS, architecture): nanopc t4 (Rockchip RK3399) with nvme, Ubuntu 20.04.3 LTS

2. Branch/commit used: Nimbus beacon node v1.4.2-fb42a3-stateofus

starting param :
/usr/bin/geth --ws --datadir /ethereum --cache 1024 --maxpeers 30
/usr/local/bin/nimbus_beacon_node --network=mainnet --data-dir=/var/lib/nimbus --web3-url=ws://127.0.0.1:8546 --nat=extip:$ip --log-level=INFO --log-file=/var/lib/nimbus/beacon_node.log

is the board powerfull enough ?
Load average: 7.27 7.22 6.60

**Comment by TennisBowling** [comment]
It looks like your cpu is not very powerful. it seems it has 6 cores, and your cpu is overloaded (since your load is above 7)
it also looks like you only have three peers, which is really low. make sure port 9000 tcp/udp is open to the internet you should pass `--enr-auto-update` to help with this.

you can try using checkpoint sync to start validating immediately, https://nimbus.guide/trusted-node-sync.html
but you'll have to use a version of nimbus off the `unstable` branch.

**Comment by arnetheduck** [comment]
Trusted node sync has been released in 1.7.0, along with several sync-related optimizations - the board looks like it's on the slower end, and the way to verify that it will give decent mainnet performance is to first run a validator on [prater](https://nimbus.guide/prater.html) - syncing is the first part of the journey, but once synced, the node will need to handle typical validator load as well - if the "delay" message in "Start slot" starts creeping up after sync has finished, the board is likely too slow.
