### ISSUE TITLE
[Altair] Syncing from checkpoint state doesn't work anymore

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#2843]
>Hey, I know this is still a experimental feature, but I noticed that after the prater Altair fork syncing from a checkpoint state doesn't work anymore and fails with file=nimbus_beacon_node.nim:124 err="Serialisation error while processing state.ssz"
>
>I'm getting the states with
>```
>curl -H 'Accept: application/octet-stream' https://InfuraSecret@eth2-beacon-prater.infura.io/eth/v2/debug/beacon/states/finalized -o state.ssz
>
>curl -H 'Accept: application/octet-stream' https://InfuraSecret@eth2-beacon-prater.infura.io/eth/v2/beacon/blocks/finalized -o block.ssz
>```

https://discord.com/channels/613988663034118151/771033358363918347/883022453830459483

**Comment by NetherStar64** [comment]
Also syncing with a state from before the Altair fork works.

**Comment by viksesh** [comment]
Any word on when checkpoint sync will be available for Nimbus?

**Comment by TennisBowling** [comment]
This should be closed. Checkpoint sync has been merged in `unstable`
#3209 #3263

**Comment by zah** [comment]
Indeed, @TennisBowling, thanks for spotting this.
