### ISSUE TITLE
Not finding peers / Failed to bond with bootstrap nodes

### ISSUE THREAD

**Issue by konsiv** [status-im/nim-beacon-chain#288]
[Related to this issue](https://github.com/status-im/nim-beacon-chain/issues/251) but I can't reopen.

make update
cd vendor/nim-beacon-chain
make testnet0
./build/testnet0_node

Ubuntu:

DBG 2019-06-16 08:15:16-07:00 UPnP                                       topics="nat" tid=3936 msg="Internet Gateway Device found but it's not connected. Trying anyway."
ERR 2019-06-16 08:15:16-07:00 UPnP port mapping                          topics="nat" tid=3936 msg=ConflictInMappingEntry
INF 2019-06-16 08:15:16-07:00 Connecting to bootstrap nodes              tid=3936 bootstrapNodes=@[enode://e7b5e57da97b753bcb8a3dbb46f66e7b8ef53bcc700451a5835406cbe758be6377f02e9bffbc65f870842f5cbac6ada45d41c610341ee0bcb122f77601f2d806@188.166.38.238:9000]
INF 2019-06-16 08:15:16-07:00 RLPx listener up                           tid=3936 self=enode://bc9dbda33268e1968f5e8d6d62df0847d218f82527e2a41be990fce073a7a2f32b3beb79ce41619669ce948df40d352cbd4153efd3ecb8737b333cc9e870b997@10.64.108.10:9000
DBG 2019-06-16 08:15:21-07:00 Looking for peers                          topics="discovery" tid=3936 present=6 requested=10
DBG 2019-06-16 08:17:32-07:00 Looking for peers                          topics="discovery" tid=3936 present=6 requested=10
DBG 2019-06-16 08:17:33-07:00 Bonding failed, already waiting for pong   topics="discovery" tid=3936 n=Node[188.166.38.238:1088]
DBG 2019-06-16 08:19:45-07:00 Looking for peers                          topics="discovery" tid=3936 present=6 requested=10
DBG 2019-06-16 08:21:59-07:00 Looking for peers                          topics="discovery" tid=3936 present=6 requested=10
(every few minutes)

Windows:

DBG 2019-06-16 18:29:25+03:00 UPnP                                       topics="nat" tid=8948 msg="Internet Gateway Device found but it's not connected. Trying anyway."
DBG 2019-06-16 18:29:25+03:00 UPnP: added port mapping                   topics="nat" tid=8948 externalPort=9000 internalPort=9000 protocol=TCP
DBG 2019-06-16 18:29:25+03:00 UPnP: added port mapping                   topics="nat" tid=8948 externalPort=9000 internalPort=9000 protocol=UDP
INF 2019-06-16 18:29:25+03:00 Connecting to bootstrap nodes              tid=8948 bootstrapNodes=@[enode://e7b5e57da97b753bcb8a3dbb46f66e7b8ef53bcc700451a5835406cbe758be6377f02e9bffbc65f870842f5cbac6ada45d41c610341ee0bcb122f77601f2d806@188.166.38.238:9000]
INF 2019-06-16 18:29:25+03:00 RLPx listener up                           tid=8948 self=enode://a6ba1eb0101374b107e25aa29703c5b020a78c5ca4397add7c983898f3fcf44acaec9895c81fe1973806c2b42a09816a378b956e4521aa0b55619fe48864fb7a@10.64.108.10:9000
INF 2019-06-16 18:29:26+03:00 Failed to bond with bootstrap nodes, retrying topics="discovery" tid=8948
INF 2019-06-16 18:29:27+03:00 Failed to bond with bootstrap nodes, retrying topics="discovery" tid=8948
(every 1-15 seconds)

**Comment by Swader** [comment]
Hi,

this should no longer be happening. Confirm please?

**Comment by tersec** [comment]
The testnet0 referenced here is not being supported much longer.
