### ISSUE TITLE
Support remote signer EIP-3030

### ISSUE THREAD

**Issue by dapplion** [status-im/nim-beacon-chain#2948]
Implementing [EIP-3030](https://eips.ethereum.org/EIPS/eip-3030) would allow Nimbus to connect to a [Web3Signer](https://consensys.github.io/web3signer/web3signer-eth2.html) remote signer to obtain signatures. 

This is very relevant in the effort to support non-technical solo stakers that require a UI to operate. Since implementor teams have very limited bandwidth attaching a UI to an external remote signer is the shortest path to a universal keymanager API for all client. Please check this issue for a readiness analysis of other potential solutions https://github.com/dappnode/DAppNode/issues/329.

A remote signer also allows both solo stakers and staking pools to safely switch between clients safely with zero downtime. It also abstracts managing the slashing protection data since it's computed and stored inside the remote signer.

The standard is currently adopted by Teku and Lighthouse, Prysm and Lodestar pending. The Web3Signer linked above developed by Teku has been stress tested in production for long and is usable immediately. To support the UI the Web3Signer should be extended to include some basic routes potentially adhering to https://github.com/ethereum/beacon-APIs/pull/151, and there's already potential funding available to make it happen.

I highly encourage the Nimbus team to consider this feature's priority since it can be very beneficial for both Nimbus adoption and the health of the network as a whole.

**Comment by james-prysm** [comment]
can confirm, team is working on this and starting designs, implementation should be in a flag for execution

**Comment by tersec** [comment]
Web3Signer support has been implemented and documented by https://github.com/status-im/nimbus-eth2/pull/3077 https://github.com/status-im/nimbus-eth2/pull/3640 https://github.com/status-im/nimbus-eth2/pull/4912 among other PRs.

This has become an interoperable approach of a remote signer, also adopted by other clients in the ecosystem.
