### ISSUE TITLE
Add Nimbus version in the bottom status bar 

### ISSUE THREAD

**Issue by Maigre** [status-im/nim-beacon-chain#2959]
Title is pretty explicit,
it would be very handful to see the current Nimbus version in the bottom status bar :)
Best,

**Comment by zah** [comment]
This was implemented in https://github.com/status-im/nimbus-eth2/pull/3747

The desired result can be achieved by adding `$version` or `$full_version` to the `--status-bar-contents` command-line or config-file parameter.

Here is an example:

```bash
nimbus_beacon_node --status-bar-contents="version: $version; peers: $connected_peers; finalized: $finalized_root:$finalized_epoch; head: $head_root:$head_epoch:$head_epoch_slot; time: $epoch:$epoch_slot ($slot); sync: $sync_status | ETH: $attached_validators_balance"
```

Using `$version` will result in a short version value such as  `22.5.0`. `$full_version` provides a more detailed value such as `v1.7.0-5b13b7-stateofus`.

The new functionality will be shipped in Nimbus 22.6.0.
