### ISSUE TITLE
Beacon node on MacOS fails to handle metrics and API queries

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#2984]
**Describe the bug**
Beacon node deployed on MacOS in https://github.com/status-im/infra-nimbus/issues/60 starts off fine, but after several hours of running it starts timing out and rejecting requests to REST, RPC, and metrics APIs. This manifests in various ways, for example:
```
Get "http://10.14.0.30:9200/metrics": read tcp 172.17.2.2:59530->10.14.0.30:9200: read: connection reset by peer
```
```
Get "http://10.14.0.30:9201/metrics": EOF
```

**To Reproduce**

Platform: Darwin 20.6.0, Mac mini G5A, M1, 8GB (`arm64`)
Branch: `stable`, `testing`, `unstable`
Command: [See Ansible role](https://github.com/status-im/infra-role-beacon-node-macos/blob/master/templates/launchd.plist.j2)
Host: [`macos-01.ms-eu-dublin.nimbus.prater`](https://consul.infra.status.im/ui/he-eu-hel1/nodes/macos-01.ms-eu-dublin.nimbus.prater/service-instances)

**Screenshots**
As it can be seen the problems start ~6 hours after process starts:

![image](https://user-images.githubusercontent.com/2212681/137094583-7c668163-6595-4d1f-a80d-1f3a87611213.png)

**Additional context**
This unstability can be also seen with RPC and API endpoints. Which is why I [disabled Consul healthchecks](https://github.com/status-im/infra-role-beacon-node-macos/commit/d4d08f06). They were flapping far too much to be useful.

I thought this might be related to memory, so I've deployed Netdata to the host and the metrics are available [here](https://grafana.infra.status.im/d/QCTZ8-Vmk/single-host-dashboard?var-host=macos-01.ms-eu-dublin.nimbus.prater).

As far as I can tell there is no clear indication that memory reached some kind of limit around 21:26:00 when the first gap in metrics appears, but then again I'm not entirely sure what all these memory states mean exactly:

![image](https://user-images.githubusercontent.com/2212681/137095239-e0fd8c60-38f5-4b79-af0e-8cec8868d493.png)

**Comment by jakubgs** [comment]
The API endpoint also fails in various ways:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % curl -sS localhost:9300/eth/v1/node/health
curl: (56) Recv failure: Connection reset by peer
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % curl -sS localhost:9300/eth/v1/node/health
curl: (52) Empty reply from server
```

**Comment by jakubgs** [comment]
As suggested by @cheatfate this might be related to limit of file descriptors.

But if I look up one of the processes with `lsof` I don't see a huge number of files/sockets open:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo lsof -p 130                          
COMMAND   PID   USER   FD     TYPE             DEVICE    SIZE/OFF                NODE NAME
nimbus_be 130 nimbus  cwd      DIR               1,17         224              891773 /Users/nimbus/beacon-node-prater-stable
nimbus_be 130 nimbus  txt      REG               1,17    79108399             1126194 /Users/nimbus/beacon-node-prater-stable/repo/build/nimbus_beacon_node
nimbus_be 130 nimbus  txt      REG               1,17       32768             1222303 /Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/db/nbc.sqlite3-shm
nimbus_be 130 nimbus  txt      REG               1,17     2547856 1152921500312767016 /usr/lib/dyld
nimbus_be 130 nimbus  txt      REG               1,17       32768             1222361 /Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/validators/slashing_protection.sqlite3-shm
nimbus_be 130 nimbus    0r     CHR                3,2         0t0                 338 /dev/null
nimbus_be 130 nimbus    1u     REG               1,17   158178248              939907 /Users/nimbus/beacon-node-prater-stable/logs/service.log
nimbus_be 130 nimbus    2u     REG               1,17   158178248              939907 /Users/nimbus/beacon-node-prater-stable/logs/service.log
nimbus_be 130 nimbus    3u    IPv4 0xab8a0fd6c96964cb         0t0                 TCP *:wap-wsp (LISTEN)
nimbus_be 130 nimbus    4u  KQUEUE                                                    count=0, state=0xa
nimbus_be 130 nimbus    5u    IPv4 0xab8a0fd6c9693253         0t0                 TCP *:* (CLOSED)
nimbus_be 130 nimbus    6u     REG               1,17 24836358144              939911 /Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/db/nbc.sqlite3
nimbus_be 130 nimbus    7u     REG               1,17     5281872             1222302 /Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/db/nbc.sqlite3-wal
nimbus_be 130 nimbus    8u     REG               1,17       32768             1222303 /Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/db/nbc.sqlite3-shm
nimbus_be 130 nimbus    9u  KQUEUE                                                    count=1, state=0x8
nimbus_be 130 nimbus   10u    IPv4 0xab8a0fd6cc1d109b         0t0                 TCP *:* (CLOSED)
nimbus_be 130 nimbus   11u    IPv4 0xab8a0fd6cc380683         0t0                 TCP localhost:iua (LISTEN)
nimbus_be 130 nimbus   12u    IPv4 0xab8a0fd6cc38109b         0t0                 TCP localhost:vrace (LISTEN)
nimbus_be 130 nimbus   13u     REG               1,17       32768              939959 /Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/validators/slashing_protection.sqlite3
nimbus_be 130 nimbus   14u     REG               1,17        4152             1222360 /Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/validators/slashing_protection.sqlite3-wal
nimbus_be 130 nimbus   15u     REG               1,17       32768             1222361 /Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/validators/slashing_protection.sqlite3-shm
nimbus_be 130 nimbus   16u    IPv4 0xab8a0fd6c8ba4c93         0t0                 UDP *:cslistener
nimbus_be 130 nimbus   17u    IPv4 0xab8a0fd6ce890683         0t0                 TCP *:cslistener (LISTEN)
nimbus_be 130 nimbus   18u    IPv4 0xab8a0fd6d4eb4683         0t0                 TCP 207.254.102.130:cslistener->pool-173-56-7-155.nycmny.fios.verizon.net:etlservicemgr (ESTABLISHED)
nimbus_be 130 nimbus   19u    IPv4 0xab8a0fd6c80a1ab3         0t0                 TCP 207.254.102.130:cslistener->83.22.152.36.ipv4.supernova.orange.pl:51792 (ESTABLISHED)
nimbus_be 130 nimbus   20u    IPv4 0xab8a0fd6c7fd509b         0t0                 TCP 207.254.102.130:cslistener->dslb-002-204-108-161.002.204.pools.vodafone-ip.de:13000 (ESTABLISHED)
nimbus_be 130 nimbus   21u    IPv4 0xab8a0fd6d5ab7c6b         0t0                 TCP 207.254.102.130:cslistener->cpe-76-182-253-152.tx.res.rr.com:60378 (ESTABLISHED)
...(omited)...
```
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo lsof -p 130 | wc -l
     262
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo lsof -p 130 | grep ESTABLISHED | wc -l
     238
```

**Comment by jakubgs** [comment]
Our limits are quite high since [we adjust them with Ansible](https://github.com/status-im/infra-role-bootstrap-macos/blob/349f4332052ec93dc5811a793711bc3202ec860b/defaults/main.yml#L57-L58):
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sysctl kern.maxfiles       
kern.maxfiles: 200000                                            
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sysctl kern.maxfilesperproc
kern.maxfilesperproc: 200000
```

**Comment by stefantalpalaru** [comment]
See also `ulimit -n` in the shell.

**Comment by jakubgs** [comment]
You have access to the host, like other people that [have access](https://github.com/status-im/infra-nimbus/blob/8c69a70ccdbfd764663fd1a60e409741f7c70d1d/ansible/group_vars/all.yml#L8-L17):
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo cat /Users/stefan/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAw+3UpA5lT+8uAHdexl8isVhJX/I9knR34IRRkvEUaJzFF8XbTBeMsFHWTdY97zA9pl3GToKAymsw6+kBJ21yNztmRBQIpI1zmdhX6rV2u7waZUcOzyZDclOAG51TOijbzjWtDS/O0OGCEUsWDU8vvX10YGg0nHOjGI6uumUJYQp67C1Z5101Ygn3IhkBStzc7Pk2rUDErYFhom4KKD8w66vrPG9kqsR2i/pcW3EPI/5dz8FriaK+GB7OoZ7nTFhP/IlIV7hJUQZaOA69hkwwBz8LE6eTgoZwX6Q4b+ZxMXBR51xiljMYfKYg4FUGhcRdljxPr8HbObOf5YwTz5Vtaw== stefan@status.im
```
But as I said above, the limits are increased at boot, so they are set at `200000`:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % ulimit -n
200000
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo su - nimbus
nimbus@macos-01.ms-eu-dublin.nimbus.prater:~ % ulimit -n
200000
```

**Comment by jakubgs** [comment]
To be more sure on Linux I could just look at `/proc/${PID}/limits` to see the effective limits for a given process, but on MacOS there is no `/proc` filesystem...

Based on this answer only the process itself can check its own limits, which is pretty dumb:
https://itectec.com/askdifferent/macos-how-to-check-max-allowed-open-files-ulimit-of-a-running-process-or-running-app/

Though I wouldn't expect them to be different.

**Comment by jakubgs** [comment]
Launchd has the same limit:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo launchctl limit maxfiles
	maxfiles    200000         200000      
```

**Comment by jakubgs** [comment]
I can't even trace the process because of system integrity protection:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo dtruss -p 130 2>&1 | tail -n1

: probe description syscall:::entry does not match any probes. System Integrity Protection is on
```

**Comment by jakubgs** [comment]
Since disabling SIP requires pressing buttons at boot I had to open a support ticket with MacStadium to get this done:
https://portal.macstadium.com/tickets/140647

**Comment by stefantalpalaru** [comment]
> You have access to the host

```text
$ ssh stefan@macos-01.ms-eu-dublin.nimbus.prater.statusim.net
Connection closed by 207.254.102.130 port 22
```

**Comment by jakubgs** [comment]
Yep, SSH access [is restricted to only `admin` group members](https://www.vinnie.work/blog/2020-12-26-why-so-hard-osx-ssh-access/) for some very good reason I'm sure...

I've added Nimbus team members to `admin` group: https://github.com/status-im/infra-nimbus/commit/7aa5d2d4

**Comment by jakubgs** [comment]
Okay, I had SIP disabled on the host, so now when the issues appear again we can use `dtruss` to look at the syscalls:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo csrutil status 

System Integrity Protection status: disabled. 
```

**Comment by jakubgs** [comment]
Since `_node_maintenance` event type has `ServiceID` and `ServicName` set to `""` I can't filter for it with `-service`:
```
admin@node-01.do-ams3.consul.hq:~ % consul watch -type checks -service '' cat | jq '. | length'
617
617
617
617
617
617
```
I just get ALL service check events available.

**Comment by jakubgs** [comment]
Opened an issue about this bug: https://github.com/hashicorp/consul/issues/11330

**Comment by jakubgs** [comment]
But indeed, there are debug level messages that indicate an issue with number of files opened:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % grep 'Too many files opened' /Users/nimbus/beacon-node-prater-stable/logs/service.log | head -n1 | jq
```
```json
{
  "lvl": "DBG",
  "ts": "2021-10-15 16:13:35.579+01:00",
  "msg": "Too many files opened",
  "topics": "libp2p tcptransport",
  "tid": 2343,
  "file": "tcptransport.nim:216",
  "exc": "Too many open transports!"
}
```
Though these ones are related to libp2p, and not metrics, but it's certainly something.

**Comment by jakubgs** [comment]
Since I cannot actually check the effective limit of files for a given process it would be cool if beacon node itself checked that limit at startup and printed a warning if the limit is too low to function properly.

**Comment by jakubgs** [comment]
MacOS does provide a POSIX complaint `getrlimit` syscall that be give the `RLIMIT_NOFILE` resource parameter:
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrlimit.2.html

Appears to be available from Nim: https://nim-lang.org/docs/posix.html#getrlimit%2Ccint%2CRLimit

This way we could check the effective limit for the process on both Linux and MacOS.

**Comment by jakubgs** [comment]
If I use [`errinfo`](https://www.manpagez.com/man/1/errinfo/) to count failing syscalls I get this:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo errinfo -c -p 136 2>/dev/null
            EXEC          SYSCALL  ERR  COUNT  DESC
nimbus_beacon_node           accept   24      4  Too many open files 
```
And if I filter with `dtruss` for `accept` event I get this:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo dtruss -t accept -p 136 2>&1 
SYSCALL(args) 		 = return
accept(0x3, 0x16BE3E9E0, 0x16BE3E9D4)		 = 131 0
accept(0x3, 0x16BE3E9E0, 0x16BE3E9D4)		 = 131 0
accept(0x3, 0x16BE3E9E0, 0x16BE3E9D4)		 = -1 Err#24
accept(0x3, 0x16BE3E9E0, 0x16BE3E9D4)		 = -1 Err#24
accept(0x3, 0x16BE3E9E0, 0x16BE3E9D4)		 = -1 Err#24
accept(0x3, 0x16BE3E9E0, 0x16BE3E9D4)		 = -1 Err#24
```
So something is definitely up.

**Comment by jakubgs** [comment]
I added a check for limits to the [`init()`](https://github.com/status-im/nimbus-eth2/blob/9381ad352f63403cbd46a1dd03d18d039148dbcb/beacon_chain/nimbus_beacon_node.nim#L103-L111) method which looks something like this:
```nim
from posix import getrlimit, RLIMIT_NOFILE, RLimit
var limits = RLimit()
var rval = getrlimit(RLIMIT_NOFILE, limits)
fatal "file limits", limits = limits
quit 1
```
And this is what I got:
```
{
  "lvl": "FAT",
  "ts": "2021-10-15 17:36:33.777+01:00",
  "msg": "file limits",
  "topics": "beacnde",
  "tid": 1534118,
  "file": "nimbus_beacon_node.nim:118",
  "limits": {
    "rlim_cur": 200000,
    "rlim_max": 200000
  }
}
```
So the limits are exactly as we are setting them...

![what](https://user-images.githubusercontent.com/2212681/137522619-6a84b4b5-ec63-4ae6-82f9-3d93103ced71.gif)

**Comment by jakubgs** [comment]
I added a log message inside of the metrics thread to verify the limits are the same in there:
https://github.com/status-im/nim-metrics/blob/b4c6a51ee75b102a9e36b8b8f2a02760d38219d8/metrics.nim#L381
But the limits are correct:
```
limits: (rlim_cur: 200000, rlim_max: 200000)
```

**Comment by jakubgs** [comment]
I've decided to take a sledgehammer and just increase the limits by an order of magnitude to `2000000` and simply see if that makes a difference over the weekend. Simple but effective way to check if the file limit is a red herring.
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % grep string /Library/LaunchDaemons/limit.maxfiles.plist 
        <string>limit.maxfiles</string>
          <string>launchctl</string>
          <string>limit</string>
          <string>maxfiles</string>
          <string>2000000</string>
          <string>2000000</string>

admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sysctl kern.maxfiles                                   
kern.maxfiles: 2000000
```

**Comment by stefantalpalaru** [comment]
"In OS X Yosemite, the max limit you can set is 65536. If you set it any higher the OS will use default settings of  maxfiles 1024 1024 ." - https://apple.lib.utah.edu/open-file-limits-on-os-x-what-they-are-why-increase-them-and-how-to-increase-them/

**Comment by jakubgs** [comment]
If it was resetting to the default of `1024` then that should show up in the result from `getrlimit()`, and it doesn't. Although then again, something that stupid definitely sounds like something Apple engineers could do...

Also we're not on `10.10` but on `11.5.1`, but it could still be in effect.

I'll give it some time with `2000000` to see what happens, and I can try `65536` tomorrow.

**Comment by jakubgs** [comment]
About 4.5 hours after start we start seeing gaps, so it doesn't seem like the value of `2000000` improved anything:

![image](https://user-images.githubusercontent.com/2212681/137577937-1b4d1ce9-1046-4350-8ddd-ca24950baa24.png)

Lets try `65536` then.

**Comment by jakubgs** [comment]
Done:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sysctl kern.maxfiles                                                       
kern.maxfiles: 65536
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo launchctl limit maxfiles
	maxfiles    65536          65536 
```
And the `init` method shows them correctly:
```
{
  "lvl": "FAT",
  "ts": "2021-10-16 08:45:30.519+01:00",
  "msg": "file limits",
  "topics": "beacnde",
  "tid": 37728,
  "file": "nimbus_beacon_node.nim:118",
  "limits": {
    "rlim_cur": 65536,
    "rlim_max": 65536
  }
}
```
Same for the metrics [`pushMetricsWorker()`](https://github.com/status-im/nim-metrics/blob/b4c6a51ee75b102a9e36b8b8f2a02760d38219d8/metrics.nim#L381) method:
```
file limits: (rlim_cur: 65536, rlim_max: 65536)
```

**Comment by jakubgs** [comment]
Wow, it actually worked. That's so dumb:

![image](https://user-images.githubusercontent.com/2212681/137622360-987a9de2-5930-445c-a507-28f56aa6e1ee.png)

Apple will never cease to amaze me...

**Comment by jakubgs** [comment]
Which means that we can't even do my suggestion from https://github.com/status-im/nimbus-eth2/issues/2984#issuecomment-944410931, because `getrlimit()` doesn't return the actual effective limit, so we can't check for that at runtime. But maybe we can at least add a note about this somewhere in the docs.

Fix in MacOS bootstrap role: https://github.com/status-im/infra-role-bootstrap-macos/commit/a0ab4fb8

**Comment by jakubgs** [comment]
This is weird, the node got restarted yesterday around 10:00, and now we see gaps again:

![image](https://user-images.githubusercontent.com/2212681/137697833-9ff9a3b7-e9ef-40d1-976e-0812efc69a25.png)

And if I grep the logs at the time of the restart I see some weird values:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus/beacon-node-prater-stable/logs % cat service.20211017_1209.log.gz | zcat | grep limit
file limits: (rlim_cur: 256, rlim_max: 9223372036854775807)
```
Where the hell is that coming from?
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo sysctl kern.maxfiles
kern.maxfiles: 65536
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo launchctl limit maxfiles
	maxfiles    65536          65536
```

**Comment by jakubgs** [comment]
Something interesting I noticed, is that while `stable` did have no gaps as shown in https://github.com/status-im/nimbus-eth2/issues/2984#issuecomment-945084759, the other branches had them:

---
### `stable`

![image](https://user-images.githubusercontent.com/2212681/137698396-689f64e9-ec44-45d1-b8c4-f38a761c4584.png)

### `testing`

![image](https://user-images.githubusercontent.com/2212681/137698448-af58a6f4-098a-45f1-ae9c-1fa90ab9b0d9.png)

### `unstable`

![image](https://user-images.githubusercontent.com/2212681/137698481-483af2f4-cafe-4420-8121-b68a767e063b.png)

---
What the hell?

**Comment by jakubgs** [comment]
This is interesting, `stable` node was restarted a few times after host reboot, and from the log we can see that the limit is `256` right after reboot, but `65536` on consequent restarts:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus/beacon-node-prater-stable/logs % cat service.20211016_0920.log.gz | zcat | grep limit
file limits: (rlim_cur: 256, rlim_max: 9223372036854775807)
file limits: (rlim_cur: 65536, rlim_max: 65536)
file limits: (rlim_cur: 65536, rlim_max: 65536)
file limits: (rlim_cur: 65536, rlim_max: 65536)
file limits: (rlim_cur: 65536, rlim_max: 65536)
file limits: (rlim_cur: 65536, rlim_max: 65536)
```
Which might mean that the node starts before the limits applied by `/Library/LaunchDaemons/limit.maxfiles.plist` takes effect.

**Comment by jakubgs** [comment]
Since the hard limit appears to be so high at boot I tried using `setrlimit()` method:
```nim
  var limits = RLimit()
  var rval = getrlimit(RLIMIT_NOFILE, limits)
  echo "getrlimit: ", limits

  limits.rlim_cur = 65536
  rval = setrlimit(RLIMIT_NOFILE, limits)
  echo "setrlimit: ", rval

  rval = getrlimit(RLIMIT_NOFILE, limits)
  echo "getrlimit: ", limits
```
And this is what I get after reboot:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % grep rlimit /Users/nimbus/beacon-node-prater-stable/logs/service.log             
getrlimit: (rlim_cur: 256, rlim_max: 9223372036854775807)
setrlimit: 0
getrlimit: (rlim_cur: 65536, rlim_max: 9223372036854775807)
```
So we see the process itself can raise its own limit, at least based on `getrlimit()` output, lets see what happens after that.

**Comment by jakubgs** [comment]
So far so good, the modified `stable` branch shows no gaps:

![image](https://user-images.githubusercontent.com/2212681/137740121-0d5c6713-68f1-413f-84dc-02ff0f7a1d65.png)

While the `testing` branch shows gaps:

![image](https://user-images.githubusercontent.com/2212681/137740160-73c9d3c6-f042-4b52-93f0-f227aa95de03.png)

So it appears that the correct solution on MacOS is using `setrlimit` to increase the soft limit of open files.

**Comment by jakubgs** [comment]
Now, I'm not sure what's the correct behavior here is. I guess something like:

1. Check soft and hard limit
2. If soft limit is lower than hard limit raise it (to what value tho?)
3. Log error if failed to raise the soft limit but continue
4. Test the limit using method described by @jlokier (using `dup2`)
5. Log error if effective limit is lower than soft limit

What do you think @stefantalpalaru ?

**Comment by stefantalpalaru** [comment]
This kind of limit should be set by the user, not by individual programs.

Detecting the maximum number of file descriptors we need to open is difficult, because the peer limit only applies to outgoing connections, not incoming ones. Once a minimum requirement is established (say it's `max-peers * 1.1`), it's acceptable to print an error message and exit, if the system's limit is lower - like when you want 1000 max peers, but that open fd limit is 256.

Testing the limit on macOS instead of trusting the libc call makes sense, knowing what we know.

**Comment by jakubgs** [comment]
>This kind of limit should be set by the user, not by individual programs.

Well, that's more related to the hard limit, not the soft limit. The system administrator should adjust hard limits if they want to limit what the process can use. The entire reason why `setrlimit` exists is to allow the process to adjust it's own soft limits within the hard limits:

>The soft limit is the value that the kernel enforces for the corresponding resource. The hard limit acts as a ceiling for the soft limit: an unprivileged process may only set its soft limit to a value in the range from 0 up to the hard limit, and (irreversibly) lower its hard limit.
https://linux.die.net/man/2/setrlimit

I believe part of the reason for `setrlimit`'s existence is to adjust limits for child processes spawned by the parent.

>Once a minimum requirement is established (say it's max-peers * 1.1)

Yes, I think basing the limit on number of max peers plus some is a good idea.

**Comment by jlokier** [comment]
Why so many file descriptors anyway? Is there a leak? Is max-peers large on the fleet?

**Comment by jlokier** [comment]
On MacOS 10.15.7 (Darwin 19.6.0), which is older than the fleet node, but newer than 10.10 where the 65536 bizarro limit was mentioned:

`rlim_cur` can be set up to `sysctl kern.maxfilesperproc`, which is 24576 on my system, but that value can be increased.  Any attempt to set `rlim_cur` higher results in `EINVAL`.

When setting `rlim_cur`, it can't be copied from `rlim_max`. The manual `man setrlimit` explains:

> `setrlimit()` now returns with `errno` set to `EINVAL` in places that historically succeeded.  It no longer accepts "`rlim_cur = RLIM_INFINITY`" for `RLIM_NOFILE`.  Use "`rlim_cur = min(OPEN_MAX, rlim_max)`".

`OPEN_MAX` is 10240 on this system though.  `rlim_cur` can be set higher.

The actual highest file descriptor which can be opened plus one usually matches `rlim_cur`.  But it's also limited by`sysctl kern.maxfiles`, which is 49152 on my system. This value can be set higher too.  This is not supposed to be lower than`kern.maxfilesperproc`, but if it is, then the process can set `rlim_cur` to `kern.maxfilesperproc` but will find its highest file descriptor is limited by `kern.maxfiles`.

I had no problem setting `kern.maxfiles` and `kern.maxfilesperproc` to very large values (10M+), and a C test program was able to set `rlim_cur` up to exactly those values, and open the corresponding file descriptors with `dup2`.  So on MacOS 10.15.7 I don't see any strange limit at 65536.

Given the article which mentions that was about MacOS 10.10, and the fleet is running MacOS 11.5.1, I would be surprised if that limit went away and was later restored.  Maybe it's a feature of `launchd` rather than the kernel; I didn't try tweaking `launchd`.

**Comment by jlokier** [comment]
I feel it is worth a mention that `ioselectors_kqueue.nim` in Chronos, or in the Nim stdlib, already seems to know something about `kern.maxfiles` and `kern.maxfilesperproc` on MacOS, FreeBSD, Dragonfly, NetBSD and OpenBSD.

**Comment by jakubgs** [comment]
>Why so many file descriptors anyway? Is there a leak? Is max-peers large on the fleet?

The default is 160 peers:
https://github.com/status-im/infra-role-beacon-node-macos/blob/d4d08f06/defaults/main.yml#L48

But that's changed for Prater fleet to 300:
https://github.com/status-im/infra-nimbus/blob/1dfba96/ansible/group_vars/nimbus.prater.yml#L18

Which does match the results from `lsof`:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo lsof -nP -p 136 | wc -l
     325

admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo lsof -nP -p 136 | grep -e ESTABLISHED -e '9000->' | wc -l
     301

admin@macos-01.ms-eu-dublin.nimbus.prater:~ % sudo lsof -nP -p 136 | grep -v -e ESTABLISHED -e '9000->' | wc -l
      22
```

**Comment by jakubgs** [comment]
Will anyone pick this up then?

**Comment by Menduist** [comment]
> because the peer limit only applies to outgoing connections, not incoming ones.

If you are talking about `--max-peers`, this is not true, it applies to both incoming & outgoing connections.
And this thread is another example of why we need a good hard boundary on peer count, instead of a soft one like most other libp2ps

**Comment by jakubgs** [comment]
For now as a temporary fix suggested by @zah I've lowered the max peers to 200: https://github.com/status-im/infra-nimbus/commit/5f04e4b1

This should allow us to avoid hitting the limit if we don't restart the service after reboot. But a proper fix would be nice.

**Comment by stefantalpalaru** [comment]
> it applies to both incoming & outgoing connections

Are you sure?

> we need a good hard boundary on peer count, instead of a soft one like most other libp2ps

A hard limit opens you up to this sort of attack: an early node you connect to feeds you other nodes under the same control until all your outgoing connections are into that malicious subnet; any incoming connection from non-malicious nodes will be rejected because you've already reached your limit.
