### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by BinderL** [status-im/nim-beacon-chain#3035]
**Describe the bug**
error while building nimbus_beacon_node 

**To Reproduce**
1. Platform details 

(OS, architecture): 
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            126.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

2. Branch/commit used:
HEAD is now at 121628357 Merge branch 'version-1-2' into nimbus
3. Commands being executed:
make nimbus_beacon_node
4. Relevant log lines: 
**Screenshots**
HEAD is now at 121628357 Merge branch 'version-1-2' into nimbus
Building: build/nimbus_beacon_node
/home/pither/nimbus-eth2/beacon_chain/rpc/rest_beacon_api.nim(748, 9) template/generic instantiation of `api` from here
/home/pither/nimbus-eth2/vendor/nim-presto/presto/route.nim(329, 65) template/generic instantiation of `async` from here
/home/pither/nimbus-eth2/beacon_chain/rpc/rest_beacon_api.nim(755, 35) template/generic instantiation of `decodeBody` from here
/home/pither/nimbus-eth2/beacon_chain/spec/eth2_apis/eth2_rest_serialization.nim(906, 15) template/generic instantiation of `decode` from here
/home/pither/nimbus-eth2/vendor/nim-serialization/serialization.nim(47, 31) Error: type mismatch: got <type ReaderType`gensym441290011, InputStreamHandle>
but expected one of: 
proc init[A](s: var HashSet[A]; initialSize = defaultInitialSize)
  first type mismatch at position: 1
  required type for s: var HashSet[init.A]
  but expression 'ReaderType`gensym441290011' is of type: type ReaderType`gensym441290011

expression: init(ReaderType`gensym441290011, stream`gensym441290010)
make: *** [Makefile:260: nimbus_beacon_node] Error 1

**Comment by etan-status** [comment]
Thanks for this report. I was recently seeing a similar build error on a different platform.

Would you mind testing whether the (earlier) commit `c40cc6cec1f326a8fbd49c6afe14b2492e3d6f35` builds correctly on your platform? Note that this specific commit is NOT a release, just a random commit to help debugging this, so please don't rely on this in production as it is missing later updates.

**Comment by stefantalpalaru** [comment]
> HEAD is now at 121628357 Merge branch 'version-1-2' into nimbus

That comes from a Git submodule. To see your current HEAD, run `git rev-parse HEAD`. To see your branch, run `git status`.

**Comment by BinderL** [comment]
It works for me thanks guys !

**Comment by etan-status** [comment]
Glad to hear. Did you need to change something for it to work, or did this issue just magically disappear? 😶‍🌫️
