### ISSUE TITLE
32-bit: Slow state advance comparing to 64-bit

### ISSUE THREAD

**Issue by eshavkun** [status-im/nim-beacon-chain#308]
Hardware: Rasberry Pi 3B+
32-bit OS: Raspbian Buster
64-bit OS: Ubuntu Server 18.04

Network sync (Advancing state with empty slots) is much slower on 32-bit OS compared to 64-bit OS. Currently (around 20000 slots) it takes less than 1 hour on 64-bit while more than 4 hours on 32-bit

**Comment by mratsim** [comment]
It's definitely linked to #102 and might be linked to #370 and Nim slow stack scanning when too much stack space is used.

**Comment by mratsim** [comment]
Similar to #102 Outdated, the improvement from the past 3 months has removed spurious hashTreeRoot. Can be confirmed with blocksim / statesim
