### ISSUE TITLE
Nimbus should provide CLI options suitable for operating archive nodes

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#3081]
The following additional CLI options are suggested:

* `--db-state-snapshots-interval: Option[int]`
* `--db-pruning: bool`

A user will be then able to configure Nimbus as an archive node that can answer historic queries quickly. The snapshot interval allows for trading storage space for speed.

To further improve the support for archive nodes, future version of Nimbus may use a more compact representation for the append-only fields in the `BeaconState` that would make their presence in snapshots unnecessary. Instead, we can have a single append-only storage item for every append-only field and we can compute the range within that storage item that corresponds to a particular finalized state.

**Comment by arnetheduck** [comment]
With regards to a snapshot density option, I think this is generally not needed with state-diffs - they should be small and efficient enough that maintaining an option for it is unlikely to be useful.

**Comment by arnetheduck** [comment]
this is implemented in the form of `--history=archive` - the rest is / will be covered by state-diff which is tracked separately
