### ISSUE TITLE
Implement dynamic sync committee subnet walking

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#3084]
* [x] Nimbus should subscribe and unsubscribe to sync committee topics dynamically, according to the upcoming sync committee duties:

   https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/validator.md#sync-committee-subnet-stability

* [ ] This should be well integrated with the subnet walking functionality, aiming to find appropriate peers on the network through discovery metadata:

   https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/p2p-interface.md

* [x] It should be possible for a validator client to drive the process through the `POST ​/eth​/v1​/validator​/sync_committee_subscriptions` API:

   https://ethereum.github.io/beacon-APIs/#/Validator/prepareSyncCommitteeSubnets
   
* [x] The gossip backoff time should be taken into account similarly to the way it's handled here:

   https://github.com/status-im/nimbus-eth2/pull/3025

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/3308 implements this. As regards the gossip backoff time, https://github.com/status-im/nimbus-eth2/pull/3207 more directly fixed (rather than worked around) that via https://github.com/status-im/nim-libp2p/pull/665 so it should be a non-issue.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/3348 implements part of the subnet walking aspect, by switching to using the Altair ENR records which know about sync committee subnets rather than phase0 ENR records which wouldn't help here.

**Comment by tersec** [comment]
Closing because the remaining item is better tracked separately.
