### ISSUE TITLE
Observed 100% CPU usage and lack of syncing progress (unstable branch)

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#3130]
@stefantalpalaru observed his client being stuck during syncing while using 100% of the CPU. The captured stack trace suggests this is a new problem introduced with the migration to nim-websock in the latest version of nim-json-rpc:

https://gist.github.com/stefantalpalaru/311ea3e48f104250c6c3dbc4ee0b3718

**Comment by arnetheduck** [comment]
Testnet server hit this as well: https://metrics.status.im/d/pgeNfj2Wz23/nimbus-fleet-testnets?orgId=1&var-instance=metal-01.he-eu-hel1.nimbus.mainnet&var-container=beacon-node-mainnet-unstable-01&from=1638205162625&to=1638212419031 (spinning on `recvMsg`)

**Comment by stefantalpalaru** [comment]
Fixed by https://github.com/status-im/nimbus-eth2/pull/3136

**Comment by Menduist** [comment]
Do we have a test for this? To see if https://github.com/status-im/nim-websock/pull/100 fixes it

**Comment by stefantalpalaru** [comment]
The test is to manually sync a network from scratch, for a few days.
