### ISSUE TITLE
Implement the required changes for interoperability with mev-boost

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#3200]
mev-boost is a new agent that will enable the Eth2 validators to optimize their proposed blocks for "maximum extracted value" (aka MEV) obtained by delegating the selection of execution layer transactions to the FlashBots network. The agent sits between the consensus and the execution layer client and communicates with both. You can find more about the overall architecture of mev-boost and Flashbots here:

https://ethresear.ch/t/mev-boost-merge-ready-flashbots-architecture/11177

The users of Nimbus will enable the use of mev-boost by supplying a `--mev-url` parameter. When provided, it will take precedence over any other `--web3-url` parameter for the purposes of execution engine communication. The communication protocol with the MEV agent is slightly different because it requires the consensus node to be able to sign a beacon block 'header" without seeing the full list of transactions that will be included in the block. Until now, the only pilot implementation of this functionality is present in the following Lighthouse branch:

https://github.com/realbigsean/lighthouse/tree/mev-lighthouse

**Comment by arnetheduck** [comment]
Beacon API issue: https://github.com/ethereum/beacon-APIs/issues/179

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/3883
