### ISSUE TITLE
[FR] Employ a Primary / Secondary Strategy for `--web3-url` Endpoints Instead of Round-Robin

### ISSUE THREAD

**Issue by jclapis** [status-im/nim-beacon-chain#3214]
In an upcoming release of Rocket Pool's Smartnode stack, we're adding formal support for fallback execution clients. This is largely driven by the need to prune Geth periodically without interrupting any of the Smartnode's behavior. The typical approach would be:

- Use a local Geth instance as the "primary" client
- Use something like Infura or another local execution client as a "fallback" client
 
The intent of this fallback is to act as a temporary endpoint only while Geth goes down for maintenance. The Smartnode understands this and will periodically (every 60 seconds by default) attempt to reconnect to Geth; once successful, it will swap back to that connection and stop using the fallback.

While adding the appropriate command line arguments to the start script for each client, I noticed that Nimbus doesn't behave this way; it considers all execution client endpoints (`--web3-url` entries) to be equal. When one of them goes down, it will happily connect to the next one in the list. However, it will remain connected to that one for as long as the connection persists.

I think it's beneficial to use a local execution client when possible from both a decentralization perspective and a performance perspective - especially in the context of the Merge, where a reliable connection to an execution client is critical. Operating under the assumption that most setups will probably have a "preferred" execution client as described above, my request here is that Nimbus adopts a "primary / secondary" regime for execution clients instead of treating them all equally.

The only appreciable difference is that when the BN loses connection to the primary, it should regularly try to reconnect and upon a successful connection, drop an existing connection to a fallback client.

**Comment by zah** [comment]
Since the described behavior here matches the prior expectations of most users of the software, it was implemented in https://github.com/status-im/nimbus-eth2/pull/3354. The change will be shipped with Nimbus 1.7.0.
