### ISSUE TITLE
The REST API doesn't serve JSON data by default

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#3261]
According to the Beacon API spec:

> All requests by default send and receive JSON, and as such should have either or both of the "Content-Type: application/json" and "Accept: application/json" headers. In addition, some request can return data in the SSZ format. To indicate that SSZ data is required in response to a request the header "Accept: application/octet-stream" should be sent. Note that only a subset of requests can respond with data in SSZ format; these are noted in each individual request.
https://ethereum.github.io/beacon-APIs/

Nimbus currently violates the spec when the client uses the Accept header `*/*` which is the default mode employed by curl:

```bash
$ curl -v -X GET localhost:5052/eth/v2/beacon/blocks/head
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1:5052...
* connect to ::1 port 5052 failed: Connection refused
*   Trying 127.0.0.1:5052...
* Connected to localhost (127.0.0.1) port 5052 (#0)
> GET /eth/v2/beacon/blocks/head HTTP/1.1
> Host: localhost:5052
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nim-presto/0.0.3 (arm64/macosx)
< Content-Length: 17814
< Content-Type: application/octet-stream
< Date: Sat, 08 Jan 2022 18:47:52 GMT
< Connection: keep-alive
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0
```

The root of the problem is the definition of the `preferredContentType` in Chronos's `httpserver` module which requires a precise match in the content type instead of implementing wildcard matches. Furthermore, all invocations of `preferredContentType` within nimbus-eth2 should be modified to put "application/json" as a higher preference than "application/octet-stream".

**Comment by arnetheduck** [comment]
>  Furthermore, all invocations of preferredContentType within nimbus-eth2 should be modified to put "application/json" as a higher preference than "application/octet-stream".

why? json is order of magnitudes slower and larger - it's a really really bad idea for anyone to _ever_ use json  unless they're forced to..

while we're here, I would really like to see two things though: 

* `snappy` support by using  https://github.com/google/snappy/blob/master/framing_format.txt#L35
* a generated filename for the downloaded resource, that ends with `.ssz`

**Comment by zah** [comment]
> why?

Well, this is about following the spec. See the first sentence of the citation above. I guess it's possible to argue that the spec is not fully defined for the curl request as it violates the second sentence.

Personally, I think it does make sense to stick to JSON by default as quite often imprecise requests are performed by humans. Applications tend to get their headers right.

**Comment by arnetheduck** [comment]
> All requests by default send and receive JSON, and as such should have either or both of the "Content-Type: application/json" and "Accept: application/json" headers

Well, there are two "should" here open for interpretation - in particular, it says that if you want json, you should "accept ..." it. The main problem is the state request - a state is well over 100mb in JSON.

**Comment by zah** [comment]
Consider the fact that I learned about this issue because a fellow Ethereum developer (on a client team) who was tripped by the curl error message and wasn't sure what the problem is. Getting a reasonable default output from one of the most widely used tools for testing the API is an important feature.

**Comment by arnetheduck** [comment]
fair enough - I wish there was an easy way to grab ssz:s though - anyway, one thing that's really important is that our own validator client uses SSZ during trusted node sync (it's barely usable otherwise).

**Comment by cheatfate** [comment]
@zahary according to specification
> All requests by default send and receive JSON, and as such should have either or both of the "Content-Type: application/json" and "Accept: application/json" headers.

So i understand that REST request SHOULD follow HTTP specification and use `Accept` header to specify what type of content he wants to receive.

According to HTTP specification client SHOULD specify what type of content he wants to receive via `Accept` header. If `Accept` header is missing or invalid it will be considered as `*/*` (any type of content which server supports). 
https://httpwg.org/specs/rfc7231.html#rfc.section.5.3.2

For REST server is much more cheaper to respond via `application/octet-stream` for requests which supports 2 content types (`application/json` and `application/octet-stream`). So if unknown Ethereum developer wants to change HTTP protocol defaults, he should change specification accordingly.

`nim-chronos` works according to HTTP specification, also chronos `Accept` parser is not so dumb and supports wildcard matches as well as weighted matches too. The only problem that when client supply `Accept: */*` it doesn't mean that server MUST respond with `application/json`, it means that server COULD respond in any encoding it prefer.

And what interesting that Ethereum API specification says that you SHOULD use `Accept: application/json` and not `Accept: */*`.

**Comment by cheatfate** [comment]
But if you still want to change defaults, you only need to change lines like this
https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/rpc/rest_beacon_api.nim#L836-L837
https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/rpc/rest_beacon_api.nim#L868-L869
https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/rpc/rest_debug_api.nim#L35-L36

```nim
preferredContentType("application/octet-stream", "application/json")
```
to
```nim
preferredContentType("application/json", "application/octet-stream")
```

**Comment by mratsim** [comment]
> fair enough - I wish there was an easy way to grab ssz:s though - anyway, one thing that's really important is that our own validator client uses SSZ during trusted node sync (it's barely usable otherwise).

Getting the state is a "debug" API that is not standardized. AKA, license to do anything.

**Comment by zah** [comment]
> nim-chronos works according to HTTP specification, also chronos Accept parser is not so dumb and supports wildcard matches as well as weighted matches too. The only problem that when client supply Accept: */* it doesn't mean that server MUST respond with application/json, it means that server COULD respond in any encoding it prefer.

> But if you still want to change defaults, you only need to change lines like this

Testing has revealed that this is not enough. There are some issues in the Chronos implementation, but a bounty developer is now working to resolve them. He will submit a PR soon.

**Comment by zah** [comment]
Fixed in https://github.com/status-im/nimbus-eth2/pull/3307
