### ISSUE TITLE
Tracking the SyncCommittee period

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#3281]
Currently validators have no way to know if they have sync committee duties or when is their next one to time restarts and node updates.

**Comment by tersec** [comment]
https://ethereum.github.io/beacon-APIs/#/Validator/getSyncCommitteeDuties ?

**Comment by arnetheduck** [comment]
I think that's an adequate solution indeed - I'm not sure what this ticket intended really, cc @mratsim

**Comment by mratsim** [comment]
Users are relying on nextActionWait at slotEnd to plan their restart for example after upgrading.

They use it to ensure that if possible there is no downtime when they have validator duties.

However currently nextActionWait doesn't track sync committees.

So either we had that to nextActionWait or we add a new log field for example "syncCommitteeDuties" which can take "None" "in xx hhmmss" or "current"

**Comment by zah** [comment]
Considering the sync committee duties in `nextActionWait` should be trivial indeed and we should do it.

**Comment by tersec** [comment]
Closed via https://github.com/status-im/nimbus-eth2/pull/3854
