### ISSUE TITLE
kintsugi-nimbus-besu fails to sync past slot 1219

### ISSUE THREAD

**Issue by SeaMonkey82** [status-im/nim-beacon-chain#3305]
**Describe the bug**
On kintsugi, nimbus connects to besu, but goes into a loop at slot 1219 perpetually rewinding to 1152.

**To Reproduce**
1. Linux Mint 20.3 x86_64
2. 1a94c59c4a2ca75b1a0c696fd144a2026fd107d8
3. 
`~/Downloads/merge-testnets/kintsugi/besu/build/install/besu/bin/besu --data-path "/home/seamonkey/eth/kintsugi-nimbus-besu" --genesis-file $HOME/Downloads/merge-testnets/kintsugi/besu_genesis.json --rpc-http-api=ADMIN,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION --rpc-ws-api=ADMIN,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION --network-id=1337702 --p2p-enabled=true --Xmerge-support=true --bootnodes=enode://6f377dd1ef5a3272d7e02fac9064c4f95d74f7edfd866e59ded774ee5b4649ff61c3f24c95f5c3d07d692b447f0569716b8921b6861810b96a705c92e1d27ff9@161.35.67.219:30303 --p2p-port 13459 --rpc-ws-port 8557 --p2p-host "1.2.3.4" --miner-coinbase="0xdefinitelyavalidethaddress" --miner-enabled=true --rpc-http-port 8558 --rpc-http-enabled=true --rpc-ws-enabled=true`

`nimbus_beacon_node-kintsugi --network=$HOME/Downloads/merge-testnets/kintsugi --web3-url=ws://127.0.0.1:8557 --log-level=INFO --bootstrap-file=$HOME/Downloads/merge-testnets/kintsugi/bootstrap_nodes.txt --terminal-total-difficulty-override=5000000000 --data-dir=/home/seamonkey/eth/kintsugi-nimbus-besu --bootstrap-node=enr:-Iq4QKuNB_wHmWon7hv5HntHiSsyE1a6cUTK1aT7xDSU_hNTLW3R4mowUboCsqYoh1kN9v3ZoSu_WuvW9Aw0tQ0Dxv6GAXxQ7Nv5gmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk --nat=extip:1.2.3.4 --tcp-port=13460 --udp-port=13460 --graffiti="nimbus-besu seamonkey.tech" --rest --rest-port=5058`

4.

```
INF 2022-01-20 22:04:42.145-05:00 runQueueProcessingLoop: running forkchoiceUpdated headBlockRoot=00000000 finalizedBlockRoot=00000000 block_hash=00000000 parent_hash=00000000 executionPayloadStatus=VALID
DBG 2022-01-20 22:04:42.145-05:00 executePayload: inserting block into execution engine parentHash=f0c72c6a blockHash=fbaebc5d stateRoot=9d7e6b69 receiptsRoot=6c73ff45 random=ed9fc63c blockNumber=7052 gasLimit=8000000 gasUsed=7904939 timestamp=1639674528 extraDataLen=0 baseFeePerGas=7 numTransactions=145
INF 2022-01-20 22:04:42.146-05:00 newExecutionPayload failed                 msg="Transport is not initialised (missing a call to connect?)"
DBG 2022-01-20 22:04:42.146-05:00 Block pool rejected peer's response        topics="beacnde" peer=16U*63UDgE request_slot=1216 request_count=32 request_step=1 blocks_map=xxxx.xx.xx.x.xxxxx.xxx.xx....... blocks_count=19 errCode=MissingParent
WRN 2022-01-20 22:04:42.146-05:00 Unexpected missing parent, rewind happens  topics="beacnde" peer=16U*63UDgE rewind_to_slot=1152 rewind_epoch_count=2 rewind_fail_slot=1219 finalized_slot=1152 request_slot=1216 request_count=32 request_step=1 blocks_count=19 blocks_map=xxxx.xx.xx.x.xxxxx.xxx.xx.......
DBG 2022-01-20 22:04:42.146-05:00 Rewind to slot was happened                topics="beacnde" reset_slot=Some(1152) queue_input_slot=1152 queue_output_slot=1152 rewind_epoch_count=2 rewind_fail_slot=1219
DBG 2022-01-20 22:04:44.027-05:00 Peer's syncing status                      topics="beacnde" wall_clock_slot=256198 remote_head_slot=256195 local_head_slot=1218 peer_score=100 peer=16U*63UDgE index=5 peer_speed=294725.0 direction=Forward
DBG 2022-01-20 22:04:44.027-05:00 Creating new request for peer              topics="beacnde" wall_clock_slot=256198 remote_head_slot=256195 local_head_slot=1218 request_slot=1152 request_count=32 request_step=1 peer=16U*63UDgE peer_speed=294725.0 peer_score=100 index=5 direction=Forward
DBG 2022-01-20 22:04:44.027-05:00 Requesting blocks from peer                topics="beacnde" peer=16U*63UDgE slot=1152 slot_count=32 step=1 peer_score=100 peer_speed=294725.0 direction=Forward
DBG 2022-01-20 22:04:44.027-05:00 Current syncing state                      topics="beacnde" workers_map=wwwwwDwwww sleeping_workers_count=0 waiting_workers_count=9 pending_workers_count=1 wall_head_slot=256198 local_head_slot=1218 pause_time=0ns avg_sync_speed=4.917033818559962e+17 ins_sync_speed=4.917033818559962e+17 direction=Forward
DBG 2022-01-20 22:04:44.841-05:00 Received blocks on request                 topics="beacnde" blocks_count=31 blocks_map=.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx request_slot=1152 request_count=32 request_step=1 peer=16U*63UDgE peer_score=100 peer_speed=293059.0 index=5 direction=Forward
DBG 2022-01-20 22:04:44.849-05:00 Block already exists                       blockRoot=e177f4fb blck="(slot: 1153, proposer_index: 57472, parent_root: \"d5eaa295\", state_root: \"01908c3e\", eth1data: (deposit_root: d70a234731285c6804c2a4f56711ddb8c82c99740f207854891028af34e27e5e, deposit_count: 0, block_hash: 0000000000000000000000000000000000000000000000000000000000000000), graffiti: \"lodestar-geth\", proposer_slashings_len: 0, attester_slashings_len: 0, attestations_len: 34, deposits_len: 0, voluntary_exits_len: 0, sync_committee_participants: 441)"
```

**Comment by tersec** [comment]
`INF 2022-01-20 22:04:42.146-05:00 newExecutionPayload failed                 msg="Transport is not initialised (missing a call to connect?)"` is the important part.

Do your logs show when/why the transport failed? Without that web3 transport, the CL (Nimbus) can't ultimately verify via the EL (Besu) whether a post-merge block is correct, so that would stall syncing in terms of a verified head.

Currently, the `kintsugi` branch doesn't automatically reconnect to its web3 provider, which is a bug. https://github.com/status-im/nimbus-eth2/pull/3279 being merged today was a step towards fixing that. If restarting Nimbus so that its web3 connection is functioning works around this for the moment, that's what's possible with the commit on the `kintsugi` branch to which you link. If it keeps happening, and keeps losing its connection, then it might need some other fix.

**Comment by SeaMonkey82** [comment]
Here's a full debug log.  Clearing the besu and nimbus dbs and starting from scratch produces the same result.
[nimbus_debug_log.txt](https://github.com/status-im/nimbus-eth2/files/7918982/nimbus_debug_log.txt)

**Comment by tersec** [comment]
The very first `executePayload` attempt fails in waiting for a response from Besu:
```
{"lvl":"DBG","ts":"2022-01-22 12:54:38.149-05:00","msg":"executePayload: inserting block into execution engine","parentHash":"f0c72c6a","blockHash":"fbaebc5d","stateRoot":"9d7e6b69","receiptsRoot":"6c73ff45","random":"ed9fc63c","blockNumber":7052,"gasLimit":8000000,"gasUsed":7904939,"timestamp":1639674528,"extraDataLen":0,"baseFeePerGas":{"data":{"lo":{"lo":7,"hi":0},"hi":{"lo":0,"hi":0}}},"numTransactions":145}
{"lvl":"INF","ts":"2022-01-22 12:54:38.151-05:00","msg":"newExecutionPayload failed","msg":"Transport was closed while waiting for response"}
{"lvl":"DBG","ts":"2022-01-22 12:54:38.151-05:00","msg":"Block pool rejected peer's response","topics":"beacnde","peer":"16U*SRFpjF","request_slot":1218,"request_count":32,"request_step":1,"blocks_map":"xx.xx.xx.x.xxxxx.xxx.xx.........","blocks_count":17,"errCode":1}
```
Why this happens isn't possible to say from the logs you've provided -- one'd have to see the Besu side of things; do you have corresponding logs from Besu where it might have noted its objection?

Since it takes only 2 milliseconds for this to occur, it seems that Besu closed the connection on Nimbus -- there's likely some protocol incompatibility here, which needs further investigation.

**Comment by SeaMonkey82** [comment]
I don't see an option to output logging to a file in besu, so I copied the contents of the tmux buffer with both running.  However, the only references I see to the WebSocketService are at the end when I shut it down, so this might be of no use.  If there's anything more I can do to collect more/better info, please let me know.
[besu_debug_log.txt](https://github.com/status-im/nimbus-eth2/files/7919310/besu_debug_log.txt)

**Comment by garyschulte** [comment]
Besu is using the default vertx websocket frame size of 64kb:
```
2022-02-03 00:12:03.148+00:00 | vert.x-worker-thread-2 | DEBUG | WebSocketRequestHandler | WS-RPC request -> eth_subscribe
2022-02-03 00:12:03.149+00:00 | vert.x-worker-thread-2 | DEBUG | SubscriptionManager | Subscribe request SubscribeRequest{subscriptionType=NEW_BLOCK_HEADERS, includeTransaction=false, filterParameter=null, connectionId=__vertx.ws.18bbd1a6-e539-487c-b1f7-8069dd1e826a}
2022-02-03 00:12:13.418+00:00 | vert.x-eventloop-thread-1 | DEBUG | WebSocketService | Unrecoverable error on Websocket: Max frame length of 65536 has been exceeded. (host=127.0.0.1, port=42694)
2022-02-03 00:12:13.421+00:00 | vert.x-eventloop-thread-1 | DEBUG | WebSocketService | Unrecoverable error on Websocket: Connection was closed (host=127.0.0.1, port=42694)
2022-02-03 00:12:13.421+00:00 | vert.x-eventloop-thread-1 | DEBUG | WebSocketService | Websocket Disconnected (host=127.0.0.1, port=42694)
2022-02-03 00:12:13.424+00:00 | vert.x-eventloop-thread-1 | DEBUG | WebSocketService | Connection closed from 127.0.0.1:42694. Total of active connections: 2/80
...
```

@tersec - what frame size is nimbus using?

**Comment by garyschulte** [comment]
AFAICT, nimbus is using news and the max frame size is 1mb:

https://github.com/Tormund/news/blob/master/src/news.nim#L423

**Comment by tersec** [comment]
I'm not that familiar with this aspect; would that suffice to explain what happened here?

**Comment by garyschulte** [comment]
> I'm not that familiar with this aspect; would that suffice to explain what happened here?

Yes, nimbus was sending messages with a frame size that exceeded 64kb, and that caused besu to disconnect.  After bumping the besu max frame size to 1mb to match the `news` lib, nimbus/besu syncs and operates without any problem.

FWIW, by default besu is now using max frame size of 1mb and max message size of 4mb.

**Comment by tersec** [comment]
Sounds resolved.
