### ISSUE TITLE
Investigate slashing protection import performance with genesis validators

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#3390]
It was reported that loading the slashing protection DB from a genesis validators takes hours.

This is both surprising and not:
- surprising because we use raw SQLite now which should be pretty efficient, especially on SSD
- unsurprising because apparently Lighthouse had to solve that issue: https://github.com/sigp/lighthouse/pull/2347 (the report also came from a Prysm user)

**Comment by Irishgrizz** [comment]
Nice[![image](https://user-images.githubusercontent.com/93418679/155210344-16fd8a26-028a-4246-88ff-dab0d128b432.jpeg)]()

**Comment by zah** [comment]
@mratsim, I believe this issue has been addressed and we can close it, right?

**Comment by Irishgrizz** [comment]
No it hasn't stopped man please help me I'm living out my car for almost 4 months
