### ISSUE TITLE
[make testnetX - MacOS] "go version" is not accepted

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#346]
On MacOS "go version" reports 1.12 instead of 1.12.0.

The "makefile testnet1" does not accept those.

```shell
$  make testnet1
Minimum Go compiler version required: 1.12.0. Version available: 1.12. Aborting.
make[1]: *** [go-checks] Error 1
make: *** [p2pd] Error 2
```
```shell
$  go version
go version go1.12 darwin/amd64
```

**Comment by stefantalpalaru** [comment]
That's weird. How did you install go?

**Comment by mratsim** [comment]
Through Homebrew

**Comment by stefantalpalaru** [comment]
You should be getting "go1.12.8". Did you do anything other than `brew install go`?

Try `brew update; brew upgrade; brew cleanup`.

**Comment by stefantalpalaru** [comment]
Run also `which go`. Is it "/usr/local/bin/go"?

**Comment by mratsim** [comment]
Seems like it was how it was done in brew before (in March).

updating changes the version as expected `go 1.12 -> 1.12.8`
