### ISSUE TITLE
Instrumentation for performance

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#347]
While so far we used several tools for performance profiling like:
- perf
- oprofile
- Apple's Instruments
- Intel VTune

that report a lot of information (call graphs, cumulated time spent in a function, assembly, ...).

Recent research in Coz demonstrated that the cumulated time spent in a function might not indicate a function that should be prioritized for optimization.

Coz is a very simple C library to wrap (COZ_PROGRESS_NAMED, COZ_BEGIN, COZ_END templates from the [header](https://github.com/plasma-umass/coz/blob/master/include/coz.h)) that can profile throughput, latency and expected overall performance gains by optimizing a specific procedure. It has been tested in single-threaded, async and multithreaded applications.

-> https://github.com/plasma-umass/coz

-------

Note: this is distinct from logging and metrics.

**Comment by tersec** [comment]
While Coz isn't incredibly difficult to wrap, it was brought up that should we desire to use a pre-existing wrapper, https://github.com/s0kil/nimcoz exists.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/tree/devel/nbench satisfies this to some extent. It's not Coz, but also might prove enough indefinitely.

**Comment by mratsim** [comment]
Furthermore our performance issues are more linked to sync speed and peer quality and not low-level function calls anymore. Hence closing.
