### ISSUE TITLE
/eth/v2/beacon/blocks returning invalid extra_data

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#3495]
**Describe the bug**

A request to the endpoint `/eth/v2/beacon/blocks` returns the `extra_data` field in an invalid format.

**To Reproduce**

Request a bellatrix block from `/eth/v2/beacon/blocks`, for example:

```
curl -s http://localhost:5052/eth/v2/beacon/blocks/21920 | jq '.data.message.body.execution_payload.extra_data'
[]
```

**Additional context**

This value should be returned as a hex string rather than a byte array.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/3581
