### ISSUE TITLE
Gnosis: Interop issue between Nimbus CL and Lighthouse VC

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nim-beacon-chain#3554]
**Describe the bug**

Nimbus compiled from `unstable` for gnosis-chain, version `Nimbus/v22.3.0-57fc9d-stateofus`

Lighthouse VC connecting to Nimbus. Lighthouse VC shows:

```
Mar 28 16:25:29.083 INFO Connected to beacon node                endpoint: https://gnosis-b.cryptomanufaktur.net/, version: Nimbus/v22.3.0-57fc9d-stateofus
Mar 28 16:25:29.163 ERRO The minimal/mainnet spec type of the beacon node does not match the validator client. See the --network command., endpoint: https://gnosis-b.cryptomanufaktur.net/
```

Could this be because of naming convention? Lighthouse calls it `gnosis`, Nimbus calls it `gnosis-chain`.

Please let me know what additional logs I can get you.

**Comment by stefantalpalaru** [comment]
See also: https://github.com/status-im/nimbus-eth2/pull/3477

**Comment by yorickdowne** [comment]
Am I seeing right that a fix for the issue in 3477 was merged 18 days ago into `unstable`? If so, the issue I encountered here is separate, as it was compiled from `unstable`.

I also do not see this issue on Ethereum mainnet, only on Gnosis.

**Comment by stefantalpalaru** [comment]
No, there is no fix. That's just a local testnet to reproduce and debug the problem.

**Comment by arnetheduck** [comment]
@yorickdowne have you tried this recently? since the release of our own VC, many compatiblity fixes have been made to the BN as well - notably though, you need to be running `nimbus_beacon_node_gnosis` from a source build for gnosis to work correctly

**Comment by yorickdowne** [comment]
It's still unhappy. I can get you debug or trace logs from both, if that helps. Which would you like?

```
eth-docker-devel-validator-1  | Jan 08 11:07:49.642 ERRO The minimal/mainnet spec type of the beacon node does not match the validator client. See the --network command., endpoint: http://consensus:5052/
eth-docker-devel-validator-1  | Jan 08 11:07:49.642 WARN Unable to connect to a beacon node      available: 0, total: 1, retry in: 2 seconds
```

**Comment by arnetheduck** [comment]
A debug log from the VC to start with would be good - hopefully that has enough information - that said, the error message about minimal/mainnet is somewhat concerning since gnosis uses their own spec type

**Comment by arnetheduck** [comment]
Nevermind actually, I found the bug.

**Comment by zah** [comment]
This has been tracked to an issue in the Gnosis network metadata which has been resolved here:
https://github.com/gnosischain/configs/pull/5
https://github.com/status-im/nimbus-eth2/pull/4603
