### ISSUE TITLE
Minor typo in changelog for v22.4.0 . --threads:0 should be --num-threads:0

### ISSUE THREAD

**Issue by jmcpheron** [status-im/nim-beacon-chain#3587]
**Describe the bug**
Not a big deal, but the latest changelog references the command like option `--threads:0` but the correct command line option is `--num-threads:0`. 

[https://github.com/status-im/nimbus-eth2/blob/stable/CHANGELOG.md?plain=1#L8](https://github.com/status-im/nimbus-eth2/blob/stable/CHANGELOG.md?plain=1#L8)

I'm happy to submit a PR, this one would be easy enough for me.

**Comment by tersec** [comment]
Fixed by https://github.com/status-im/nimbus-eth2/pull/3591
