### ISSUE TITLE
Add --jwt-secret to --help

### ISSUE THREAD

**Issue by SeaMonkey82** [status-im/nim-beacon-chain#3603]
**Is your feature request related to a problem? Please describe.**
--help lacks listing/description of the `--jwt-secret` flag

**Describe the solution you'd like**
Add one

**Comment by etan-status** [comment]
This option is currently marked `hidden`, removing it from `--help`.

Description is listed here:
https://github.com/status-im/nimbus-eth2/blob/4e147287eacadb27d5b5792d2ef7b3c21b5ac5a3/beacon_chain/conf.nim#L204-L208

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/3604
