### ISSUE TITLE
Attestation Event stream emits less Attestation than expected

### ISSUE THREAD

**Issue by InvisibleSymbol** [status-im/nim-beacon-chain#3609]
**Describe the bug**
For a project I'm working on I need a constant stream of all Attestations my nodes receives. After enabling `--subscribe-all-subnets`,  this results in around around 900 Attestations/s being received. 
![image](https://user-images.githubusercontent.com/34715248/165634411-0e878083-6719-4c52-ad56-6af8f4c72a32.png)
But `http://nimbus/eth/v1/events?topics=attestation` only emits around 25-50 Attestation/s, seemingly a random sample of all received Attestations. This does not match what Teku does for example (emitting all), nor what I would expect the endpoint to do (a random sample is pretty useless).

**To Reproduce**
You can run this small script to get an Attestation/s count the endpoint emits. requires `pip install sseclient`
```python
from sseclient import SSEClient
from tqdm import tqdm
for _ in tqdm(SSEClient("http://nimbus:5052/eth/v1/events?topics=attestation")):
    pass
```

**Comment by zah** [comment]
A fix for this has been merged in the `unstable` branch and will be shipped in Nimbus v22.6.0
