### ISSUE TITLE
Checkpoint sync doesn't accept `charset` in `content-type` response header

### ISSUE THREAD

**Issue by acolytec3** [status-im/nim-beacon-chain#3624]
**Describe the bug**
The Nimbus client requires that response headers be set to strictly `application/json` without any `charset` specified when trying to parse REST responses during checkpoint sync so is not able to parse responses from the Lodestar client on the Kiln testnet.

**To Reproduce**
1. OS - Ubuntu 22 running on `AMD64` platform
2. Branch/commit used: `kiln-auth-dev`
3. Commands being executed: `build/nimbus_beacon_node trustedNodeSync --trusted-node-url=https://lodestar-kiln.chainsafe.io --network=vendor/merge-testnets/kiln --web3-url=ws://127.0.0.1:8551 --log-level=DEBUG  --jwt-secret="/home/jim/development/ethjs/packages/client/kiln/datadir/jwtsecret" --data-dir=build/kiln`
4. Relevant log lines: 
```
NOT 2022-05-09 15:56:40.867-04:00 Starting trusted node sync                 databaseDir=build/kiln/db restUrl=https://lodestar-kiln.chainsafe.io blockId=finalized backfill=true reindex=false
DBG 2022-05-09 15:56:41.146-04:00 Sending REST request to remote server      remote=lodestar-kiln.chainsafe.io:443 request=/eth/v1/beacon/blocks/genesis/root http_method=GET
DBG 2022-05-09 15:56:41.399-04:00 Got REST response headers from remote server status=200 http_method=GET remote=lodestar-kiln.chainsafe.io:443 request=/eth/v1/beacon/blocks/genesis/root connection=1
DBG 2022-05-09 15:56:41.399-04:00 Received REST response body from remote server status=200 http_method=GET remote=lodestar-kiln.chainsafe.io:443 request=/eth/v1/beacon/blocks/genesis/root connection=1 contentType="application/json; charset=utf-8" size=77
ERR 2022-05-09 15:56:41.399-04:00 Unable to download genesis block root      error="Unable to decode REST response, error [Content-Type not supported]" restUrl=https://lodestar-kiln.chainsafe.io
```

**Comment by zah** [comment]
This issue was addressed by the linked PR above and the fixes have been shipped in Nimbus v22.8.0
