### ISSUE TITLE
Continuous Integration time

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#364]
Running the CI gets longer.

Issues to track:
- compile-time
- runtime

Note that Compilation/Runtime is done once per preset (minimal, mainnet at the moment)

Potential culprits:

- state_sim constants tuning (Epochs/Slots)
- the nested templates expansion of suite/test/check in `unittest` might be an issue

Potential fixes "without doing anything"
- Incremental Compilation

**Comment by stefantalpalaru** [comment]
Immediate runtime reduction: change the number of slots for the `state_sim` from 140 to the minimum needed to reach the desired number of epochs.

**Comment by tersec** [comment]
> Immediate runtime reduction: change the number of slots for the `state_sim` from 140 to the minimum needed to reach the desired number of epochs.

It should reach into the 3rd epoch (epoch number 2).

**Comment by arnetheduck** [comment]
can easily compile `state_sim` with minimal configuration/shorter epochs for the test

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/595 helps here.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/597 cuts another minute or two so off the default configuration.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/726 should help somewhat.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/issues/364

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/1198

**Comment by tersec** [comment]
We've been addressing this in an ongoing way as it's come up as a more specific issue.
