### ISSUE TITLE
Beacon API Spec Conformance

### ISSUE THREAD

**Issue by z3n-chada** [status-im/nim-beacon-chain#3666]
**Describe the bug**
Conformance issue in json-rpc responses for the beacon_node.

**To Reproduce**
use the following endpoints:
| API Path                                              | Inputs | Issue                         |
|:----------------------------------------------------- |:------ |:----------------------------- |
| /eth/v1/beacon/states/(state)/root                    | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/fork                 | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/finality_checkpoints | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/validators           | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/committees           | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/sync_committees      | "head" | No execution_optimistic field |
| /eth/v1/beacon/headers                                | "head" | No execution_optimistic field |
| /eth/v2/beacon/blocks/{block_id}                      | "head" | No execution_optimistic field, wrong decoding of baseFeePerGas |
| /eth/v1/node/syncing                                  | None   | No is_optimistic field        |

**Screenshots**

**Additional context**
running on kiln-dev-auth

**Comment by zah** [comment]
Reference information for the `execution_optimistic` flag:
https://github.com/ethereum/beacon-APIs/pull/190

Implementations in Lighthouse and Teku:
https://github.com/sigp/lighthouse/issues/3031
https://github.com/ConsenSys/teku/issues/4968

**Comment by zah** [comment]
Addressed by https://github.com/status-im/nimbus-eth2/pull/3780 and https://github.com/status-im/nimbus-eth2/pull/3679. The corresponding fixes have been shipped in Nimbus `22.6.0`
