### ISSUE TITLE
Fix ValidatorIndex type

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#367]
currently it's a range, and the compiler has several range-related bugs. let's keep it simple and use a.. something (`uint64`?)

https://github.com/status-im/nim-beacon-chain/blob/9cfc153620f91c620f8605aedae44baffb091a78/beacon_chain/spec/datatypes.nim#L76

**Comment by mratsim** [comment]
in the future I'd rather use int64 everywhere except maybe for epochs due to "FAR_FUTURE_EPOCH".

**Comment by zah** [comment]
Implemented in https://github.com/status-im/nim-beacon-chain/pull/473
