### ISSUE TITLE
VC: implement doppelganger protection

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#3683]
`--doppelganger-detection` missing from VC

85d023452494b348033be85033317ebd22799980

**Comment by cheatfate** [comment]
I think commit which you put there in the issue is wrong.

**Comment by arnetheduck** [comment]
> I think commit which you put there in the issue is wrong.

looks right to me? ie it's part of `stable`, which I was testing with

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/3877
