### ISSUE TITLE
Prevent running multple BN:s and VC:s from the same data directory

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#3686]
This will cause keys to be loaded by both VC and BN resulting in high slashing risk (ie the slashing DB _may_ prevent it, but it's not certain)

This is specially true in the case of a VC and BN sharing data directory.

**Comment by cheatfate** [comment]
This is not only VC problem, it is also problem of BN itself.

**Comment by arnetheduck** [comment]
#3080 suggests one approach

It's indeed a problem both for VC:s and BN:s, though with the VC, it's very easy to put in the same data dir in the two processes by accident or misunderstanding.

**Comment by zah** [comment]
This was fixed in the v22.8.0 release through the addition of keystore locking.
