### ISSUE TITLE
Hard to track slashings

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-beacon-chain#3688]
From: https://github.com/status-im/infra-docs/blob/master/docs/postmortems/20220526_prater_validator_slashing.md

We got slashed on the testfleet for 24 days before someone pinged us to notify us
We don't really have metrics, or alarms setup to detect issues faster

**Comment by arnetheduck** [comment]
Slashings are covered by the validator monitoring which provides metrics for this - it's a matter of getting it set up for the testnet fleet (which was set up before the vmon feature was available): https://github.com/status-im/nimbus-eth2/blob/09663e00d87c0d3f43519c6073d27d2653f69b53/beacon_chain/validators/validator_monitor.nim#L36

See validator monitor tab on: https://metrics.status.im/d/pgeNfj2Wz23/nimbus-fleet-testnets?orgId=1&var-instance=metal-05.he-eu-hel1.nimbus.prater&var-container=beacon-node-prater-unstable&from=now-2d&to=now&refresh=15m - what's missing is alerting.

cc @jakubgs

**Comment by Menduist** [comment]
Missing documentation then :)

**Comment by jakubgs** [comment]
Is there any other metrics aside from `validator_monitor_slashed` we should be alerting on?
```
admin@metal-02.he-eu-hel1.nimbus.prater:~ % c 0:9201/metrics | grep validator_monitor_slashed
# HELP validator_monitor_slashed Set to 1 if the validator is slashed.
# TYPE validator_monitor_slashed gauge
```
Also, shouldn't this have a possible value higher than one, since we can run multiple validators?

**Comment by Menduist** [comment]
You can have one per validator:
```
$ curl -s 127.0.0.1:9202/metrics | grep validator_monitor_slashed
# HELP validator_monitor_slashed Set to 1 if the validator is slashed.
# TYPE validator_monitor_slashed gauge
validator_monitor_slashed{validator="94b98aba"} 0.0
validator_monitor_slashed_created{validator="94b98aba"} 1654016624.0
etc
```

**Comment by jakubgs** [comment]
Yeah, I see now, it does indicate which validator is slashed with the beginning of its public key:

![image](https://user-images.githubusercontent.com/2212681/171381256-d6388c2c-c8b3-471a-8567-95990c0fca4e.png)

But this means we have to remove the slashed validators or the monitoring will be constantly in alert.

**Comment by Menduist** [comment]
Is this the full results? Cause we should have >1600, not <100

**Comment by jakubgs** [comment]
Not all nodes had monitoring enabled, only `unstable` ones, which was changed today in https://github.com/status-im/infra-nimbus/commit/3366cd40.

**Comment by jakubgs** [comment]
The current full number is 2877 validators slashed:

![image](https://user-images.githubusercontent.com/2212681/171391544-e1a4e628-ae10-4cd3-b127-e58b68ebce69.png)

I will have to move/archive slashed validators in `nimbus-private` repo and re-deploy a new layout without any slashed ones.
