### ISSUE TITLE
`base_fee_per_gas` wrong format in API

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#3697]
**Describe the bug**

The `base_fee_per_gas` value in `ExecutionPayload` is being returned as a hex string rather than an integer.

**To Reproduce**
```
# curl -s -H 'Accept: application/json' http://localhost:xxxx/eth/v2/beacon/blocks/26000 | jq -r '.data.message.body.execution_payload.base_fee_per_gas'
0x0000000000000000000000000000000000000000000000000000000000000000
```

The [specification](https://github.com/ethereum/consensus-specs/blob/v1.1.9/specs/bellatrix/beacon-chain.md#executionpayload) states that `base_fee_per_gas` is a `uint256`, which is should be returned as a quoted integer.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/3679 (already merged) should fix this.
