### ISSUE TITLE
Nimbus Bad Block Behaviour for EL Node Edge Cases

### ISSUE THREAD

**Issue by z3n-chada** [status-im/nim-beacon-chain#3708]
**Describe the bug**
In some cases where the nimbus node is unable to communicate with an el client right at the merge nimbus nodes will produce and propose bad blocks. This leads to a chain split on those nodes.

**To Reproduce**
1. Platform details : platform agnostic
2. Branch/commit used: nimbus-kiln-dev-auth (besu pairing)
3. Commands being executed: 
4. Relevant log lines: full logs submitted to @tersec more available upon request.

**Screenshots**

**Additional context**
This occurs at least in the case where we get an unauthorized response from a EL client. Not sure of the conditions yet that must be satisfied for this behavior. The invalid blocks are related to the execution-payload-header:
```
parent_hash    "0x0000000000000000000000…00000000000000000000000"
fee_recipient    "0x0000000000000000000000000000000000000000"
state_root    "0x0000000000000000000000…00000000000000000000000"
receipts_root    "0x0000000000000000000000…00000000000000000000000"
logs_bloom    "0x0000000000000000000000…00000000000000000000000"
prev_randao    "0x0000000000000000000000…00000000000000000000000"
block_number    "0"
gas_limit    "0"
gas_used    "0"
timestamp    "0"
extra_data    "0x"
base_fee_per_gas    "0x0000000000000000000000…00000000000000000000000"
block_hash    "0x0000000000000000000000…00000000000000000000000"
transactions_root    "0x0000000000000000000000…00000000000000000000000"
```
This eventually leads to only other nimbus nodes exhibiting this behavior to form up on fork.

**Comment by tersec** [comment]
The websocket web3 connection used in the setup logged managed to hit both https://github.com/hyperledger/besu/issues/3796 and https://github.com/hyperledger/besu/issues/3854 and was effectively detached from the testnet.

**Comment by zah** [comment]
@tersec, does this mean that there is no issue on Nimbus's side and we can close this?

**Comment by tersec** [comment]
Yes, this particular one isn't really a bug as such, or, well, not a per-se merge bug. It's because Nimbus wasn't seeing any input from Besu due to incompatibilities, and just proceeded as if not-merge, and that means all-zero execution payloads as shown.
