### ISSUE TITLE
Add option to disable state pruning

### ISSUE THREAD

**Issue by RomiRand** [status-im/nim-beacon-chain#3714]
**Is your feature request related to a problem? Please describe.**
- I'm helping the beaconcha.in guys by looking into support for additional consensus clients for their backend (for diversity reasons). After prysm stopped working for them they switched to lighthouse. I would love to see nimbus as another option, but it's not supported because state pruning can't be disabled at the moment. That's fine for most users of course, but block explorers like beaconcha.in and others could benefit from this.
@arnetheduck asked me to include some calls/usage patterns, so I extracted a short request flow from their backend into this script as an example. It's called for every epoch initially to fill their db.
```python
import requests
import json

url = "http://my-nimbus-node:port"

def GetSyncCommittee(epoch):
    dependent_root = json.loads(requests.get(url + "/eth/v1/validator/duties/proposer/" + str(epoch)).content)["dependent_root"]
    state_root = json.loads(requests.get(url + "/eth/v1/beacon/headers/" + dependent_root).content)["data"]["header"]["message"]["state_root"]
    print(requests.get(url + "/eth/v1/beacon/states/" + state_root + "/sync_committees?epoch=" + str(epoch)).content)
```
The first call fails with `Trying to access a pruned historical state`.
- An argument could be made that nimbus isn't capable of fulfilling the entire beacon node api with the correct responses. Requesting old state information just returns an error message instead of the correct data.

**Describe the solution you'd like**
Nimbus should have an option to disable state pruning. I'm new to this so I'm not sure how this could be done most effectively (sorry). I think lighthouse just stores a state snapshot every n (configurable) epochs and recomputes the requested data from the nearest snapshot. Imo that's a great way to let the user configure a trade-off between disk space and computation time. I'm sure there are many more decisions like this involved to implement it efficiently.

Please note that I don't really have any experience with client development. LMK if I'm missing something, maybe there's another solution to my problem.

**Comment by etan-status** [comment]
Nimbus currently requires historic states to be requested by `slot` instead of by `root`.

**Comment by arnetheduck** [comment]
> Nimbus should have an option to disable state pruning.

Indeed, as @etan-status points out, the above request can significantly be simplified simply by requesting `/eth/v1/beacon/states/<slot>/...` - there is no need to load state root and then load states via state root - in fact, it is strictly worse because it introduces additional round-trips which put load on the server _and_ make the fetching a lot slower (by virtue of making 3 requests instead of 1).

There is no need for state pruning options to support this - nimbus however has a rest cache ttl option that can be used to speed up the process at the expense of memory - see `--rest-cache-ttl` in particular.

**Comment by arnetheduck** [comment]
Nimbus generally does not index state roots at all as these have little value / there are very few uses where they are better suited than simply using the slot number - this would be a feature to bring up with beaconcha.in - if they are unable to change their approach, we can consider creating a state root index for this sole purpose.

**Comment by RomiRand** [comment]
Okay thanks for the information. I understand this isn't really needed, feel free to close the issue.

> Nimbus generally does not index state roots at all as these have little value / there are very few uses where they are better suited than simply using the slot number - this would be a feature to bring up with beaconcha.in - if they are unable to change their approach, we can consider creating a state root index for this sole purpose.

Makes sense, I will check if this can be optimized. If necessary I'll come back to you.

**Comment by arnetheduck** [comment]
@RomiRand were you able to look into the API usage?

**Comment by arnetheduck** [comment]
>  If necessary I'll come back to you.

assuming we're fine here.
