### ISSUE TITLE
Cannot have a zeroed Signature

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#374]
The spec relies on zero signature in process_block_header: https://github.com/ethereum/eth2.0-specs/blob/v0.8.3/specs/core/0_beacon-chain.md#block-header.

which we diligently copied in our implementation: https://github.com/status-im/nim-beacon-chain/blob/297e9079d47f6070e06f425e8999eb46546029c8/beacon_chain/spec/state_transition_block.nim#L60-L67

However we can't have zero signatures:

```Nim
import
  ../beacon_chain/spec/[crypto, datatypes],
  typetraits,
  blscurve

let x = BeaconBlockHeader()

echo x.signature.blsValue.type.name
echo x.signature.blsValue
echo x.signature.blsValue.getBytes
```
```
Signature
c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Comment by mratsim** [comment]
Actually already raised here: https://github.com/ethereum/eth2.0-tests/issues/27.

It doesn't participate in hash_tree_root, isn't serialized or later so a workaround in the test vectors should be enough.

**Comment by mratsim** [comment]
Very annoying for https://github.com/status-im/nim-beacon-chain/pull/375
as 3 tests fail due to needing to build on the workaround.

**Comment by mratsim** [comment]
upstreamed: https://github.com/ethereum/eth2.0-specs/issues/1396

**Comment by arnetheduck** [comment]
see `BlsValue` in code
