### ISSUE TITLE
Nimbus unexpectedly normalizes web3 RPC URLs

### ISSUE THREAD

**Issue by mandrigin** [status-im/nim-beacon-chain#3756]
**Describe the bug**
I run Nimbus with `--web3-url=http://gateway.fm/ethereum/mainnet?apiKey=MyCaseSensitiveToKeN`

The requests I get on the gateway load balancer side have the URLs lowercased: `--web3-url=http://gateway.fm/ethereum/mainnet?apiKey=mycasesensitivetoken`.
That causes Nimbus to get 401 because tokens are case-sensitive.

At least in Teku & Prysm there is no problem with that.

**To Reproduce**
1. Platform details (OS, architecture): Linux x64, Docker container, official image: `statusim/nimbus-eth2:amd64-latest`
2. Branch/commit used: release `v22.5.2`3. 
3. add `--web3-url` parameter with a http url with the mix of capital and small letters
4. observe on the receiving side that all letters in the url are small.

**Comment by narimiran** [comment]
It looks like [this function](https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/eth1/eth1_monitor.nim#L261) is normalizing URLs by converting them to lowercase.

**Comment by zah** [comment]
Addressed in the merged PR above. The fix will be generally available in the upcoming 22.6.0 release.
