### ISSUE TITLE
Add support for Personal Package Archive (PPA) installation of Nimbus

### ISSUE THREAD

**Issue by superphiz** [status-im/nim-beacon-chain#3782]
**Is your feature request related to a problem? Please describe.**

Current installation methods require the user to go to an external source to install nimbus rather than using a package system like apt available in Ubuntu.

**Describe the solution you'd like**

 Ethereum maintains a PPA and geth is currently most-easily installed using this method. If other clients adopt the PPA installation method it will significantly reduce the effort required to install a Consensus client and enable people with limited technical ability to quickly and easily upgrade their consensus client using standard apt repositories.

**Describe alternatives you've considered**

**Additional context**

**Comment by arnetheduck** [comment]
An experimental x86_64 package of 22.6.1 is available for testing from https://paste.c-net.org/CardsDripping

**Comment by arnetheduck** [comment]
Debian packages now available from https://apt.status.im/ - installation is as simple as `apt install nimbus-beacon-node`! https://nimbus.guide/binaries.html contains more details.
