### ISSUE TITLE
LFS - don't pull large test files by default

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#384]
Prompt by #383, it's very easy to forget to `export GIT_LFS_SKIP_SMUDGE=1` before cloning the repo which means lots of test data downloaded for naught for non-nimbus developers.

Apparently git lfs (but not git) can read .gitconfig within the repo:

- https://github.com/git-lfs/git-lfs/issues/2717
- https://github.com/git-lfs/git-lfs/issues/227

**Comment by tersec** [comment]
Is this resolved/fixed by https://github.com/status-im/nim-beacon-chain/pull/514 ?
