### ISSUE TITLE
"Local network simulation" after some change 

### ISSUE THREAD

**Issue by zsharifian** [status-im/nim-beacon-chain#3873]
Hi
I am beginner and I want use "Local network simulation" feature of your project. I have 2 questions:
1: Does your project concern delays between clients and I can change them?
2. I am a student and I should change some part of consensus protocol of beacon and test the effect of it. so I should simulate after some changes. can I simulate it (after changes) directly from IntelliJ IDEA in Window (I have not Linux or … and I should do my work in win)? If yes, can you help me that what form do I need to run to enable local simulation mode (and not single node or network connection mode)?

Thanks

**Comment by zah** [comment]
You'll need to be proficient in shell scripting and Nim in order to change aspects of the simulation. Working on Windows is possible, as long as you follow the instructions provided here:

https://nimbus.guide/developers.html

**Comment by zsharifian** [comment]
Thanks so much
