### ISSUE TITLE
Nimbus 22.7.0 does not work with Lighthouse VC on Goerli

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nim-beacon-chain#3930]
**Describe the bug**

Nimbus 22.7.0 does not return field `is_optimistic` ahead of Goerli merge, causing Lighthouse VC 2.5.0 to fail to connect to it. 

```
Aug 01 12:07:11.037 INFO Connected to beacon node                endpoint: https://prater.example.com/, version: Nimbus/v22.7.0-75ccfc-stateofus

Aug 01 12:07:11.108 WARN Unable connect to beacon node           error: Reqwest(reqwest::Error { kind: Decode, source: Error("missing field `is_optimistic`", line: 1, column: 70) })
```

**Comment by macladson** [comment]
FYI, we do intend to support BNs which do not provide the `is_optimistic` field. We have an open PR for this at https://github.com/sigp/lighthouse/pull/3410.

**Comment by yorickdowne** [comment]
Fixed by Lighthouse

**Comment by zah** [comment]
For more clarity, the Nimbus implementation is strict in the sense that the `is_optimistic` field is added to response only after the Bellatrix fork epoch is reached on the network. It is indeed appropriate for other client to not require this field prior to this.
