### ISSUE TITLE
Flag to define headers in engine API requests

### ISSUE THREAD

**Issue by pablomendezroyo** [status-im/nim-beacon-chain#3933]
**Is your feature request related to a problem? Please describe.**

With the upcoming merge, 1 EL node cannot receive the head chain from multiple CL nodes due to subjectivity. For this reason, makes sense to look for ways to restrict the use of the engine API in the EL, so it is used by one CL at a time.

**Describe the solution you'd like**

In addition to the `auth-token` would be nice to add headers to the EL endpoint (`--web3-url`) requests, to indicate the Host who is requesting. This could be used in conjunction with the host whitelist in Geth `--authrpc.vhosts value`, see [geth docs](https://geth.ethereum.org/docs/interface/command-line-options).

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by zah** [comment]
The meaning of the `Host` header in the HTTP specification is to indicate which server is meant to be reached (on an IP address hosting multiple servers or web sites):

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

It doesn't indicate the host making the request.
