### ISSUE TITLE
Migrate to the latest version of the Engine API spec

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#3935]
We need to review the recent changes introduced in the Engine API (one example is the inclusion of the `safeBlockHash` field in the fork-choice update call).

Some relevant spec PRs:
https://github.com/ethereum/consensus-specs/pull/2851
https://github.com/ethereum/consensus-specs/pull/2858
https://github.com/ethereum/consensus-specs/pull/2876

**Comment by tersec** [comment]
I'm not sure if there's anything remaining to be done here:
- those are not engine API calls, but consensus spec changes
- https://github.com/status-im/nimbus-eth2/pull/4010 addresses https://github.com/ethereum/consensus-specs/pull/2851 and https://github.com/ethereum/consensus-specs/pull/2858
- https://github.com/ethereum/consensus-specs/pull/2876 is part of an abstract aspect of the consensus spec, where it's not especially crucial it matches any particular implementation exactly, so long as it does handle the safe block hash properly
- https://github.com/status-im/nimbus-eth2/pull/4030 does the minor update from the engine API (proper) alpha.9 to beta.1.

**Comment by zah** [comment]
Indeed, these improvements have been shipped in Nimbus v22.8.1
