### ISSUE TITLE
Implement the Capella beacon chain spec

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#3942]
The Capella beacon chain spec changes are defined here:
https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#introduction

As a first step, we should implement the Capella state transition in expectation of test vectors that might be published in the future. The task will include the following:

1) Define a new `capella` module in the `beacon_chain/spec/datatypes` folder. The module will hold the new definitions for types such as `ExecutionPayload`, `BeaconBlockBody`, `BeaconState`, etc, as well as the brand new types such as `Withdrawal` and `BLSToExecutionChange`.

2) Extend the `BeaconStateFork` enum with additional `Capella` value and handle the fallout from the change.

3) Introduce the modifications to the state transition functions (as done for previous forks such as Altair and Bellatrix). All existing code should continue to compile normally (i.e. `make` and `make test` should complete successfully). `block_sim` can be extended to test Capella transitions.

**Comment by tavurth** [comment]
From this task I guess I'm more than half way through (3), compile times are getting close to the unmodified repo compile times. However it's quite hard to understand how far along I am as there is no percentage counter 🤔 

In general (2 Fallout from the change) has been pretty massive.

**Comment by tavurth** [comment]
Add [migration process overview](https://github.com/status-im/nimbus-eth2/blob/feature/capella/beacon_chain/spec/datatypes/migration.md)

**Comment by tersec** [comment]
Done, shipping.
