### ISSUE TITLE
Metrics for Web3 request responses

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#3950]
**Is your feature request related to a problem? Please describe.**
It's difficult to figure out issues related to the Web3 endpoint, also known as Engine API, also known as Auth RPC, also probably known by other names. It would be much easier to debug this if we had metrics that indicate what responses we are getting from the endpont.

**Describe the solution you'd like**
A metric like this would make issues with the engine API endpoint much simpler to debug:
```
# HELP beacon_node_web3_request_responses The total number of requests batch appends sent to web3 endpoints.
# TYPE beacon_node_web3_request_responses counter
beacon_node_web3_request_responses{target="http://10.10.0.35:8551",status="200",type="runForkchoiceUpdated"} 685
beacon_node_web3_request_responses{target="http://10.10.0.35:8551",status="429",type="runForkchoiceUpdated"} 2
beacon_node_web3_request_responses{target="http://10.10.0.35:8551",status="502",type="runForkchoiceUpdated"} 29
beacon_node_web3_request_responses{target="http://10.10.0.35:8551",status="200",type="getBlockByHash"} 254309
beacon_node_web3_request_responses{target="http://10.10.0.35:8551",status="429",type="getBlockByHash"} 321
beacon_node_web3_request_responses{target="http://10.10.0.35:8551",status="502",type="getBlockByHash"} 92
beacon_node_web3_request_responses{target="http://10.10.0.27:8551",status="200",type="getBlockByHash"} 932191
beacon_node_web3_request_responses{target="http://10.10.0.27:8551",status="403",type="getBlockByHash"} 28
beacon_node_web3_request_responses{target="http://10.10.0.29:8551",status="timeout",type="getBlockByHash"} 299221

```
The inclusion of `type`(or `method`) label isn't absolutely necessary, but would be neat.
The most critical thing is really knowing which web3 endpoint is returns what codes to understand what's the issue.

The added benefit is that you can also tell which endpoint out of the configured ones is actively being used.

**Comment by jakubgs** [comment]
This is related to, and an alternative or additional solution to:

* https://github.com/status-im/nimbus-eth2/issues/4000

**Comment by zah** [comment]
The following new metrics have been added:

```nim
declareCounter engine_api_responses,
  "Number of successful requests to the newPayload Engine API end-point",
  labels = ["url", "request", "status"]

declareCounter engine_api_timeouts,
  "Number of timed-out requests to Engine API end-point",
  labels = ["url", "request"]

declareCounter engine_api_last_minute_forkchoice_updates_sent,
  "Number of last minute requests to the forkchoiceUpdated Engine API end-point just before block proposals",
  labels = ["url"]
```

The first two should be self-explanatory. The last one measures a fallback code path that we don't want to be triggered frequently.

**Comment by jakubgs** [comment]
Looking good:
```
admin@linux-02.he-eu-hel1.nimbus.prater:~ % c http://10.14.0.70:9202/metrics | grep engine_api_responses
# HELP engine_api_responses Number of successful requests to the newPayload Engine API end-point
# TYPE engine_api_responses counter
engine_api_responses_total{url="http://localhost:8554",request="newPayload",status="200"} 50.0
engine_api_responses_created{url="http://localhost:8554",request="newPayload",status="200"} 1678187950.0
engine_api_responses_total{url="http://localhost:8554",request="forkchoiceUpdated",status="200"} 50.0
engine_api_responses_created{url="http://localhost:8554",request="forkchoiceUpdated",status="200"} 1678187951.0
```

**Comment by jakubgs** [comment]
What would be even more amazing is a latency histogram for those. But this is great already.

**Comment by jakubgs** [comment]
Nice:

![image](https://user-images.githubusercontent.com/2212681/223411753-1ac39d0b-e789-4a5c-8fac-a7065505dbd2.png)

**Comment by zah** [comment]
OK, great, it would be easy to add latency.

**Comment by jakubgs** [comment]
Just to test this I restarted the Geth node to see what would happen:

![image](https://user-images.githubusercontent.com/2212681/223413248-5e8a1132-3735-4ce3-ba32-effbb80bdf7b.png)

And we can clearly see some failed requests to the EL node. Nice.

**Comment by jakubgs** [comment]
But for some reason I don't see any metrics in `engine_api_timeouts`:
```
admin@linux-02.he-eu-hel1.nimbus.prater:~ % c http://10.14.0.70:9202/metrics | grep engine_api_timeouts
# HELP engine_api_timeouts Number of timed-out requests to Engine API end-point
# TYPE engine_api_timeouts counter
admin@linux-02.he-eu-hel1.nimbus.prater:~ % 
```
Could it be that the Geth node wasn't down long enough?

**Comment by zah** [comment]
A histogram for the response times was added in https://github.com/status-im/nimbus-eth2/pull/4707 (as well as quite a lot of additional new metrics for tracking other request types besides `newPayload` and `forkchoiceUpdated`)

**Comment by jakubgs** [comment]
Also related:

* https://github.com/status-im/nimbus-eth2/pull/4707

**Comment by jakubgs** [comment]
Pretty cool:

#### `linux-04.he-eu-hel1.nimbus.prater`

![image](https://user-images.githubusercontent.com/2212681/224184997-bf753752-bb67-4c19-afdc-6d632980df54.png)

#### `linux-05.he-eu-hel1.nimbus.prater`

![image](https://user-images.githubusercontent.com/2212681/224184972-82c4473b-4cca-4769-ae91-ed27b000a952.png)

#### `linux-06.he-eu-hel1.nimbus.prater`

![image](https://user-images.githubusercontent.com/2212681/224184982-1a87903e-cc38-4aec-ab5a-f9742fac080f.png)

---

Here we can clearly see that the more validators you have the more strained the EL node is.

**Comment by jakubgs** [comment]
Request graphs are also neat:

![image](https://user-images.githubusercontent.com/2212681/224185343-36c96828-98c3-4073-84a4-c5f4af92b966.png)

I think we can close this.
