### ISSUE TITLE
Sync progress should distinguish between optmistic and real progress

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#3963]
```
INF 2022-08-12 16:40:24.163+02:00 Slot start                                 topics="beacnde" slot=3650602 epoch=114081 sync="00h00m (99.99%) 6.5529slots/s (RPQQQQQQQQ:3650367)" peers=35 head=85f92e16:3650389 finalized=114072:cf9d2bd5 delay=163ms932us33ns
```

Here, we see `sync=...` showing progress making it appear that we will be synced soon, but what's really happening is that the blocks are optimistic. Instead, if optimistic sync is happening, it should be spelled out somehow (`sync="opt 00h:00m..."` for example)

**Comment by arnetheduck** [comment]
ideally we would also show eth1 progress here, when opt-synced (so as to give an estimate when duties will resume)

**Comment by tersec** [comment]
> ideally we would also show eth1 progress here, when opt-synced (so as to give an estimate when duties will resume)

Perhaps, but that's also a distinct issue, and the issue as opened has been addressed. There are thornier issues with that, in general. It's reasonable to continue to discuss those in this issue or to open another issue for that, but either way, closing.
