### ISSUE TITLE
Continue attesting when web3 goes down

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#3969]
When the connection to the web3 server is lost, it remains possible and valid to keep voting for the last known head for some time (1 epoch? up to 2?) - using an old head/target/source still nets a rewards and remains a valid vote.

Ditto when syncing: after optimistic sync, it's sufficient that the execution layer confirms any block within the last 1-2 epochs to start attesting to _that_ block.

**Comment by zah** [comment]
What's preventing attesting at the moment? Isn't this entirely a function of the current head block stored in the DAG?

**Comment by arnetheduck** [comment]
if we're optimistically synced, we stop attesting completely which is correct (we should not attest to a head that the EL has not fully verified) but also overprotective - what happens, either during upgrades to the el or glitches, is that the EL goes out of sync for a few slots then comes back online - in those cases, we could continue attesting to the _latest_ block that the EL verified before going out of sync.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/5313
