### ISSUE TITLE
Build Fails on v22.7.0

### ISSUE THREAD

**Issue by joesixpack** [status-im/nim-beacon-chain#3992]
```
exec /home/user/entry_point.sh: permission denied
make: *** [Makefile:694: dist-amd64] Error 1
```

**Comment by arnetheduck** [comment]
This looks like a docket setup issue - can you post some more information about how exactly you're trying to build?

**Comment by joesixpack** [comment]
Followed the official guide.

**Comment by arnetheduck** [comment]
Can you proved a bit more information? Which guide? what commands did you run? what version were you using?

**Comment by arnetheduck** [comment]
closing for now since we're unable to reproduce without further information - do reopen if you find time to try  this again.
