### ISSUE TITLE
Potential incorrect serialization of  bls pub key

### ISSUE THREAD

**Issue by djrtwo** [status-im/nim-beacon-chain#4]
# Issue
_Note:_ I'm looking at Nim for the first time so this might just be incorrect.

The following defines a `BLSPubKey` which is used in the `ValidatorRecord` type definition
https://github.com/status-im/nim-beacon-chain/blob/ca4082b316689c8702dc8ba665611de31e3a92cf/beacon_chain/datatypes.nim#L63-L65

I believe that when you serialize `BLSPubKey` with SSZ that you will get a length prefix in the byte output. Because the length is known, we will likely use `int384` or `bytes48`. Both of these types will _not_ require a length prefix when serialized with SSZ.

_EDIT_
It looks like the items in this `aggregateSig` will suffer the same fate.
https://github.com/status-im/nim-beacon-chain/blob/ca4082b316689c8702dc8ba665611de31e3a92cf/beacon_chain/datatypes.nim#L77

Note, that while using the length of the `BLSPubKey` works for the bn256 curve for aggregate sig, if we use BLS12-381, the signatures are not the same length as the pub keys. One is 48bytes while the other is 96bytes (depending on if you G1 or G2 for the key).

**Comment by mratsim** [comment]
Yeah it was just a stub :), I'm fixing it while adding the real BLS aggregate sig
