### ISSUE TITLE
Outdated makeBlock usage in unittest (and state_sim?)

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#402]
While working on #399/#400, I realise that the usage of makeBlock in the old unittest was outdated but somehow tests were passing in the past.

Snippets:

Current situation
https://github.com/status-im/nim-beacon-chain/blob/1c4d145f26513eeddb61f5218db392b7976004d4/tests/test_state_transition.nim#L35-L46

Corrected code:
```Nim
  test "Passes from genesis state, empty block" & preset():
    var
      state = genesisState
      prev_block_header = state.latest_block_header

    prev_block_header.state_root = state.hash_tree_root() # this assumes genesis, i.e. parent_root == ZERO_HASH
    let previous_block_root = prev_block_header.signing_root()
    let new_block = makeBlock(state, previous_block_root, BeaconBlockBody())

    let block_ok = state_transition(state, new_block, {})

    check:
      block_ok

      state.slot == genesisState.slot + 1
```

The changes from https://github.com/status-im/nim-beacon-chain/pull/399/commits/e58eb57b90b70aeec0e1c321419530e2ab2c6c27 triggered several failures in the test_state_transition unittest due to that outdated usage.

**Comment by mratsim** [comment]
Tests deactivated in d74cd9d / #406

**Comment by arnetheduck** [comment]
This is either obsolete or fixed
