### ISSUE TITLE
Investigate reported cases of slow block production

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#4022]
It has been reported that under specific circumstances, Nimbus may take up to 4 seconds to produce a block on low-powered devices such as the Raspberry Pi.

**Comment by tersec** [comment]
This is in process, but due to the nature of block proposals, it's unclear exactly when more information will emerge.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4184 should address around 1/3 or more of this issue.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4186 addresses more of this issue (@arnetheduck measured this to be around 500ms or even more sometimes)

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4185 addresses yet more of it

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4196 part of this

**Comment by arnetheduck** [comment]
Fixed with above PR:s
