### ISSUE TITLE
Implement the liveness failsafe in the Builder API (a.k.a the circuit breaker)

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#4033]
The specifications is available here:
https://github.com/ethereum/builder-specs/pull/47/files

**Comment by tersec** [comment]
It's not yet a specification, but a proposed specification.

**Comment by zah** [comment]
As far as I know all other clients are working on an implementation though (or have already completed it).

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4746
