### ISSUE TITLE
nimbus.guide: .service file in path

### ISSUE THREAD

**Issue by MaxKaay** [status-im/nim-beacon-chain#4035]
**Describe the bug**
On step 2 on the systemd setup it directs to an old service file. https://nimbus.guide/beacon-node-systemd.html

**To Reproduce**
1. Go to https://nimbus.guide/beacon-node-systemd.html
2. Check step 2
3. Link and code snippet are outdated
![image](https://user-images.githubusercontent.com/45236782/186897475-2281e6d7-e4b0-49a1-a33e-73078b2d66d5.png)

correct raw .service file can be found here: 
https://raw.githubusercontent.com/status-im/nimbus-eth2/stable/scripts/package_src/nimbus_beacon_node/image/lib/systemd/system/nimbus_beacon_node.service

**Comment by arnetheduck** [comment]
thanks, fixed!
