### ISSUE TITLE
Periodic progress information

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4048]
No "Slot start" message is printed, thus it's hard to tell if the light client is doing anything, and what its latest view of the network is (what it thinks the head is etc

**Comment by etan-status** [comment]
Assuming this is for `nimbus_beacon_node`, it is printed but only if the LC is more than 8 epochs ahead of DAG and within 2 epochs of wall slot. This was recently added (together with the rename of `--light-client` to `--sync-light-client`)

https://github.com/status-im/nimbus-eth2/blob/613f4a9a50c9c4bd8568844eaffb3ac15d067e56/beacon_chain/nimbus_beacon_node.nim#L1288-L1308

**Comment by arnetheduck** [comment]
`nimbus_light_client` - added an `LC` tag for that

**Comment by arnetheduck** [comment]
another point here: instead of showing the periodic message at all times, it can be limited to when there is  no other activity
