### ISSUE TITLE
Don't sync eth1 deposits when EL is unsynced

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4057]
Trying to fetch deposits on an unsynced EL results in addtional load on the EL further delaying its sync and leads to timeouts in the API - it's also bound to fail most of the time since the EL is known to be out of date.

22.8.1

**Comment by zah** [comment]
We currently detect that the EL is not synced by trying to request a block from time to time (the requested block is the starting point for syncing the deposits). Is the suggesting here to switch to a different specialized API for obtaining the sync status (we'll still have to request the starting block and handle the possibility that it may not be returned)?

**Comment by arnetheduck** [comment]
well, when the beacon node is optimistically synced, the execution data has not been verified yet and the execution client is by definition out of sync - we could simply use the optimistic-or-not status to determine whether deposit sync should be active

**Comment by zah** [comment]
There are no downsides of syncing the deposits as early as possible. Nimbus will not persist the deposits in the database until the data has been confirmed by the finalization process on the beacon chain. If the finalized data indicates that the downloaded deposits are not authentic, the client will automatically restart the syncing process from the latest known confirmed point. The information stored in the downloaded deposits won't be used until the first block proposal, which would require the client to already be fully synced and the deposits to be sufficiently verified.

The risk of starting the syncing process later is that the client might miss a block proposal during the "synced, but not deposits-synced" state.

**Comment by arnetheduck** [comment]
Alright - this was also written at a time when not syncing deposits let to a lot of ugly `ERR` in the logs, when in fact, nothing was wrong, ie the user had just started syncing their eth1 node and was met with ERR all over the place, even though the system was correctly configured.

I think the logging is much better after the multi-el branch and we can close this issue for now - I think I'll open a separate one about the non-synced-UX in general, ie we should be clear about what is an error and what is simply the natural state of things: ideally, a correctly configured client would have NOT:ces as most when it's doing well and we should reserve the higher warning levels for actual problems (by being more refined about what consistutes a problem and what is simply "expected").
