### ISSUE TITLE
[Tests] Refine skipValidation flag

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#407]
The `skipValidation` flag is too coarse and should at least propose a skipBLSValidation option that does not skip `verifyStateRoot`.

This impacts the test suite as some tests use invalid signatures but expect failures on verifyStateRoot

**Comment by gnattishness** [comment]
I think this is resolved by #735?

**Comment by tersec** [comment]
Along with other changes since which don't require as many special cases/opt-outs.
