### ISSUE TITLE
I'm wondering if nimbus plans to add this for Mev Boost? 

### ISSUE THREAD

**Issue by YikesMcSurfFace** [status-im/nim-beacon-chain#4084]
https://bloxroutelabs.medium.com/eth-2-0-validators-capturing-mev-cecdf01f6be6

Lighthouse/prysm have already added it, wondering if nimbus plans to do the same for Mevboost. Pardon me I am not a dev.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/113007714/188802435-4aceeee1-dcdc-4f5a-8d74-f446d8a739be.png">

**Comment by tersec** [comment]
Yes, this is intended at some point.

**Comment by tersec** [comment]
https://writings.flashbots.net/the-cost-of-resilience/ documents some reasonable default thresholds

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4847

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4847
