### ISSUE TITLE
[Göerli] engine_exchangeTransitionConfigurationV1 errors

### ISSUE THREAD

**Issue by gus4rs** [status-im/nim-beacon-chain#4102]
After upgrade to ```v22.9.0``` the beacon chain keeps throwing this error:

```
Sep 09 13:37:12 nimbus_beacon_node[398627]: ERR 2022-09-09 13:37:12.273+01:00 Failed to exchange transition configuration topics="eth1" err="engine_exchangeTransitionConfigurationV1(dataProvider.web3.provider,\n    consensusCfg) failed 3 times. Last error: {\"code\":-32000,\"message\":\"the execution layer has a wrong terminal block hash. expected 0xa1be33e115ca56b51b80f2b7070d8062c3959f0b4a4f5fa35e91135894f55d30, but instead got: 0x0000000000000000000000000000000000000000000000000000000000000000\"}"
```

**Comment by BenedettiLucca** [comment]
Got the same error in mainnet with besu as execution client

**Comment by etan-status** [comment]
Please ensure that you are NOT passing a `--terminal-total-difficulty-override`. This flag was only used for testnets but is NOT needed for mainnet and causes issues if specified on mainnet.

If you have to pass the flag due to your specific configuration, double-check that it is matching the correct mainnet TTD: `58750000000000000000000`.

**Comment by gus4rs** [comment]
I am not passing any flag

**Comment by Yxang** [comment]
Having the same issue here in mainnet after The Merge using erigon as EC:
```
ERR 2022-09-15 07:02:19.738+00:00 Failed to exchange transition configuration topics="eth1" err="engine_exchangeTransitionConfigurationV1(dataProvider.web3.provider,\n    consensusCfg) failed 3 times. Last error: {\"code\":-32000,\"message\":\
"the execution layer has a wrong terminal block hash. expected 0x55b11b918355b1ef9c5db810302ebad0bf2544255b530cdce90674d5887bb286, but instead got: 0x0000000000000000000000000000000000000000000000000000000000000000\"}"
```

Also I noticed when starting the nimbus client, the log shows
```
INF 2022-09-15 07:01:30.735+00:00 Exchanged engine configuration             topics="eth1" ttd=58750000000000000000000 terminalBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000 terminalBlockNumber=0
```
which seems not correct for `terminalBlockHash` and `terminalBlockNumber` value. Not sure whether the problem is in the execution sode or the consensus side.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4126 should fix this -- reopen otherwise.
