### ISSUE TITLE
Modification of agent version for Lodestar

### ISSUE THREAD

**Issue by philknows** [status-im/nim-beacon-chain#4106]
**Is your feature request related to a problem? Please describe.**
Reference: https://github.com/ChainSafe/lodestar/issues/4465

Lodestar is looking to modify the agent version gossiped from the default libp2p string `js-libp2p/0.36.2` to `lodestar/version`. We are requesting an update to your client on how you identify Lodestar nodes for better tracking and referencing of Lodestar peers on the network for debug purposes. We will not implement until it has been completed between all the various clients on the network.

**Describe the solution you'd like**
Please update how you identify Lodestar nodes on the network with your client.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4108
