### ISSUE TITLE
Investigate web3 crash with Besu @BenedettiLucca

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#4118]
This centralizes @BenedettiLucca reported issues as currently they are spread in other users' issues:

- https://github.com/status-im/nimbus-eth2/issues/3521#issuecomment-1242591745
  > Got the same problem on mainnet with besu as execution client. Changing to websocket solved the crashes.
- https://github.com/status-im/nimbus-eth2/issues/4102
  > Got the same error in mainnet with besu as execution client
- https://github.com/status-im/nimbus-eth2/issues/4080
  > Had the same problem with both besu and nimbus fresh syncs, try using the engine api over websocket and not http, worked for me.
  > Have in mind that to get websocket to work you have to pass the --host-allowlist=[hostname] or "*" option in besu.

  and

  > I've updated to 22.9 and still can't use http to connect to the engine API, trying to do so results in crashes with SIGSEGV: Illegal storage access. errors.

**Comment by jclapis** [comment]
I just experienced this on:
- Mainnet (Besu v22.7.2, Nimbus v22.9.0)
- Goerli/Prater (Geth v1.10.23, Nimbus v22.9.0)

It manifests like this:
```
eth2_1           | INF 2022-09-13 18:51:31.171+00:00 State replayed                             topics="chaindag" blocks=1 slots=0 current=f434ec3b:4689255 ancestor=71c742fb:4689247@4689248 target=dd679971:4689248 ancestorStateRoot=b0d79a78 targetStateRoot=c4caf974 found=false assignDur=401ms838us944ns replayDur=157ms245us111ns
eth2_1           | INF 2022-09-13 18:51:31.206+00:00 Missed heartbeat                           heartbeat=GossipSub delay=480ms48us854ns
eth2_1           | INF 2022-09-13 18:51:31.410+00:00 Slot end                                   topics="beacnde" slot=4689255 nextActionWait=1m39s589ms416us716ns nextAttestationSlot=4689264 nextProposalSlot=-1 syncCommitteeDuties=none head=f434ec3b:4689255
eth2_1           | Traceback (most recent call last, using override)
eth2_1           | SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

The fact that Geth caused the same segfault on Prater implies that it's a general EL thing, not a Besu thing.

**Comment by cheatfate** [comment]
@jclapis what is type of connection between `geth` and `nimbus`, `besu` and `nimbus`. Is this HTTP connection or WebSocket connection?

**Comment by jclapis** [comment]
> @jclapis what is type of connection between `geth` and `nimbus`, `besu` and `nimbus`. Is this HTTP connection or WebSocket connection?

Both of them are HTTP connections.

**Comment by BenedettiLucca** [comment]
> This centralizes @BenedettiLucca reported issues as currently they are spread in other users' issues

Sorry for reporting it in this manner, I was trying to get insights on how to fix my issues on the other users threads.
