### ISSUE TITLE
[interop] Rewards & Penalties issue

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#413]
Followup on https://github.com/status-im/nim-beacon-chain/pull/375/files#diff-a4353c02776b35d6615b1b748f96ce04R102

Issue seems in get_attestation_deltas (snippet from interop branch):

https://github.com/status-im/nim-beacon-chain/blob/cd471bbc806906b03a2dd06c144642136c259441/beacon_chain/spec/state_transition_epoch.nim#L315-L403

**Comment by tersec** [comment]
Fixed by https://github.com/status-im/nim-beacon-chain/pull/416
