### ISSUE TITLE
Post call for validator/duties/attester/{epoch} is returning error

### ISSUE THREAD

**Issue by julian-st** [status-im/nim-beacon-chain#4194]
**Describe the bug**
Post call for validator/duties/attester/{epoch} is returning error and should return the duties for an validator index or a list of validator indices

**To Reproduce**
I tried the following call on an arm64 build with the current version after the merge

curl -d "[\"12345\"]" localhost:5052/eth/v1/validator/duties/attester/149919 -v
*   Trying 127.0.0.1:5052...
* Connected to localhost (127.0.0.1) port 5052 (#0)
> POST /eth/v1/validator/duties/attester/149919 HTTP/1.1
> Host: localhost:5052
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 9
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: nim-presto/0.0.3 (arm64/linux)
< Content-Length: 104
< Content-Type: application/json
< Date: Wed, 28 Sep 2022 19:47:51 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
{"code":"400","message":"Invalid validator's index value(s)","stacktraces":["Unsupported content type"]}

**Comment by arnetheduck** [comment]
The correct request would be:
`curl -d '["12345"]' localhost:5052/eth/v1/validator/duties/attester/149919 -H "Content-Type: application/json" -v`

note the [quotes](https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash) and the added `Content-Type`.
