### ISSUE TITLE
Support BN endpoints for producing blinded blocks

### ISSUE THREAD

**Issue by michaelsproul** [status-im/nim-beacon-chain#4220]
**Is your feature request related to a problem? Please describe.**

I would like to produce blinded blocks using Nimbus and an accompanying builder, without those blocks necessarily being sent to the execution node. The reason I'm doing this is for block fingerprinting, but it would also assist with cross-client interop, e.g. Lighthouse's validator client can be configured to request and sign blinded beacon blocks, and I think Vouch may do this by default (cc @mcdee) .

**Describe the solution you'd like**

I would like Nimbus to implement these APIs:

- `GET /eth/v1/validator/blinded_blocks/{slot}`: https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Validator/produceBlindedBlock
- `POST /eth/v1/beacon/blinded_blocks`: https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/publishBlindedBlock

**Describe alternatives you've considered**

- For fingerprinting I'm thinking of hacking the condition [here](https://github.com/status-im/nimbus-eth2/blob/2d6911d526dc10877453e88892088fd3235c242d/beacon_chain/validators/validator_duties.nim#L373-L376) to always enable empty payloads.
- For external validator clients I think there's no alternative, the non-blinded endpoint has to be used instead which rules out using a builder (no way for the VC to sign the blinded block).

**Additional context**

For fingerprinting it would be great to have `skip_randao_verification` too, see: https://github.com/ethereum/beacon-APIs/pull/249.

**Comment by arnetheduck** [comment]
Blinded endpoints are supported as of 22.11 - support for randao skipping will be added in a future release

**Comment by arnetheduck** [comment]
available as of 22.12
