### ISSUE TITLE
[Interop] makefile build issues on Ubuntu 18.04 - bash

### ISSUE THREAD

**Issue by mpetrunic** [status-im/nim-beacon-chain#423]
![image](https://user-images.githubusercontent.com/8836210/64573864-ef6d6a80-d33a-11e9-82fd-30e1ad8248b9.png)

seen with @mratsim and @arnetheduck

**Comment by stefantalpalaru** [comment]
Should be fixed by https://github.com/status-im/nim-beacon-chain/commit/f5b0474aa2c901dab240dc84a8f35d4d16533b50

Please pull and check again.

**Comment by mpetrunic** [comment]
Internet is kinda bad in interop but got it fixed mannually though
