### ISSUE TITLE
Implemend standardised endpoint for doppelganger detection

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4256]
https://github.com/ethereum/beacon-APIs/pull/131 contains a new endpoint for liveness detection that can be used for doppelganger. We should:

* [ ] Implement server
* [ ] Make VC use it

**Comment by zah** [comment]
This was implemented in https://github.com/status-im/nimbus-eth2/pull/4381 and will be shipped in Nimbus 22.12.0
