### ISSUE TITLE
Speed up the loading of validator keys

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#4277]
Large institutional users such as staking pools may run beacon nodes with thousands of validators. Launching Nimbus with large number of validator keys currently results in a significant start-up delay which may result in missed validator duties. We may improve the start-up by optimizing the key loading procedure and by leveraging the `taskpool` library to load multiple keys in parallel.

**Comment by arnetheduck** [comment]
Per discussion, one "trick" to use is that when seed and password is shared between keystore files, they can be decrypted using the same key meaning that multiple keystores can be loaded as fast as a single keystore.

In the meantime, #4301 gives a nice little boost for free by switching the backing sha256 implementation

**Comment by zah** [comment]
This has been implemented in https://github.com/status-im/nimbus-eth2/pull/4372 and shipped in Nimbus `v23.2.0`.

To take advantage of the new functionality, please follow the instructions provided in the Nimbus guide:
https://nimbus.guide/keys.html#optimised-import-for-a-large-number-of-validators
