### ISSUE TITLE
VC should not drop BN on all errors

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4288]
```
{"lvl":"DBG","ts":"2022-11-07 09:02:32.184+00:00","msg":"Received REST response body from remote server","remote":"127.0.0.1:9303","request":"/eth/v1/validator/contribution_and_proofs","contentType":"application/json","size":167,"connection":"202"}
{"lvl":"DBG","ts":"2022-11-07 09:02:32.185+00:00","msg":"Received invalid request response","response_code":400,"node":"127.0.0.1:9303[Nimbus/v22.10.1-1ed9fe-stateofus]","node_index":0,"node_roles":"AGBSD","response_error":"Some errors happened while validating contribution and proof(s)","strategy":"first","request":"publishContributionAndProofs"}
{"lvl":"ERR","ts":"2022-11-07 09:02:32.185+00:00","msg":"Unable to publish sync contribution","contribution":{"slot":4275312,"beacon_block_root":"5b5d02d1","subcommittee_index":0,"aggregation_bits":"0b00111000000100000010101111001001000011000100101111000101011010001010000000110001000010000100001110010000000011000110000111100000"},"validator":"b91007ba","validator_index":198283,"err_msg":"Beacon node(s) unable to satisfy request","service":"sync_committee_service"}
{"lvl":"WRN","ts":"2022-11-07 09:02:32.185+00:00","msg":"Sync contribution was not accepted by beacon node","contribution":{"slot":4275312,"beacon_block_root":"5b5d02d1","subcommittee_index":0,"aggregation_bits":"0b00111000000100000010101111001001000011000100101111000101011010001010000000110001000010000100001110010000000011000110000111100000"},"validator":"b91007ba","validator_index":198283,"service":"sync_committee_service"}
{"lvl":"DBG","ts":"2022-11-07 09:02:32.185+00:00","msg":"Sync message contribution statistics","total":1,"succeed":0,"failed_to_deliver":0,"not_accepted":1,"delay":"185ms183us956ns","slot":4275312,"service":"sync_committee_service"}
{"lvl":"WRN","ts":"2022-11-07 09:02:33.898+00:00","msg":"No suitable beacon nodes available","online_nodes":0,"offline_nodes":0,"uninitalized_nodes":0,"incompatible_nodes":1,"nonsynced_nodes":0,"total_nodes":1,"service":"fallback_service"}
```

#4287 caused the BN to reject the sync contribution but attestations and blocks are still getting through - the BN should not be removed in this case - keep using the BN is harmless and may be helpful (for the "working" messages), so it's better to keep trying than to remove from BN pool

**Comment by cheatfate** [comment]
There is no reason to keep BNs which returned 400, this means that either this BN behaves in incorrect way or there is a bug in VC or we have incorrect time... There is no straight way. Right now we are in active development phase, as soon as most of the issues and bugs will be fixed number of 400 errors will be very low. And so there will be no disconnects at all.

**Comment by arnetheduck** [comment]
> There is no reason to keep BNs which returned 400,

Well, in this particular case, there clearly was: the BN was still routing attestations which generated profit - there's no harm in _trying_ to route through such a BN: if it fails, so be it, but there is a chance that between one message and the next, the BN starts working (for example if it loses sync for a short while

**Comment by arnetheduck** [comment]
One way to do this is that when there's a failure, we can schedule a config / sync check: if that check fails, we can remove the BN - this way, we keep the BN until it's been checked and proven faulty instead of removing it and then getting it back again in a loop. Such a scheduled check should obviously have a rate limit as well so that when sending N messages in a slot, there's only one check.

**Comment by cheatfate** [comment]
@arnetheduck i think this issue is fixed in https://github.com/status-im/nimbus-eth2/pull/4635 ?
