### ISSUE TITLE
Empty execution payload should have fee recipient set

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4289]
https://github.com/status-im/nimbus-eth2/blob/06ccf5b80c316a1eae4f8dbcdc3a4b822e80e7ad/beacon_chain/spec/helpers.nim#L383 is missing the fee recipient

**Comment by etan-status** [comment]
While this seems benign (there are no actual funds sent to the fee recipient), this is still important to fix, as RocketPool will socially "slash" on incorrect fee recipient.

https://docs.rocketpool.net/guides/redstone/whats-new.html#the-penalty-system

**Comment by etan-status** [comment]
> A minipool that proposed a block with an invalid fee recipient will be issued a strike. On the third strike, the minipool will begin receiving infractions - each infraction will dock 10% of its total Beacon Chain balance, including ETH earnings and send them to the rETH pool stakers upon withdrawing funds from the minipool.
> 
> Infractions are at a minipool level, not a node level.
