### ISSUE TITLE
Tighten sync committee duty polling

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4290]
The current VC polls sync committee duties for current and next epoch:

https://github.com/status-im/nimbus-eth2/blob/a1201f13a482a84e4b6d230c1d648b6a49023d9a/beacon_chain/validator_client/duties_service.nim#L445

This is both too much and not enough - we should:

* not poll the same period twice (even if the epoch is different)
* start polling the "next" period 4 epochs before the period starts (and consequently register those duties - currently this happens 1 epoch before which might not be enough

**Comment by cheatfate** [comment]
Fixed in #4333.
