### ISSUE TITLE
Prettier CLI

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#434]
We have plenty of logs but they are confusing to follow the state of the client without explanations.

For demo purpose like devcon we could use 20% of the top screen space to report the client state, for example:
- number of peers connected to
- current block, slot, epoch
- latest justified/finalized block, epoch, slot

This would also be helpful to see when we run out of peers or are not finalizing.

In the future this might be better handled via an API like via nim-metrics but a minimal interface would be a great start.

**Comment by zah** [comment]
Using the top portion of the screen prevents accessing the out-of-screen information through scrolling. I think we can instead put a bar at the bottom of the screen similar to this interface:

![repl](https://github.com/prompt-toolkit/python-prompt-toolkit/raw/master/docs/images/ptpython.png)

But developing cross-platforms CLIs is not a trivial task, we might get better mileage with a Web GUI.

**Comment by mratsim** [comment]
Bottom of the screen sounds good. But I want something that makes understanding the status easier than hunting though logs for justification/finalization.

I think it's important that we have a minimal CLI output so that it's easily accessible through SSH or by just plugging a screen to a Raspberry Pi.

**Comment by zah** [comment]
I should mention that the chronicles-tail tool already features a similar interface with an interactive prompt at the bottom of the screen. Handling the logging output in this setup is a bit tricky, because the naive approach messes up the prompt, but the [nim-prompt](https://github.com/surf1nb1rd/nim-prompt) was created for this purpose. If we want something more fancy, we can extend it.

**Comment by stefantalpalaru** [comment]
See also: https://github.com/rnowley/nim-ncurses

**Comment by zah** [comment]
This has been implemented
