### ISSUE TITLE
Log improvements

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#437]
Looking at the logs we send we can improve those:

- Fork choice: only report the result of the fork choice (no head update/new head) instead of preparing for fork choice and fork chosen. Those were important in Feb/March when we had fork choice issues but produce a lot of noise now.
- Block and attestation sent: those are directly followed by the node receiving its own block and attestation. This should be removed so that we can properly trace the block/attestation from other clients
- Justification and finalization: a proper message should be displayed when those happen, bonus if we know the rule used from https://github.com/protolambda/eth2-docs#justification-and-finalization
- slot processing: checking attestation, scheduling slot action are not needed anymore, "slot start" should be enough

It might be good to think deeply about logging during the offsite as it will be the primary tool people will use to interact with Nimbus.

**Comment by mratsim** [comment]
Another thing is that logging might introduce high overhead by repeatedly reporting the hash_tree_root of the state. I might be helpful to benchmark the cost of SSZ serialization. I don't think we can cache it though as we need a hash as a cache ID anyway.

**Comment by arnetheduck** [comment]
one thing to note is the log level: `INF` should be the log level we recommend users to run and thus what we audit for a "sensible" and complete, normalized/minimal output of data that will allow us to meaningfully "replay" scenarios the user encounters

**Comment by mratsim** [comment]
Closing: the goal of this issue was to improve logging for the interop event. As the codebase mature and the "real" testnet approaches, our logging needs have changed and will be tracked in new issues.
