### ISSUE TITLE
UX for pruning

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4419]
In offering pruning support, there are several things that can be pruned - https://github.com/status-im/nimbus-eth2/blob/45574021c3d60582a401c21e9095be808b477629/beacon_chain/consensus_object_pools/block_pools_types.nim#L109 uses some terms like "history" and "archive" but these have not made it outside of that module - although the code support in chaindag is mostly there, this has not yet been exposed in the CLI.

When considering pruning, we have several types of data to consider:

* blocks - need to be stored for `MIN_EPOCHS_FOR_BLOCK_REQUESTS` (33024 epochs, ~5 months)
* states - need finalized state and newer - upper bound in the inactivity leak range, ie in the ~3 weeks range (https://eth2book.info/bellatrix/part2/incentives/inactivity/)
* light client updates - `MIN_EPOCHS_FOR_BLOCK_REQUESTS` too - their size is negligeable so we might as well keep them

We also  have to consider indices on top of the raw data:
* block hash -> mini-header (slot+parent_root)
* slot->block (finalized blocks)
* (slot+block) -> state_root

Some statistics:

```
sqlite> select avg(length(value))/1024, sum(length(value))/1024, count(*) from bellatrix_state_no_validators ;
6774.26703344652|4457467|658

sqlite> select avg(length(value))/1024, sum(length(value))/1024, count(*) from bellatrix_blocks;
53.2420313847627|34399729|646101
```

From this table, we can see that blocks take up roughly 8x the size of states as of a fairly recent snapshot, looking at bellatrix+ state & block sizes. Avg block size is `53kb` but there's a lot of them - another way to look at it that for every state, we store ~1k blocks.

Currently, we backfill blocks to genesis and don't purge states - effectively, this leads to a mode of operation where a trusted-node-synced node has state history from the checkpoint-point, a forward-synced node has history from genesis and all nodes have blocks since genesis.

We can also "reindex" a backfilled node to create the intermediate states, turning a "backfill" node into a "genesis" node, but there is no (clean) way to move from "genesis" to "backfilled" (ie purging the states up to a point). There is also no way to move the "checkpoint-point".

Ignoring light client updates (they're small and can follow whatever we do for blocks or simply stay around for now since Nimbus is the majority light client provider), we can consider the following pruning modes:

* minimal - prune states and blocks to their absolute minimums
* normal - prune states and blocks to `MIN_EPOCHS_FOR_BLOCK_REQUESTS` - this allows "some" historic requests and is simple to explain
* archive - no pruning (as today)

Notably, here we talk about pruning only - it doesn't say anything about TNSed nodes, or how far they backfill.

Since in normal mode, we start pruning blocks and states after 5 months, it's reasonable to expect that it will grow harder and harder to backfill blocks from the network. Also, even when backfilling, it's not possible to recreate state history except by going either from genesis or from a snapshot.

Thus, it makes  sense to **never backfill** any further than what is minimally required by the protocol and instead rely on era files completely for the creation of "genesis" nodes.

On top of the above, it's cheap to move the pruning point backwards in time - for example if there's a usecase for "1 year of history" this can be expressed as "normal + X".

A possible UX is thus:

* `--pruning=[minimal/normal/none]`
* `--prune-horizon=N` where N is the number of (epochs/eras) of extra data to keep - it is debatable whether this option is worth the implemenation effort (ie just run an archive node, it's not like they're crazy expensive)

When talking about this, we end up with:

* "genesis archive node" for a node that was synced from genesis and has all history (exists today)
* "checkpoint archive node" for a node that was TNSed and then didn't prune (exists today)
* "minimal node" - a node that has no state history - there's no effective difference between "genesis" and "checkpoint" because pruning will render the two the same
* "normal node" - the default UX which offers about 5 months of history as a convenient middle ground - notably, after 5 months, a  checkpoint node becomes equivalent to a genesis node in this configuration

The above also does not consider the creation of era files - currently, era file creation is done using an external process which works with genesis archive nodes - one could plausibly consider a "prune-to-era" option, but that is outside the scope of this issue.

To make the above work well, it would be advisable to bring to production the state-diff feature - it would further lower the cost of "normal" nodes while at the same time speeding up queries, assuming diffing is done at a higher granularity than the 1024 blocks that we have today for state snapshots.

**Comment by arnetheduck** [comment]
Extrapolating the above stats, we reach steady-state databases sizes of:

* minimal: `53.24 * 32 * 33024 + some small constant` = **~53gb**
* normal: `53.24 * 32 * 33024 + 6774 * 32 * 33024 / 1024`  = **~60gb**
* archive: keeps growing

(notably, this steady state is the typical state size based on current usage - eip4844 and other efforts will obviously have effects - so will atypical use, should patterns change and blocks become bigger)

**Comment by etan-status** [comment]
Note that LC responses currently use the historic states to extract the sync committees. If state pruning is becoming more aggressive than blocks pruning, may need to store a copy of the sync committees separately.

**Comment by arnetheduck** [comment]
As far as deployment plans go, this would probably be rolled out with a default "archive" strategy, then the default would change to "normal" after the hard fork (so as to guarantee that all users have upgraded to a version that supports reading databases without full block history)

**Comment by arnetheduck** [comment]
> If state pruning is becoming more aggressive than blocks pruning, may need to store a copy of the sync committees separately.

I think we may want this design regardless, ie to keep the light client data completely separate.

**Comment by zah** [comment]
@arnetheduck, can you add some thoughts regarding the density of state snapshots? Is your thinking above based on the assumption that we won't need frequent state snapshots once we have efficient state diffs?

In a previous [related issue](https://github.com/status-im/nimbus-eth2/issues/3081) that I've filed, I also had documented the following idea:

> To further improve the support for archive nodes, future version of Nimbus may use a more compact representation for the append-only fields in the BeaconState that would make their presence in snapshots unnecessary. Instead, we can have a single append-only storage item for every append-only field and we can compute the range within that storage item that corresponds to a particular finalized state.

**Comment by arnetheduck** [comment]
> Is your thinking above based on the assumption that we won't need frequent state snapshots once we have efficient state diffs?

ideally, yes - with efficient diffs, I imagine we can store a full state for every era and diffs on top of that - either at a slot or epoch granularity depending on the size of that diff - ie a block is effectively a state diff from one slot to another, albeit not a very efficient one - so we could either go with one state-diff per epoch to skip ahead quickly (because most interesting state fields change at this granularity) or a more detailed each-slot-diff (feels too expensive but maybe not)

**Comment by arnetheduck** [comment]
> more compact representation for the append-only fields in the BeaconState 

there aren't that many apart from the validator set - historical roots is too small to be worth the bother and the other fields get cleared at a regular basis - I intuitively doubt there are any notable gains here that are not already implemented.

the gains in state-diff come from representing the circular hash structures more efficiently - these take up significant space and don't compress, even though only a fraction of the data changes on every epoch.
