### ISSUE TITLE
[Interop] Prysm script issue on OSX

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#444]
Not sure how Prysm was installed (docker or bazel) but there are a couple of issues with the scripts on mac:

- `paste` needs a dash `-` at the end to accept the pipe
- `bazel run //beacon-chain --` is needed, just `./beacon-chain` will throw an error that "beacon-chain" is a directory
- `../data/` doesn't work for custom paths not in `multinet/`
   Additionally when using bazel I'm not too sure of the working directory as I'm having issues with it.

**Comment by prestonvanloon** [comment]
Can you try with https://github.com/status-im/nim-beacon-chain/pull/445?

**Comment by arnetheduck** [comment]
@mratsim can you check the current interop scripts in the interop branch?

**Comment by mratsim** [comment]
Yes, works for me now. I edited the script to use https instead of ssh as I didn't give my token cloning rights and it failed for me.
