### ISSUE TITLE
Report time it took to run the tests

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#450]
Maybe for unittest2.

Having test timing would be helpful:
- to see if we have suspiciously slow tests on some fixed hardware.
- to report perf degradation

This is the first step to have anti-perf regression test suite.

An example of very slow test is in test_fixture_sanity_blocks.nim on mainnet preset:

- empty_block_transition (a few seconds)
- skipped_slots (a few seconds)
- empty_epoch_transition (dozens of seconds)
- voluntary_exit test
...

**Comment by stefantalpalaru** [comment]
The CPython test suite runner could be an inspiration for that: https://github.com/python/cpython/blob/2.7/Lib/test/regrtest.py

`-S/--slowest    -- print the slowest 10 tests`

**Comment by tersec** [comment]
If/when people want something beyond https://github.com/status-im/nim-beacon-chain/pull/624 they can open a new issue.
