### ISSUE TITLE
newPayload failed - check execution client

### ISSUE THREAD

**Issue by fronts-sergey** [status-im/nim-beacon-chain#4532]
![photo_2023-01-20 15 28 15](https://user-images.githubusercontent.com/24233047/213705977-61494325-936c-4893-8c20-4a2e96566d31.jpeg)

**Comment by arnetheduck** [comment]
Make sure you've passed the correct `--jwt-secret` to both your nodes: https://nimbus.guide/eth1.html#3-pass-the-url-and-jwt-secret-to-nimbus

**Comment by arnetheduck** [comment]
The error indicates 401 - authorization - this is likely a setup issue in the EL and/or JWT secret mismatch - closing since we've had no response
