### ISSUE TITLE
Add method to retrieve randao value 

### ISSUE THREAD

**Issue by soos3d** [status-im/nim-beacon-chain#4561]
**Is your feature request related to a problem? Please describe.**
Users might be interested in extracting the randao value.

**Describe the solution you'd like**
Adding a method to retrieve the value like the Prysm clients has.
[Reference](https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/rpc/apimiddleware/endpoint_factory.go#L28)

**Comment by zah** [comment]
The implementation of this feature will be tracked in the https://github.com/status-im/nimbus-eth2/issues/4335 issue. We've recently agreed to prioritize this work for our upcoming releases.
