### ISSUE TITLE
Remove use of global `gProtocols` global protocol registry from `nimbus_beacon_node`

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#4578]
Because https://github.com/status-im/nimbus-eth2/issues/4571 will start hitting major stable and LTS distributions, without the underlying gcc 12.x bug having been fixed or Nim (any branch) having implemented some workaround to avoid generating triggering C code, it now lands on `nimbus-eth2` to avoid this issue.

https://github.com/status-im/nimbus-eth2/blob/94837caa2a5fba5ab2777dbd9ff7f0a422cbd4b2/beacon_chain/networking/eth2_network.nim#L1015-L1020
is the code triggering it in this repo. That particular global `gProtocols` comes from https://github.com/status-im/nim-eth/blob/master/eth/p2p/p2p_backends_helpers.nim but it's less clear whether its https://github.com/status-im/nim-eth/blob/master/eth/p2p/rlpx.nim usage might trigger the same issue. As `nimbus-eth2` does not use RLPx, this issue only concerns itself with the `eth2_network` usage.

The key most readily avoidable aspect which triggers the gcc bug is that it's a mutable, global variable.

**Comment by tersec** [comment]
For the record, for anyone else affected, one workaround required to work with the REST API tests, or to run a local testnet:
```diff
diff --git a/config.nims b/config.nims
index 5d74da20..978efbb9 100644
--- a/config.nims
+++ b/config.nims
@@ -29,26 +29,6 @@ else:
   let nimCachePath = nimCachePathOverride
 switch("nimcache", nimCachePath)

-# `-flto` gives a significant improvement in processing speed, specially hash tree and state transition (basically any CPU-bound code implemented in nim)
-# With LTO enabled, optimization flags should be passed to both compiler and linker!
-if defined(release) and not defined(disableLTO):
-  # "-w" is not passed to the compiler during linking, so we need to disable
-  # some warnings by hand.
-  switch("passL", "-Wno-stringop-overflow -Wno-stringop-overread")
-
-  if defined(macosx): # Clang
-    switch("passC", "-flto=thin")
-    switch("passL", "-flto=thin -Wl,-object_path_lto," & nimCachePath & "/lto")
-  elif defined(linux):
-    switch("passC", "-flto=auto")
-    switch("passL", "-flto=auto")
-    switch("passC", "-finline-limit=100000")
-    switch("passL", "-finline-limit=100000")
-  else:
-    # On windows, LTO needs more love and attention so "gcc-ar" and "gcc-ranlib" are
-    # used for static libraries.
-    discard
-
 # show C compiler warnings
 if defined(cwarnings):
   let common_gcc_options = "-Wno-discarded-qualifiers -Wno-incompatible-pointer-types"
```

**Comment by tersec** [comment]
Debian stable with affected gcc has been released: https://www.debian.org/News/2023/20230610

**Comment by arnetheduck** [comment]
#5719
