### ISSUE TITLE
How to run old unsupported networks using metadata folder? Instructions are obviously not clear.

### ISSUE THREAD

**Issue by J-A-M-E-5** [status-im/nim-beacon-chain#4593]
**Describe the bug**
After removing ropsten support with the --network=ropsten option which now throws an error, the [changelog stated that you can pass the metadata folder](https://github.com/status-im/nimbus-eth2/blob/adcc57e7ca328038a92f14ed7cfa8a80213eaab0/CHANGELOG.md#breaking-changes) to the --network option instead to continue to run ropsten. It doesn't work, I get an invalid unsigned integer error. I am not sure if this is a bug, or if I am not following instructions correctly. If I append "/config.yaml" to the path I get a config.yaml not found error, so I am presuming I have to specify the folder.

**To Reproduce**
`$ nimbus_beacon_node --network=/home/user/src/nimbus-eth2/vendor/merge-testnets/ropsten-beacon-chain ....`

`Cannot load network                        msg="invalid unsigned integer: 0xeefb1f70bf7bed6394ed7d6f812f422aa37bf7680e1b75fa551d40e849f10a87" networkName=/home/user/src/nimbus-eth2/vendor/merge-testnets/ropsten-beacon-chain/
`

![Screenshot 2023-02-03 at 21 27 46](https://user-images.githubusercontent.com/26421539/216734788-676f8751-151a-41bb-b453-583911a6d324.png)

**Comment by J-A-M-E-5** [comment]
I'd rather run with the latest version on ropsten, but for those with same problem who want to continue to use ropsten compatible version for now checkout and compile older version:-

```
git clone https://github.com/status-im/nimbus-eth2.git nimbus-eth2-old-v22.11.0-38827d
cd nimbus-eth2-old-v22.11.0-38827d
git reset --hard 38827d776c7bee9fb2ec886f7b8befe758e783b7 # Last commit hash before ropsten removed
make -j8 update && make -j8 nimbus_beacon_node
```
You might want to move the bin somewhere (perhaps with _ropsten suffix on name so you know) and then delete the entire source folder as it's quite big.

**Comment by etan-status** [comment]
This seems to be a data issue with the actual config folder.

https://github.com/eth-clients/merge-testnets/blob/main/ropsten-beacon-chain/deposit_contract_block.txt
The `deposit_contract_block.txt` should indicate a block number, while `deposit_contract_block_hash.txt` should contain a hash value. Loading the config folder fails because `deposit_contract_block.txt` refers to a hash value instead of a block number. @parithosh

**Comment by J-A-M-E-5** [comment]
> This seems to be a data issue with the actual config folder.
> 
Thanks for your analysis @etan-status, is there some of easy fix (patch) I can do with my local files cause I am not sure how much support anyone is going to get for Ropsten from the ETH foundation? Cheers.

**Comment by etan-status** [comment]
Submitted a PR upstream: https://github.com/eth-clients/merge-testnets/pull/31
After cloning that branch next to the `nimbus-eth2` directory, I can start Nimbus, using `--network=../merge-testnets/ropsten-beacon-chain`.

**Comment by etan-status** [comment]
Upstream PR was merged. Have bumped our `vendor/merge-testnets` as well: https://github.com/status-im/nimbus-eth2/pull/4598
