### ISSUE TITLE
Error with compiliation

### ISSUE THREAD

**Issue by yanrising** [status-im/nim-beacon-chain#4599]
OS: Ubuntu 18
After clonning source code from github:
```
git clone https://github.com/status-im/nimbus-eth2.git
cd nimbus-eth2
make update
```
Result:
`Git submodules not found. Running 'git submodule update --init --recursive'.`

`git submodule update --init --recursive
`
Result:
```
fatal: No url found for submodule path 'vendor/nim-snappy/tests/snappycpp/third_party/benchmark' in .gitmodules
Failed to recurse into submodule path 'vendor/nim-snappy/tests/snappycpp'
Failed to recurse into submodule path 'vendor/nim-snappy'
```
![Screenshot_1](https://user-images.githubusercontent.com/76003604/217141825-1e2301c6-e7b3-46ca-a9ab-957b63a4be51.jpg)

**Comment by etan-status** [comment]
Have you installed the prerequisites?
https://nimbus.guide/build.html
```sh
sudo apt-get install build-essential git cmake
```

**Comment by yanrising** [comment]
Yes, installed

**Comment by arnetheduck** [comment]
I've seen this happen on occasion, but we do the same thing in CI where it works - I believe this may be a temporary issue - regardless, it's safe to ignore and move on to `make` as the next build step - it will work fine without.

**Comment by yanrising** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/76003604/217285820-8ded2f59-ba07-4a47-832f-12c2e3b9a0de.jpg)

**Comment by arnetheduck** [comment]
yep - now try again :)

**Comment by yanrising** [comment]
Tried. Same result. Error

**Comment by yanrising** [comment]
dagen@ubuntu:~/projects/nimbus-eth2$ make update deps
Creating nimbus-build-system.paths
fatal: No url found for submodule path 'vendor/nim-snappy/tests/snappycpp/third_party/benchmark' in .gitmodules
Failed to recurse into submodule path 'vendor/nim-snappy/tests/snappycpp'
Failed to recurse into submodule path 'vendor/nim-snappy'
fatal: No url found for submodule path 'vendor/nim-snappy/tests/snappycpp/third_party/benchmark' in .gitmodules
Failed to recurse into submodule path 'vendor/nim-snappy/tests/snappycpp'
Failed to recurse into submodule path 'vendor/nim-snappy'
vendor/nimbus-build-system/makefiles/targets.mk:107: recipe for target 'update-common' failed
make: *** [update-common] Error 1

**Comment by arnetheduck** [comment]
we're quite unable to reproduce this, and stackoverflow has lots of hits on random problems that people have with their git repos or git versions for the [given error](https://stackoverflow.com/search?q=No+url+found+for+submodule+path): the best thing I can think of is to remove `nimbus-eth2` completely and start over, perhaps upgrading `git` first - it could be that there are some leftovers in your git setup that prevent git from recovering or a filesystem issue - maybe a shorter directory name is needed?

**Comment by yanrising** [comment]
System is new and clean. Full testing installation. All upgaded and dependencies are installed. Error indicates at make command that can not find submodule path 'vendor/nim-snappy/tests/snappycpp/third_party/benchmark' in .gitmodules Although link in .gitmodules are correct

**Comment by arnetheduck** [comment]
Indeed - https://github.com/google/snappy/blob/main/.gitmodules lists the module as expected.

Not sure if it helps, but you can try `cd vendor/nim-snappy/tests/snappycpp/; git submodule init; git submodule sync` which is roughly what the makefile does - perhaps that will show a better error.

**Comment by arnetheduck** [comment]
https://github.com/status-im/nimbus-eth2/actions/runs/4165029534/jobs/7207465227#step:8:149 is how our CI does the checkout - we can see the system correctly checking out benchmark on a comparable OS - perhaps you can compare and see if there is any difference compared to your log?
