### ISSUE TITLE
There are missing test cases for the merged interop fixes

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#463]
Some of the fixes from our interop branch were recently merged without corresponding test cases in
https://github.com/status-im/nim-beacon-chain/pull/461

Ideally, we should ensure that such test cases are available as part of the official EF test suites, but in the meantime we can add custom unit tests for the following problems:

1) Overflow in the `BeaconState.justification_bits` BitVector in `process_justification_and_finalization`

2) Reading a SSZ object including an empty byte list.

    During the interop testing, we received a [crash report with a stack trace](https://github.com/status-im/nim-beacon-chain/issues/428) that lead us to implement the ssz.nim fix is https://github.com/status-im/nim-beacon-chain/pull/461. This issue requires some further investigation because it was never fully confirmed that the crash was caused by the fixed issue and it's not clear why the existing test cases in [ssz_minimal_nil](https://github.com/status-im/nim-eth2-official-tests/blob/59830c90e11291c886c71b8cdf83a81651d5fbc0/json_tests_v0.8.1/ssz_static/core/ssz_minimal_nil.json) didn't cover the problematic situation.

3) Fix in `process_slots` related to missing `BeaconState.root` update

    @arnetheduck, can you please edit the description here to provide more details about this issue?

4) Off-by-one error in genesis state computation

   Fix merged here: https://github.com/status-im/nim-beacon-chain/pull/468

5) Wrong attestation selection leading to wrong rewards and penalties

   Fix with more detailed description merged here: https://github.com/status-im/nim-beacon-chain/pull/470

6) Incorrect attestation signing

   Fix merged here: https://github.com/status-im/nim-beacon-chain/pull/472

**Comment by tersec** [comment]
Is this still relevant?

**Comment by arnetheduck** [comment]
probably not
