### ISSUE TITLE
Prater unstable nodes unable to sync with EL node

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#4695]
This "warning" started appearing on `unstable` and `libp2p` Prater nodes on 2nd of March:
```json
{                                                                                                     
  "lvl": "WRN",
  "ts": "2023-03-06 11:26:59.040+00:00",
  "msg": "Failed to obtain the most recent known block from the execution layer node (the node is probably not synced)",
  "topics": "elmon",
  "url": "http://localhost:8554",
  "blk": "0x5ac670562dbf877a45039d65ec3c2e3402a40eda9b1dba931c2376ab7d0927c2",
  "err": "hex input too large"
}
```
Based on Eth1 Chain length metrics this started at `11:30:00` UTC on 2nd of March:

![image](https://user-images.githubusercontent.com/2212681/223112873-fdaf3e4e-4716-4086-90b9-69a30e33c1a4.png)
https://metrics.status.im/d/pgeNfj2Wz23/nimbus-fleet-testnets?orgId=1&refresh=5m&var-instance=linux-02.he-eu-hel1.nimbus.prater&var-container=beacon-node-prater-unstable&from=1677501760116&to=1678106560116

This is from `linux-02.he-eu-hel1.nimbus.prater`, but other hosts show the same behavior for `unstable` and `libp2p` nodes.

**Comment by jakubgs** [comment]
Both CL and EL nodes appear as synced:
```
admin@linux-02.he-eu-hel1.nimbus.prater:~ % for port in $(seq 9300 9305); do curl -s 0:$port/eth/v1/node/syncing | jq -c; done
{"data":{"head_slot":"5133204","sync_distance":"0","is_syncing":false,"is_optimistic":false}}
{"data":{"head_slot":"5133204","sync_distance":"0","is_syncing":false,"is_optimistic":false}}
{"data":{"head_slot":"5133204","sync_distance":"0","is_syncing":false,"is_optimistic":false}}
{"data":{"head_slot":"5133204","sync_distance":"0","is_syncing":false,"is_optimistic":false}}

admin@linux-02.he-eu-hel1.nimbus.prater:~ % for dir in /docker/geth-goerli-*; do $dir/rpc.sh eth_syncing | jq -c; done
{"jsonrpc":"2.0","id":1,"result":false}
{"jsonrpc":"2.0","id":1,"result":false}
{"jsonrpc":"2.0","id":1,"result":false}
{"jsonrpc":"2.0","id":1,"result":false}
```
And no logs suggesting lack of connectivity can be found. Only things like:
```json
{
  "lvl": "DBG",
  "ts": "2023-03-06 12:41:48.945+00:00",
  "msg": "Message sent to RPC server",
  "topics": "JSONRPC-HTTP-CLIENT",
  "address": {
    "oResultPrivate": true,
    "vResultPrivate": {
      "id": "localhost:8554",
      "scheme": 0,
      "hostname": "localhost",
      "port": 8554,
      "path": "",
      "query": "",
      "anchor": "",
      "username": "",
      "password": "",
      "addresses": [
        {
          "family": "IPv4",
          "address_v4": [ 127, 0, 0, 1 ],
          "port": 8554
        }
      ]
    }
  },
  "msg_len": 250802
}
```

**Comment by zah** [comment]
For clarity, this is not related to the recent `ELMonitor` changes. The problem appears to have started with the latest Geth upgrade on the fleet.

**Comment by jakubgs** [comment]
BUT it only affects `unstable` and `libp2p` branch nodes as far as I can tell. And `libp2p` is based off of `unstable`.

**Comment by jakubgs** [comment]
Seems to me like the issue has been resolved:

![image](https://user-images.githubusercontent.com/2212681/223412553-88323a94-6c2e-4357-9f10-346893c26ac4.png)

The Eth1 chain length is back to normal, meaning, not being zero.
