### ISSUE TITLE
Suggestion how to fix failing macOS AMD64 - Nightly build

### ISSUE THREAD

**Issue by jangko** [status-im/nim-beacon-chain#4758]
**Describe the bug**

macOS AMD64 - Nightly build failing with error message:

```
undef: ___isOSVersionAtLeast
Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      _upnp_gettimeofday in libminiupnpc.a(minissdpc.o)
ld: symbol(s) not found for architecture x86_64
```

Suggestions below only to fix the scripts. Someone still have to build the base docker image and push it to docker hub.

1. add ` --passL:'-lSystem'` to this line
 
https://github.com/status-im/nimbus-eth2/blob/287ae79c87d241d678241afd0449b5351e5d3e6f/docker/dist/entry_point.sh#L152

2. add `./build_compiler_rt.sh` before this `# cleanup` line

https://github.com/status-im/nimbus-eth2/blob/287ae79c87d241d678241afd0449b5351e5d3e6f/docker/dist/base_image/build_osxcross.sh#L24

3. add `&& update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-11 100 \` to `docker/dist/base_image/Dockerfile.macos` after this line

https://github.com/status-im/nimbus-eth2/blob/287ae79c87d241d678241afd0449b5351e5d3e6f/docker/dist/base_image/Dockerfile.macos#L17

4. and update this line using the new built base image's tag and sha256

https://github.com/status-im/nimbus-eth2/blob/287ae79c87d241d678241afd0449b5351e5d3e6f/docker/dist/Dockerfile.macos#L2

**Comment by tersec** [comment]
It appears that the nightly builds do work now: https://github.com/status-im/nimbus-eth2/releases/tag/nightly

https://github.com/status-im/nimbus-eth2/commit/c22962f3821d069f86ee38826443f9830931cc7c was part of it, at least.

**Comment by arnetheduck** [comment]
nightlies are broken again but for a different reason - closing this as fixed
