### ISSUE TITLE
Slashed validators are counted in the required stability subnets at startup

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-beacon-chain#4787]
**Describe the bug**
At startup, we add every validators, including slashed ones in the `knownValidators` validators set.
This causes the nodes to subscribe to a lot of stability subnets
When the stability subnets get refreshed, they slowly decrease since the slashed validators are not longer counted

**Screenshots**

https://metrics.status.im/d/pgeNfj2Wz23/nimbus-fleet-testnets?orgId=1&var-instance=linux-05.he-eu-hel1.nimbus.prater&var-container=beacon-node-prater-libp2p&from=1680278988225&to=1680550202130
![image](https://user-images.githubusercontent.com/13471753/229764899-31a908cc-62af-4bef-8960-a8916ce3a114.png)

Node with 43 slashed validators, 17 active.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4793
