### ISSUE TITLE
Use withdrawal credentials as default fee recipient

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4792]
Now that everyone will have shiny new withdrawal credentials, we should not send EL fees to 0x000... - instead, we can use the 0x01 withdrawal credential of the validator as a sensible default simplifying setup and avoiding the need for yet another command line option for simple setups.

**Comment by zah** [comment]
Implemented in the linked PR above and shipped in Nimbus 23.5.1.
