### ISSUE TITLE
Finalization issue on master

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#481]
The current master (https://github.com/status-im/nim-beacon-chain/commit/5f271fd82e3b3093fa293c3171ccf62fa34d8009) has a finalization issue, while running the prompt the whole night on a raspberry Pi, the last finalized epoch stayed stuck at 0. I had to use a branch from last week.

**Comment by arnetheduck** [comment]
https://github.com/status-im/nim-beacon-chain/commit/669b81495a7642ecee999d55d52fdb84fb22a86d most likely

**Comment by zah** [comment]
In the test run discussed here, there shouldn't have been any missing nodes, because we've launched an extra node manually with `run_node.sh`. If the fix here is solving the problem though, I suspect we might have missed another explanation for the problem.

**Comment by arnetheduck** [comment]
well, the sim finalizes with 6 nodes without issues - without any other info, it's hard to tell what the reason in that particular case was though (ie no logs, no info about how it was run etc) - networking issue? could have been anything and we can reopen the bug if a precise repro is found
