### ISSUE TITLE
local-block-value-boost clarification

### ISSUE THREAD

**Issue by Xexr** [status-im/nim-beacon-chain#4883]
https://github.com/status-im/nimbus-eth2/pull/4847

23.4.0 includes the new option "--local-block-value-boost" with the comment:

_"as long as its value is within the specified percentage of the value advertised by the best external builder. Setting this flag to a non-zero value is recommended because the usage of an external builder introduces an additional risk that the advertised block won't be published by the builder"_

However the notes aren't clear on how the value should be specified and it's not yet in the docs as far as I could see.

Please could you provide a few examples, e.g. would:

`--local-block-value-boost=1`

Mean that if the local block fee capture was within 1% of the external builder proposal, then the local block would be used instead? Or should the percentage be specified in some other way?

Also, I note that mev_boost already includes an option for specifying a minimum eth fee value for using the external builder block. Should these two options be used in tandem?

**Comment by Xexr** [comment]
https://github.com/status-im/nimbus-eth2/issues/4243

Subsequently found this issue on mev-boost so I now understand the differentiation on that point but would still appreciate clarification on setting the value.

Many thanks

**Comment by Aminkavoos** [comment]
> https://github.com/status-im/nimbus-eth2/pull/4847
> 
> 23.4.0 includes the new option "--local-block-value-boost" with the comment:
> 
> _"as long as its value is within the specified percentage of the value advertised by the best external builder. Setting this flag to a non-zero value is recommended because the usage of an external builder introduces an additional risk that the advertised block won't be published by the builder"_
> 
> However the notes aren't clear on how the value should be specified and it's not yet in the docs as far as I could see.
> 
> Please could you provide a few examples, e.g. would:
> 
> `--local-block-value-boost=1`
> 
> Mean that if the local block fee capture was within 1% of the external builder proposal, then the local block would be used instead? Or should the percentage be specified in some other way?
> 
> Also, I note that mev_boost already includes an option for specifying a minimum eth fee value for using the external builder block. Should these two options be used in tandem?
> 
> 
>

**Comment by Xexr** [comment]
Any clarity on this? Thank you

**Comment by kdeme** [comment]
> Mean that if the local block fee capture was within 1% of the external builder proposal, then the local block would be used instead?

A bit late on reply here, but yes, that's what it means.

The calculation done is basically: 
Use the builder block `if ( builderValue * 100 >  engineValue * (localBlockValueBoost + 100))`
