### ISSUE TITLE
Address comments from #46

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#49]
cc @tersec @arnetheduck

**Comment by tersec** [comment]
I've picked up some of the comments via https://github.com/status-im/nim-beacon-chain/tree/WorkPoolUpdates especially regarding incremental combining of results.

Not proposing ready for merging, etc. More to come.

**Comment by tersec** [comment]
Comments addressed (in #46 and in code in branch linked).

**Comment by tersec** [comment]
Probably mutually exclusive with https://github.com/status-im/nim-beacon-chain/pull/53

**Comment by tersec** [comment]
Closing in favor of https://github.com/status-im/nim-beacon-chain/pull/56
