### ISSUE TITLE
Validator adds :5052 to https URLs erroneously

### ISSUE THREAD

**Issue by jshufro** [status-im/nim-beacon-chain#4920]
**Describe the bug**
As of either 23.4 or 23.5, passing `--beacon-node=https://nimbus.redacted.com` results in the validator attempting to connect to `https://nimbus.redacted.com:5052` instead of the correct port (443).

Previous versions did not exhibit this behavior. Explicitly passing a url ending in `:443` is a workaround.

**To Reproduce**
1. Platform details (OS, architecture): Linux
2. Branch/commit used: statusim/nimbus-validator-client:multiarch-v23.5.0
3. Commands being executed: ```/home/user/nimbus_validator_client --non-interactive --beacon-node=https://nimbus.redacted.com``` (truncated)
4. Relevant log lines: ```NOT 2023-05-09 17:38:37.801+00:00 Beacon node initialized                    node="https://nimbus.redacted.com:5052" node_index=0 node_roles=AGBSD```

**Comment by jshufro** [comment]
At a glance, this seems suspect:
https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/validator_client/common.nim#L525-L532

If scheme is `http` i would argue this should use port 80, and `https` should use 443, so this whole conditional block is probably unnecessary

**Comment by zah** [comment]
Resolved by https://github.com/status-im/nimbus-eth2/pull/4921
The fix was shipped in the `v23.5.1` release of Nimbus.
