### ISSUE TITLE
Build error: missing blst library?

### ISSUE THREAD

**Issue by ericaltendorf** [status-im/nim-beacon-chain#4972]
**Describe the bug**
Fresh install following https://nimbus.guide/build.html seems to produce a build error.

**To Reproduce**
1. Platform: Ubuntu server 22.04 5.15.0-72-generic
2. Branch/commit used: commit 40253a76ddcfd2aa29ef662bb8ee61306093fd1c (HEAD -> stable, tag: v23.5.0, origin/stable, origin/HEAD)

Commands being executed:

```
sudo apt-get install chrony
sudo apt install build-essential git cmake
git clone https://github.com/status-im/nimbus-eth2
cd nimbus-eth2/
make -j4 nimbus_beacon_node
```

Log:

```
[...]
Building: install/usr/lib/libbacktrace.a
Building: Nim compiler
Building: install/usr/lib/libbacktracenim.a
Building: build/generate_makefile
Build completed successfully: build/generate_makefile
Building: build/nimbus_beacon_node
/home/eth/nimbus-eth2/vendor/nim-blscurve/blscurve/blst/blst_lowlevel.nim(12, 10) Error: cannot find: ../../vendor/blst/build/assembly.S
make: *** [Makefile:415: nimbus_beacon_node] Error 1
```

**Additional context**
No `blst` dir exists:
```
$ ls -d vendor/*bls*
vendor/nim-blscurve
```

**Comment by arnetheduck** [comment]
`make update` should repair the checkout in case of missing dependencies (which can happen if connectivity is poor)

**Comment by ericaltendorf** [comment]
Got it, thanks, that seems to have fixed it.
