### ISSUE TITLE
Move CI linters to separate job

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#5182]
The copyright year / branch checks etc currently prevent testing on linux - instead, they should run in their own little category and block auto-merge from there so that all "normal" tests can run as usual

**Comment by tersec** [comment]
How are the copyright year checks preventing testing?

**Comment by arnetheduck** [comment]
they run before the unit tests and fail the job before testing begins

**Comment by arnetheduck** [comment]
https://github.com/status-im/nimbus-eth2/actions/runs/5508861794/jobs/10040733882?pr=5176

**Comment by etan-status** [comment]
As for the branch checks, updating `.gitmodules` to point to the dev branch lets the tests run, and also fixes `git submodule update --remote` to track the correct branch.

Overall, having a separate lint step would still be cleaner, but this unblocks testing at least.

**Comment by arnetheduck** [comment]
> As for the branch checks, updating .gitmodules to point to the dev branch lets the tests run, and also fixes git submodule update --remote to track the correct branch.

this is worse than what the check is trying to prevent: an accidental commit of the PR would mess up both gitmodules and the commit pointers

**Comment by tersec** [comment]
> https://github.com/status-im/nimbus-eth2/actions/runs/5508861794/jobs/10040733882?pr=5176

This is the branch check, not the copyright check.
