### ISSUE TITLE
Startup time.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-beacon-chain#528]
Because of `nim-nat-traversal` package we have more then 120sec of startup time in case of:
1. No UPNP and NAT-PMP routers available.
2. Router present but with blocked UPNP functionality.

**Comment by stefantalpalaru** [comment]
I proposed an upstream patch that would solve this: https://github.com/miniupnp/libnatpmp/pull/15

**Comment by stefantalpalaru** [comment]
Please test it like this, @cheatfate:

```sh
git pull
make clean
make -j4 update
make clean-testnet0 testnet0
```
