### ISSUE TITLE
Migrate to non-embedded network metadata

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#5339]
The Holesky testnet features a 205 MB genesis state (~100MB when compressed with zstd/snappy), which makes embedding it in the binary less practical for day-to-day development (every build of Nimbus will be slowed down due to the large resulting binary size).

We can migrate either to releases featuring network metadata files as directories or we can introduce some support for loading compressed metadata (e.g. `holesky.tar.snappy` or a similar format).

**Comment by tersec** [comment]
Implemented via https://github.com/status-im/nimbus-eth2/pull/5337 and https://github.com/status-im/nimbus-eth2/commit/c7db7d0f2c2cc2de72c5689854e7eb474992edf2
