### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by gcareid** [status-im/nim-beacon-chain#5456]
Versions v23.8.0 and v23.9.0 leak file descriptors.

1. Platform details (OS, architecture): Ubuntu 22.04.3 LTS on Armbian (Orange Pi 5)
2. Branch/commit used: v23.8.0 and v23.9.0 (v23.7.0 is OK)
3. Commands being executed: --network=mainnet --data-dir=/home/ethereum/.nimbus-beacon --web3-url=http://127.0.0.1:8551 --rest --rest-address=0.0.0.0 --jwt-secret=/etc/ethereum/jwtsecret --metrics --metrics-address=0.0.0.0 --tcp-port=9001 --udp-port=9001 --enr-auto-update --payload-builder=true --payload-builder-url=http://localhost:18550
4. Relevant log lines: Nothing obvious in the logs.

![Graph of FD vs peers](https://i.ibb.co/mJbL3hR/fdleak.png)

**Comment by arnetheduck** [comment]
This is a somewhat rare but known issue that's been with us for a bit longer than 23.8 - it's related to when timeouts happen in various between vc/bn/el - specially in periods of higher resource usage or hardware right on the edge - a fix is being tested in `unstable`. 

In the meantime, something that could potentially help is overclocking the board slightly which should give some breathing space while we get the fix to a release (23.9 most likely).

**Comment by gcareid** [comment]
Fixed as of 23.10.0
