### ISSUE TITLE
Submit attestations for slashing validation in batch

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#5466]
On large setups (ie 64-validators+), we end up creating several attestations per slot on average - currently, we perform slashing protection checks on these attestations one-by-one, recording the result in the database before signing.

Each slashing protection database updated is protected by fsync (implicit in sqlite transaction) to ensure that it is written to disk before we sign and send it - this creates significant fsync traffic when used with a high-latency drive (such as a HDD or a virtual host).

Instead of submitting them one by one to the check, we can perform all slashing tests in a single sqlite transaction and bulk-write it to disk thus amortizing the cost..

Testing on my 5k-validators holesky node reveals that on a moderately fast HDD, 150 attestations take ~4s to submit - on the same machine using an SSD instead it takes <100ms - it's obviously much faster but still wasteful.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/5604
