### ISSUE TITLE
Unrecognized option 'trusted-node-url'

### ISSUE THREAD

**Issue by jgresham** [status-im/nim-beacon-chain#5511]
**Describe the bug**
Running nimbus beacon node with the `--trusted-node-url` flag returns an error:
```
Unrecognized option 'trusted-node-url'
Try nimbus_beacon_node --help for more information.
```

**To Reproduce**
1. Platform details (OS, architecture): Ubuntu 23.04, x86_64, podman 4.6.0
2. Branch/commit used: docker.io/statusim/nimbus-eth2:multiarch-latest (23.10.0)
3. Commands being executed: `podman run -q -d --name nimbus-beacon -v "/home/userName/.config/NiceNode/nodes/nimbus-beacon-1697649838":/home/user/data:z -p 9000:9000/tcp -p 9000:9000/udp -p 5052:5052 --user 0 docker.io/statusim/nimbus-eth2:multiarch-latest --data-dir=/home/user/data --web3-url=http://host.containers.internal:8551 --jwt-secret=/home/user/data/jwtsecret --rest --rest-port=5052 --rest-address=0.0.0.0 --rest-allow-origin="http://localhost" --network=mainnet --trusted-node-url=https://beaconstate.ethstaker.cc`
4. Relevant log lines: 2 log lines above

**Screenshots**

**Additional context**
Nimbus starts syncing correctly after removing the `--trusted-node-url`

**Comment by arnetheduck** [comment]
The `--trusted-node-url` option currently only works for the `trustedNodeSync` sub-command - see https://nimbus.guide/trusted-node-sync.html (which you run separately)
