### ISSUE TITLE
[Test suite] The "check" template doesn't allow custom error messages

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#553]
One of the issue with nim unittest is that it doesn't allow custom error messages on failure.

The default behaviour is nice in pure Nim code:
- you get a printout of the line having an issues
- you get the values

But with external fixtures loaded from hundreds of files we don't know which files triggered the failure.

This is especially a problem for SSZ tests. A new error handling would be more helpful.

The following macros that I use for lightweight design by contract with good error printout can be repurposed for the test suite.

```Nim
import macros, os

# A simple design-by-contract API
# ----------------------------------------------------------------------------------

# Everything should be a template that doesn't produce any code
# when PI_Asserts is not defined.
# Those checks are controlled by a custom flag instead of
# "--boundsChecks" or "--nilChecks" to decouple them from user code checks.
# Furthermore, we want them to be very lightweight on performance

# TODO auto-add documentation

proc inspectInfix(node: NimNode): NimNode =
  ## Inspect an expression,
  ## Returns the AST as string with runtime values inlined
  ## from infix operators inlined.
  proc inspect(node: NimNode): NimNode =
    case node.kind:
    of nnkInfix:
      return newCall(
          bindSym"&",
          newCall(
            bindSym"&",
            newCall(bindSym"$", inspect(node[1])),
            newLit(" " & $node[0] & " ")
          ),
          newCall(bindSym"$", inspect(node[2]))
        )
    of {nnkIdent, nnkSym}:
      return node
    else:
      return node.toStrLit()
  return inspect(node)

macro assertContract(
        checkName: static string,
        predicate: untyped) =
  let lineinfo = lineinfoObj(predicate)
  let file = extractFilename(lineinfo.filename)
  let debug = "\n    Contract violated for " & checkName & " at " & file & ":" & $lineinfo.line &
              "\n        " & $predicate.toStrLit &
              "\n    The following values are contrary to expectations:" &
              "\n        "
  let values = inspectInfix(predicate)

  result = quote do:
    when compileOption("assertions"):
      assert(`predicate`, `debug` & `values`)
    elif defined(PI_Asserts):
      if unlikely(not(`predicate`)):
        raise newException(AssertionError, `debug` & `values`)

# A way way to get the caller function would be nice.

template preCondition*(require: untyped) =
  ## Optional runtime check before returning from a function
  assertContract("pre-condition", require)

template postCondition*(ensure: untyped) =
  ## Optional runtime check at the start of a function
  assertContract("post-condition", ensure)

template ascertain*(check: untyped) =
  ## Optional runtime check in the middle of processing
  assertContract("transient condition", check)

# Sanity checks
# ----------------------------------------------------------------------------------

when isMainModule:
  proc assertGreater(x, y: int) =
    postcondition(x > y)

  # We should get a nicely formatted exception
  assertGreater(10, 12)
```

**Comment by zah** [comment]
The previous test suite was defining was treating each YAML file as a separate test suite and each serialized value as a separate test case.

You can use the unittest module's `checkpoint` API to create extra messages that will be displayed only in case of failure.

**Comment by zah** [comment]
I was particularly fond of the following code in the test runner, which was able to re-run any failing test with SSZ tracing enabled:

https://github.com/status-im/nim-beacon-chain/blob/f95af56bf7f5c78c73f93b0f8308cb94c8384d85/tests/official/test_fixture_ssz_static.nim#L81-L104

This allowed me to quickly iterate though the failures.

**Comment by mratsim** [comment]
The SSZ tests now display the file path https://github.com/status-im/nim-beacon-chain/blob/a84a8ba192e2f4c7bae22470b44b2db12f95ab0f/tests/official/test_fixture_operations_attestations.nim#L36-L41

And also have a diff to narrow down differing fields in a complex BeaconState object:

https://github.com/status-im/nim-beacon-chain/blob/a84a8ba192e2f4c7bae22470b44b2db12f95ab0f/tests/helpers/debug_state.nim#L58-L96
