### ISSUE TITLE
Nimbus VC doesn't prune the slashing db on holesky

### ISSUE THREAD

**Issue by yokem55** [status-im/nim-beacon-chain#5540]
**Describe the bug**
The nimbus_validator_client doesn't appear to prune old attestations out of the `signed_attestations` table in the `slashing-protection.sqlilte3` db on holesky node + vc with 5K validators. The database then has unbounded growth, reducing performance of attestations over time. 

**To Reproduce**
1. Platform details (OS, architecture): linux amd64
2. Branch/commit used: Nimbus validator client v23.10.0-8b07f4-stateofus
3. Commands being executed: `/usr/local/bin/nimbus_validator_client --non-interactive --beacon-node=http://127.0.0.1:5052 --block-monitor-type=event --data-dir=/srv/holesky_data/vc-1 --validators-dir=/srv/holesky_data/keys/ --secrets-dir=/srv/holesky_data/secrets/ --doppelganger-detection=false --suggested-fee-recipient=0xAAAAAAA0 --metrics --metrics-address=0.0.0.0 --metrics-port=8121 --graffiti=Stuff`
4. Relevant log lines: N/A. But for a given validator index in the slashing db (1), there are currently 267 epochs in the db for the validator since I last manually pruned the slashing db with dark magic that shouldn't be discussed in public. It repeats even when I 'safely' shutdown the vc, delete the slashing db all together, wait 2 epochs, and start up again. 
```
sqlite> select count(validator_id) from signed_attestations where validator_id = 1;
267
```

**Screenshots**
N/a

**Additional context**
This is a very large holesky node with 5k keys. It's possible I guess that the large number is contributing to this? I can break a few of the validators off to run in a different vc instance if desired for testing.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/5551
