### ISSUE TITLE
Crash: Error: unhandled exception bitseqs.nim(266, 12) `b.len == alen`  [AssertionDefect]

### ISSUE THREAD

**Issue by celeduc** [status-im/nim-beacon-chain#5609]
**Describe the bug**
Beacon node crashed after two weeks running uninterrupted with "Error: unhandled exception: /home/user/nimbus-eth2/vendor/nim-ssz-serialization/ssz_serialization/bitseqs.nim(266, 12) `b.len == alen`  [AssertionDefect]'"

**To Reproduce**
1. Ubuntu 22.04.3 LTS (fully patched), Intel 12th Gen Core i9-12900H
2. nimbus-eth2_Linux_amd64_23.10.1_d19ffcaa
3. Commands being executed: './run-mainnet-beacon-node.sh --rest --subscribe-all-subnets --nat:extip:IP --jwt-secret=/home/user/secret.jwt --el=http://127.0.0.1:8551 --payload-builder=true --payload-builder-url=http://127.0.0.1:18550 --suggested-fee-recipient=0xetc --metrics --metrics-port=8008 --doppelganger-detection=off'
4. Relevant log lines: 'INF 2023-11-19 20:30:28.314+00:00 Attestation sent                           topics="message_router" attestation="(aggregation_bits: 0b0000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, data: (slot: 7800150, index: 11, beacon_block_root: \"e1d16f5c\"
, source: \"243753:df0fc372\", target: \"243754:f22a4329\"), signature: \"a3a1d79a\")" delay=1s313ms874us553ns subnet_id=11                                                                                        
 peers: 160 ❯ finalized: 909d3a22:243752 ❯ head: e1d16f5c:243754:22 ❯ time: 243754:22 (7800150) ❯ sync: s                                                                                                          
 peers: 160 ❯ finalized: 909d3a22:243752 ❯ head: e1d16f5c:243754:22 ❯ time: 243754:22 (7800150) ❯ sync: s                                                                                                          
 peers: 160 ❯ finalized: 909d3a22:243752 ❯ head: e1d16f5c:243754:22 ❯ time: 243754:22 (7800150) ❯ sync: s                                                                                                          
 peers: 160 ❯ finalized: 909d3a22:243752 ❯ head: e1d16f5c:243754:22 ❯ time: 243754:22 (7800150) ❯ sync: s                                                                                                          
 peers: 160 ❯ finalized: 909d3a22:243752 ❯ head: e1d16f5c:243754:22 ❯ time: 243754:22 (7800150) ❯ sync: synced 1728.092801346                                                                                      
 ETH: 1728.092801346 /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(508) main                                                                                                             
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(501) NimMain                                                                                                                               
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2298) main                                                                                                                                              
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2139) handleStartUpCmd                                                                                                                                  
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2040) doRunBeaconNode                                                                                                                                   
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1806) start                                                                                                                                             
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1753) run                                                                                                                                               
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(268) poll                                                                                                                                          
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue                                                                                                                            
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsubpeer.nim(156) handle                                                                                                                        
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsub.nim(359) handler                                                                                                                           
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsub.nim(264) rpcHandler                                                                                                                        
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim(381) rpcHandler                                                                                                                     
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue                                                                                                                            
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim(461) rpcHandler                                                                                                                     
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim(302) validateAndRelay                                                                                                               
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue                                                                                                                            
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim(307) validateAndRelay                                                                                                               
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsub.nim(514) validate                                                                                                                          
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsub.nim(514) validate                                                                                                                          
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue                                                                                                                            
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsub.nim(522) validate                                                                                                                          
/home/user/nimbus-eth2/beacon_chain/networking/eth2_network.nim(2497) execValidator                                                                                                                                
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(1593) colonanonymous                                                                                                                               
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue                                                                                                                            
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncmacro2.nim(208) anonymous                                                                                                                                   
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1597) anonymous                                                                                                                                         
/home/user/nimbus-eth2/beacon_chain/gossip_processing/eth2_processor.nim(421) processSignedAggregateAndProof                                                                                                       
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue                                                                                                                            
/home/user/nimbus-eth2/beacon_chain/gossip_processing/eth2_processor.nim(445) processSignedAggregateAndProof                                                                                                       
/home/user/nimbus-eth2/beacon_chain/gossip_processing/gossip_validation.nim(736) validateAggregate   
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue
/home/user/nimbus-eth2/beacon_chain/gossip_processing/gossip_validation.nim(815) validateAggregate
/home/user/nimbus-eth2/beacon_chain/consensus_object_pools/attestation_pool.nim(400) covers
/home/user/nimbus-eth2/beacon_chain/consensus_object_pools/attestation_pool.nim(291) covers
/home/user/nimbus-eth2/vendor/nim-ssz-serialization/ssz_serialization/bitseqs.nim(266) isSubsetOf
/home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(38) failedAssertImpl
/home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(28) raiseAssert
/home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(54) sysFatal
[[reraised from:
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(508) main
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(501) NimMain
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2298) main
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2139) handleStartUpCmd
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2040) doRunBeaconNode
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1806) start
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1753) run
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(268) poll
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsubpeer.nim(156) handle
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsub.nim(359) handler
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsub.nim(264) rpcHandler
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim(381) rpcHandler
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim(461) rpcHandler
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/gossipsub.nim(302) validateAndRelay
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncmacro2.nim(213) validateAndRelay
]]
[[reraised from:
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(508) main
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(501) NimMain
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2298) main
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2139) handleStartUpCmd
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2040) doRunBeaconNode
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1806) start
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1753) run
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(268) poll
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsubpeer.nim(158) handle
]]
[[reraised from:
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(508) main
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(501) NimMain
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2298) main
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2139) handleStartUpCmd
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2040) doRunBeaconNode
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1806) start
/home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1753) run
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(268) poll
/home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(323) futureContinue
/home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/protocols/pubsub/pubsubpeer.nim(167) handle
]]
Error: unhandled exception: /home/user/nimbus-eth2/vendor/nim-ssz-serialization/ssz_serialization/bitseqs.nim(266, 12) `b.len == alen`  [AssertionDefect]'

**Comment by tersec** [comment]
Fixed in `unstable` and upcoming v23.11.0.
