### ISSUE TITLE
Feature: Implement keymanager graffiti API endpoint

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nim-beacon-chain#5657]
**Is your feature request related to a problem? Please describe.**

Users cannot set a per-validator graffiti without manually changing json files

**Describe the solution you'd like**

Implement keymanager graffiti endpoints so user can use `ethd keys get|set|delete-graffiti`

**Additional context**

Very similar to the `gas-limit` endpoint. See https://ethereum.github.io/keymanager-APIs/?urls.primaryName=dev#/Graffiti

**Comment by xrchz** [comment]
For reference what are the JSON files we can edit as a workaround in the meantime? (If the validator is imported via API)

**Comment by tersec** [comment]
> For reference what are the JSON files we can edit as a workaround in the meantime? (If the validator is imported via API)

Either [`keystore.json` or `remote_keystore.json`](https://nimbus.guide/data-dir.html#secrets-and-validators), depending on whether it's a local or remote keystore.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/6054
