### ISSUE TITLE
Invalid JWT signature if --el is not specified

### ISSUE THREAD

**Issue by lgaroche** [status-im/nim-beacon-chain#5665]
**Bug description**
By default, the nimbus node connects to a local EL client on `http://127.0.0.1:8551`, if the `--el` option is omitted. When doing so, the JWT is rejected by the EL (I'm using Reth).
If I explicitly specify the command line option `--el=http://127.0.0.1:8551`, then the clients can communicate well. 

**To Reproduce**
Nimbus version: `v23.11.0-3a527d-stateofus`
Reth version: `0.1.0-alpha.13`
OS: `Rocky Linux 9 5.14.0-362.8.1.el9_3.x86_64`
Running EL and CL on the same host. IPTables are open (all ACCEPT)

Reth is running, listening on localhost port 8551.

Start nimbus without `--el`flag:
```bash
/build/nimbus_beacon_node --network:mainnet --jwt-secret=/root/.local/share/reth/mainnet/jwt.hex
```

Bug: JWT error: 
In Nimbus logs: `WRN 2023-12-12 16:07:26.078+01:00 Failed to exchange transition configuration topics="elmon" url=http://127.0.0.1:8551 err=Unauthorized`
In Reth logs: `2023-12-12T15:07:26.078366Z ERROR engine::jwt-validator: Invalid JWT: provided signature is invalid`

Start nimbus with the flag:
```bash
./build/nimbus_beacon_node --network:mainnet --el=http://127.0.0.1:8551 --jwt-secret=/root/.local/share/reth/mainnet/jwt.hex
```
Then there's no error.

**Expected behavior**
As the default EL Url is the same as the one I specify, it should work without the flag.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/5671
