### ISSUE TITLE
Cleanup testutil

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#581]
The file https://github.com/status-im/nim-beacon-chain/blob/b643ee945e7cfe0717bff9a7578d58e14a7219c3/tests/testutil.nim#L8-L14 has a lot of obsolete stuff related to mocking.

However it is imported in most test files just for the "preset()" proc
https://github.com/status-im/nim-beacon-chain/blob/b643ee945e7cfe0717bff9a7578d58e14a7219c3/tests/testutil.nim#L16-L17

This is brings in lots of unused dependencies for simple tests: BearSSL, Chronos, Patricia Tries, DB types, libp2p, the entire state transitions.

BearSSL is particularly an issue because it can't be cached by the Nim compiler as it is a C library.

**Comment by tersec** [comment]
Closing because the specific issue referenced is now fixed. Further refactoring can be useful, but the problem posed is solved.
