### ISSUE TITLE
`/eth/v3/validator/blocks/{slot}` not returning consensus value

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#5830]
**Describe the bug**

A call to `/eth/v3/validator/blocks/{slot}` is not returning the consensus value in either the headers or the returned JSON.

The start of the JSON returned by this call for a sample slot:

```
{"version":"capella","execution_payload_blinded":"false","execution_payload_value":"27526787717857859","data":{"slot":"4212523",
```

Note no `consensus_block_value`.

**Additional context**

```
nimbus_beacon_node --version
Nimbus beacon node v24.1.2-6c63a5-stateofus
Copyright (c) 2019-2024 Status Research & Development GmbH

eth2 specification v1.4.0-beta.6

Nim Compiler Version 1.6.18 [Linux: amd64]
```

**Comment by tersec** [comment]
As an immediate observation, it should provide this value if and only `value.consensusValue.isSome`:
https://github.com/status-im/nimbus-eth2/blob/7c731a2bfb4820ef5c08e5e35df635b986ed4857/beacon_chain/spec/eth2_apis/eth2_rest_serialization.nim#L3397-L3399

The code is there, but for some reason, it doesn't have a consensus value. https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Validator/produceBlockV3 doesn't have this logic, though -- it's unconditionally present. https://github.com/ethereum/beacon-APIs/blob/92287015075ff9eaefcd9dcaa4a90191187640c7/apis/validator/block.v3.yaml#L108-L110 similarly specifies this.

I would note that the current released version of https://ethereum.github.io/beacon-APIs/?urls.primaryName=v2.4.2#/Validator/produceBlockV3 is satisfied by Nimbus's response.

**Comment by tersec** [comment]
In progress in https://github.com/status-im/nimbus-eth2/pull/5873

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/5873
