### ISSUE TITLE
Allow providing suggestedFeeRecipient as a file

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#5832]
**Is your feature request related to a problem? Please describe.**
I consider the suggested fee recipient address to be sensitive data and I would prefer to treat them as a secret.

It is easier to manage secrets as separate files, and in some cases like on NixOS they have to be a file to be provided.

**Describe the solution you'd like**
Either the same flag checks if it was given an address or a path, or a separate `--suggested-fee-recipient-file` flag.

**Describe alternatives you've considered**
None.

**Additional context**
Solutions like [Agenix](https://github.com/ryantm/agenix) and others provide secrets only as files which become available at runtime only, since using variables in Nix configuration would result in secrets ending up in the Nix store.

**Comment by kdeme** [comment]
I think you could make use of the yaml config file for that: https://nimbus.guide/options.html#configuration-files

**Comment by jakubgs** [comment]
But I don't want to handle the whole file as a secret, just the fee address.

**Comment by tersec** [comment]
How is something which shows up in plaintext in the block on chain a secret?

**Comment by jakubgs** [comment]
Because you might want to avoid the association of a wallet address and yourself?

**Comment by tersec** [comment]
I mean, again, in plaintext for blocks on chain. If that validator never proposes, then it's moot. If it does, then the world will see it anyway, no?

I guess I'm missing or misunderstanding something.

**Comment by jakubgs** [comment]
I forgot to mention that my configuration is public:
https://github.com/jakubgs/nixos-config/blob/master/roles/nimbus-eth2.nix

Considering the fee recipient address can be looked up on the chain and associated with specific nodes and validators I do not want to include it in my configuration without encrypting it and treating it as a secret. And because secrets in NixOS have to be files which are created at runtime I would like to provide it as a file, rather than having to treat the whole configuration as a secret. Effectively negating the declarative nature of NixOS for this particular service.

**Comment by cheatfate** [comment]
@jakubgs you can store `suggestedFeeRecipient` in file called `suggested_fee_recipient.hex` in hexadecimal form inside your validator directory.

**Comment by jakubgs** [comment]
Oh, that's neat! That would work for me.

I see this mentioned here: https://nimbus.guide/data-dir.html#secrets-and-validators
But I see no mention of this in: https://nimbus.guide/suggested-fee-recipient.html

**Comment by tersec** [comment]
So this is a documentation issue now, not a missing-functionality issue?

**Comment by jakubgs** [comment]
Ah, forgot to close it.

**Comment by jakubgs** [comment]
I still think a `--suggested-fee-recipient-file` flag would be nice.
