### ISSUE TITLE
REST endpoint fails to accept connections and times out

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#5838]
**Describe the bug**
The REST API endpoint for `unstable` node on `linux-01.ih-eu-mda1.nimbus.prater` has become quite unresponsive recently:
```
admin@linux-01.ih-eu-mda1.nimbus.prater:~ % curl --max-time 5 0:9302/eth/v1/validator/duties/proposer/234407
curl: (28) Operation timed out after 5001 milliseconds with 0 bytes received
```
The result is that the http://unstable.prater.beacon-api.nimbus.team/ endpoint is showing as unavailable most of the time:

![image](https://github.com/status-im/nimbus-eth2/assets/2212681/4a80aa32-991e-40f2-85b1-ef1961fdd7e5)

**Logs**
```json
{"lvl":"DBG","ts":"2024-01-29 18:57:03.515+00:00","msg":"Received request","topics":"beacnde","peer":"178.128.252.209:44886","meth":"GET","uri":"/eth/v1/node/version"}
{"lvl":"DBG","ts":"2024-01-29 18:57:03.515+00:00","msg":"Serving API request","topics":"beacnde","peer":"178.128.252.209:44886","meth":"GET","uri":"/eth/v1/node/version","path_params":"[]","query_params":"[]","content_body":"(None)"}
{"lvl":"DBG","ts":"2024-01-29 18:57:03.516+00:00","msg":"Received response from handler","topics":"beacnde","status":200,"meth":"GET","peer":"178.128.252.209:44886","uri":"/eth/v1/node/version","content_type":"application/json","content_size":54}
{"lvl":"DBG","ts":"2024-01-29 18:57:03.516+00:00","msg":"Error occured while sending response","topics":"beacnde","meth":"GET","peer":"178.128.252.209:44886","uri":"/eth/v1/node/version","reason":"Unable to send response, reason: Stream finished or remote side dropped connection"}
```

**Additional context**
This node is running current `unstable` branch and the issues have started few weeks ago but they appear to be more severe now. A node restart does fix the issue temporarily.

The cause is most probably related to the endpoint being exposed publicly.

**Comment by jakubgs** [comment]
We might be seeing some kind of issue with freeing sockets:

![image](https://github.com/status-im/nimbus-eth2/assets/2212681/558df6b0-5fa5-4d1c-a73d-90a829de2b81)

https://grafana.infra.status.im/d/QCTZ8-Vmk/single-host-dashboard?orgId=1&refresh=1m&var-host=linux-01.ih-eu-mda1.nimbus.prater&from=1706382141252&to=1706554941252

**Comment by jakubgs** [comment]
It appears the `unstable` node on `linux-01.ih-eu-mda1.nimbus.mainnet` for Mainnet has the same issue:

![image](https://github.com/status-im/nimbus-eth2/assets/2212681/971b7622-4ec5-4d48-9061-994ea7504718)

Though the socket graph looks a bit different:

![image](https://github.com/status-im/nimbus-eth2/assets/2212681/0b3528d7-c685-4a5f-a0cf-cb3fded7751b)

**Comment by jakubgs** [comment]
Same behavior again:
```
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % curl --max-time 5 0:9302/eth/v1/node/version                    
curl: (28) Operation timed out after 5000 milliseconds with 0 bytes received
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % curl --max-time 10 0:9302/eth/v1/node/version
{"data":{"version":"Nimbus/v24.1.1-0e63f8-stateofus"}}%  
```
Sometimes it does work tho.

**Comment by jakubgs** [comment]
Not sure if this socket usage growth is at fault, possibly:

![image](https://github.com/status-im/nimbus-eth2/assets/2212681/2eeb601d-d9af-4a56-b221-c2da66d65d90)

**Comment by jakubgs** [comment]
It's not files open limit since the currently used number is low:
```
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % sudo ls /proc/$(systemctl show --property MainPID --value beacon-node-mainnet-unstable-01)/fd/ | wc -l
385

jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % s cat beacon-node-mainnet-unstable-01 | grep LimitNOFILE                                              
LimitNOFILE=16384
```

**Comment by jakubgs** [comment]
It doesn't seem to be a firewall issue because I can see the packet attempting to open the connection pass through correctly:
```
PACKET: 2 42017d99 IN=lo LOOPBACK SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x0 TTL=64 ID=17113DF SPORT=33346 DPORT=9304 SYN 
 TRACE: 2 42017d99 raw:PREROUTING:rule:0x2:CONTINUE  -4 -t raw -A PREROUTING -p tcp -m tcp --dport 9304 -j TRACE
 TRACE: 2 42017d99 raw:PREROUTING:return:
 TRACE: 2 42017d99 raw:PREROUTING:policy:ACCEPT 
PACKET: 2 42017d99 IN=lo LOOPBACK SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x0 TTL=64 ID=17113DF SPORT=33346 DPORT=9304 SYN 
 TRACE: 2 42017d99 filter:INPUT:rule:0xc:ACCEPT  -4 -t filter -A INPUT -i lo -m comment --comment "loopback interface" -j ACCEPT
```

**Comment by jakubgs** [comment]
I stopped all the other nodes on `linux-01` on Mainnet to see if freeing up CPU and RAM will make a difference but it doesn't:
```
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % c --max-time 10 0:9304/eth/v1/node/version
curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received
```
So I don't think it's related to high system load or low memory.

**Comment by jakubgs** [comment]
We identified that Prater node doesn't have the `--rest-allow-origin="*"` flag, so we've disabled it on mainnet:

- [`infra-nimbus#cb517650`](https://github.com/status-im/infra-nimbus/commit/cb517650) - nimbus.master: disable wildcard REST API origin

Doubt it will do anything though.

**Comment by jakubgs** [comment]
I cannot see any public REST API endpoint issues currently. It is possible the removal of `--rest-allow-origin="*"` did fix the issue for the publicly exposed nodes. But that does not actually address the underlying issue with the REST API endpoint.

We will continue to monitor for API problems like this, but this particular issue is not resolved, only mitigated on infra side.

**Comment by jakubgs** [comment]
Actually, scratch that. The `testing` node on `geth-02.ih-eu-mda1.nimbus.holesky` is now showing the same symptoms:
```
jakubgs@geth-02.ih-eu-mda1.nimbus.holesky:~ % c --max-time 5 0:9302/eth/v1/node/syncing
curl: (28) Operation timed out after 5001 milliseconds with 0 bytes received
jakubgs@geth-02.ih-eu-mda1.nimbus.holesky:~ % c --max-time 10 0:9302/eth/v1/node/syncing
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
jakubgs@geth-02.ih-eu-mda1.nimbus.holesky:~ % c --max-time 30 0:9302/eth/v1/node/syncing
curl: (28) Operation timed out after 30001 milliseconds with 0 bytes received
```
And it is exposed publicly:
```yaml
  'geth-02.ih-eu-mda1.nimbus.holesky': # 1 each
    - { branch: 'stable',   start:     0, end:     1,  el: 'geth',      vc: true  }
    - { branch: 'testing',  start:     1, end:     2,  el: 'geth',      vc: false, public_api: true }
    - { branch: 'unstable', start:     2, end:     3,  el: 'geth',      vc: false }
    - { branch: 'libp2p',   start:     3, end:     4,  el: 'geth',      vc: false }
```
https://github.com/status-im/infra-nimbus/blob/f446bd309ff4a4e004fb3c42c6e0bc9cbf0b0a0b/ansible/vars/layout/holesky.yml#L11-L15

And it does not have the `--rest-allow-origin` flag:
```
jakubgs@geth-02.ih-eu-mda1.nimbus.holesky:~ % s cat beacon-node-holesky-testing | grep rest-
    --rest-address=0.0.0.0 \
    --rest-port=9302 \
    --rest-max-body-size=16384 \
    --rest-max-headers-size=128 \
```
Which suggests that the `--rest-allow-origin` flag is a red herring.

**Comment by jakubgs** [comment]
Another instance of the issue on `linux-02.ih-eu-mda1.nimbus.mainnet` node `beacon-node-mainnet-testing-01`:
```
jakubgs@linux-02.ih-eu-mda1.nimbus.mainnet:~ % for port in $(seq 9300 9305); do c 0:$port/eth/v1/node/version | jq -c; done
{"data":{"version":"Nimbus/v24.2.0-742f15-stateofus"}}
{"data":{"version":"Nimbus/v24.2.0-742f15-stateofus"}}
curl: (28) Connection timed out after 5001 milliseconds
{"data":{"version":"Nimbus/v24.2.0-742f15-stateofus"}}
{"data":{"version":"Nimbus/v24.2.0-81b849-stateofus"}}
{"data":{"version":"Nimbus/v24.2.0-81b849-stateofus"}}
```

**Comment by cheatfate** [comment]
This issue should be fixed in `unstable`.

**Comment by jakubgs** [comment]
Sure, thanks, any explanation for what was actually happening? I see nothing in the PR or the commit.

**Comment by apentori** [comment]
Almost all  beacon node of the Holesky network built on the branch [nim-libp2p-auto-bump-unstable](https://github.com/status-im/nimbus-eth2/tree/nim-libp2p-auto-bump-unstable) show this  issue this weekend:

```
Get "http://localhost:9304/eth/v1/node/version": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by cheatfate** [comment]
> Almost all beacon node of the Holesky network built on the branch [nim-libp2p-auto-bump-unstable](https://github.com/status-im/nimbus-eth2/tree/nim-libp2p-auto-bump-unstable) show this issue this weekend:
> 
> ```
> Get "http://localhost:9304/eth/v1/node/version": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> ```

Could you please provide some commit hash or something, because `branch` is moving all the time and right now its impossible to verify is this branch had fixes from unstable or not.

**Comment by cheatfate** [comment]
> Sure, thanks, any explanation for what was actually happening? I see nothing in the PR or the commit.

It was an issue some small race condition which exits accept loop so no more connections are being accepted and processed after bug happens. It exists for more than 7 months already, but looks like it get revealed only when host is very busy.

**Comment by jakubgs** [comment]
Thanks for the explanation and more importantly the fix.

I reviewed some of our alerts and I do think this has been resolved. If need be we can always reopen.
