### ISSUE TITLE
Safety Mecanism against validator running on 2 clients

### ISSUE THREAD

**Issue by apentori** [status-im/nim-beacon-chain#5872]
**Is your feature request related to a problem? Please describe.**
On testnet, we run multiple configuration of Nimbus client, some with Beacon Node running at the same time as Validator Client. When changing the layout for various test, it happen that Validator Client and Beacon Node are running with the same validator keys, provoking a slashing of the validator.

**Describe the solution you'd like**
Could it be possible for a BN or VC to have a safety mecanism to avoid slashing when a instance is running with the same validator key ?

**Additional context**

[Postmortem of the slashing incident on Holesky due to validator overlapping](https://github.com/status-im/infra-docs/blob/postmoterm-holesky-sashing-20240131/docs/postmortems/20240131_holesky_validator_slashing.md)

**Comment by tersec** [comment]
Sure, doppelgänger protection. It exists now.

**Comment by apentori** [comment]
Oh I didn't knew that exist, sorry.
It's seems we have it by default : https://github.com/status-im/infra-role-beacon-node-linux/blob/3642b4b5ca13b0a637670c870df1d312e8ff5d99/defaults/main.yml#L48.
Thanks for the information
