### ISSUE TITLE
[v24.2.1] VC crashes during proposals

### ISSUE THREAD

**Issue by jclapis** [status-im/nim-beacon-chain#5960]
**Describe the bug**

The v24.2.1 Validator Client seems to be crashing with a RangeException any time it has to submit a proposal. Sometimes it recovers in time and submits the proposal, sometimes it does not.

VC logs during a crash where it *did not* recover in time:

```
rocketpool_validator  | INF 2024-02-25 08:30:47.003+00:00 Slot start                                 slot=8502152 epoch=265692 attestationIn=4s blockIn=12s validators=15 good_nodes=2 viable_nodes=0 bad_nodes=0 delay=3ms30us602ns
rocketpool_validator  | NTC 2024-02-25 08:30:50.397+00:00 Attestation published                      delay=-602ms342us559ns service=attestation_service validator=a074a34c@267669 attestation="(aggregation_bits: 0b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000, data: (slot: 8502152, index: 37, beacon_block_root: \"79081fa0\", source: \"265691:fc906053\", target: \"265692:cd309d41\"), signature: \"b72f00a3\")"
rocketpool_validator  | NTC 2024-02-25 08:30:50.397+00:00 Attestation published                      delay=-601ms955us531ns service=attestation_service validator=b7138498@430459 attestation="(aggregation_bits: 0b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000, data: (slot: 8502152, index: 24, beacon_block_root: \"79081fa0\", source: \"265691:fc906053\", target: \"265692:cd309d41\"), signature: \"af45821b\")"
rocketpool_validator  | INF 2024-02-25 08:30:59.014+00:00 Slot start                                 slot=8502153 epoch=265692 attestationIn=4s blockIn= validators=15 good_nodes=2 viable_nodes=0 bad_nodes=0 delay=14ms299us955ns
rocketpool_validator  | [[reraised from:
rocketpool_validator  | ]]
rocketpool_validator  | [[reraised from:
rocketpool_validator  | ]]
rocketpool_validator  | [[reraised from:
rocketpool_validator  | ]]
rocketpool_validator  | Error: unhandled exception: value out of range [RangeDefect]
```

then it restarts, loads they keys, gets here, and crashes again immediately:

```
rocketpool_validator  | INF 2024-02-25 08:31:01.351+00:00 Validator indices updated                  pending=0 missing=0 updated=15 elapsed_time=10ms160us727ns service=duties_service
rocketpool_validator  | [[reraised from:
rocketpool_validator  | ]]
rocketpool_validator  | [[reraised from:
rocketpool_validator  | ]]
rocketpool_validator  | [[reraised from:
rocketpool_validator  | ]]
rocketpool_validator  | Error: unhandled exception: value out of range [RangeDefect]
```

this cycle continues several times, either until the slot is missed, or until it can finally submit the block several seconds late. After that it resumes attesting normally. It seems to occur with every proposal duty I've encountered so far, though I've only had 2 since upgrading.

This is on **Mainnet**.

**To Reproduce**
1. Platform details (OS, architecture): Debian bullseye, `arm64`, Docker image `statusim/nimbus-validator-client:multiarch-v24.2.1`
2. Branch/commit used: N/A
3. Commands being executed: `/home/user/nimbus_validator_client --non-interactive --beacon-node=http://eth2:5052 --beacon-node=http://192.168.1.7:5052 --data-dir=/ethclient/nimbus_vc --validators-dir=/validators/nimbus/validators --secrets-dir=/validators/nimbus/secrets --doppelganger-detection=false --suggested-fee-recipient=0xd4E96eF8eee8678dBFf4d535E033Ed1a4F7605b7 --block-monitor-type=event --payload-builder --metrics --metrics-address=0.0.0.0 --metrics-port=9101 --graffiti=RP-GN v1.11.5 (Made on arm64!)`
4. Relevant log lines: (see above)

**Screenshots**

**Additional context**

**Comment by etan-status** [comment]
In this issue, one of the BNs was running an older Nimbus version which provided incorrectly formatted `Eth-Execution-Payload-Value` headers.

This was addressed in Nimbus BN 24.2.1:

- #5741 

However, VC 24.2.1 did not gracefully handle the incorrect format by older BN. This has been fixed:

- #5967 

Updating the BN to 24.2.1 (so that correct value is sent), or the VC to the next version (so that the incorrect value is gracefully handled), should resolve this.

**Comment by etan-status** [comment]
Reproduced using BN 24.1.1 and VC 24.2.1, with stack trace:

<img width="1538" alt="image" src="https://github.com/status-im/nimbus-eth2/assets/89844309/f2350c69-9a14-48ca-961b-1403f15abc64">

That's indeed the problem here, with the `Eth-Execution-Payload-Value` parsing

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/5967
