### ISSUE TITLE
Changing fee recipient with KeyManager API does not trigger mev-boost relayer update without a restart

### ISSUE THREAD

**Issue by nanexcool** [status-im/nim-beacon-chain#5983]
**Describe the bug**
Changing a validator's fee recipient address using the KeyManager API does not trigger an update with mev-boost relayers until the Nimbus client is restarted.

**To Reproduce**
1. Change fee recipient via KeyManager POST call
2. Confirm change via KeyManager GET call
3. Wait a couple of epochs and check relayers data for the validator
4. No change

**Additional context**
Smoothing Pools like Dappnode Smooth or Smoothly check that the validators have the correct fee recipient configured via mev-boost relayer lists. These for now (at least the fee recipient) are only updated when the Nimbus client is restarted.

**Comment by stonp89** [comment]
I experienced this bug as well

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/6412
