### ISSUE TITLE
Polish & Ergonomics & User experience

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#599]
This is a meta issue to track the state of user experience. And have it visible to everyone.

Some issues might be worth a dedicated thread (say a crash), while others might be recurrent (instructions not up to date).

------------------------

- [x] (Week 2019.11.25) Build instructions not up to date at https://github.com/eth2-clients/eth2-testnets/tree/e4a9640bc9d9cf7913bed210b20341eea745ef44/nimbus.
  Those instructions are referred to in: What's new in Eth2 https://notes.ethereum.org/@ChihChengLiang/Sk8Zs--CQ/https%3A%2F%2Fhackmd.io%2F%40benjaminion%2FH12CnGHhr?type=book
- [x] (Week 2019.11.25) Connecting to testnets should be highlighted https://github.com/status-im/nim-beacon-chain#connecting-to-testnets
- [x] (Week 2019.11.25) The meaning of "building" is not clear, probably should be rework to "contributing to nimbus" or "setting up the nimbus build system" https://github.com/status-im/nim-beacon-chain#build--develop. Maybe clearly separating "for users" and "for developers" would be cleaner.
- [x] (Week 2019.11.25) Posix --> Linux, MacOS: https://github.com/status-im/nim-beacon-chain#posix-compatible-os
- [x] (Week 2019.11.25) Validators are exiting every few days on the testnet, for as-yet-undetermined reasons.
- [x] (Week 2019.12.02) Handle gracefully UPNP failures (#626)

**Comment by tersec** [comment]
Validators are exiting every few days on the testnet, for as-yet-undetermined reasons.
