### ISSUE TITLE
Add experimental Yamux support

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#6008]
The latest LibP2P now includes Yamux support. It can be enabled by using the following code when constructing the switch:

```nim
  .withYamux(inTimeout, outTimeout)
  .withMplex(inTimeout, outTimeout)
```

The muxer that gets added first is treated as first choice, the second is a fallback.

We should add a hidden command line option for enabling Yamux and then we should deploy it on a subset of our testnet fleet hosts.

**Comment by tersec** [comment]
> We should add a hidden command line option for enabling Yamux and then we should deploy it on a subset of our testnet fleet hosts.

So long as it's a `--debug-foo` option so that per https://nimbus.guide/options.html#available-options
> Any `debug`-prefixed flags are considered ephemeral and subject to removal without notice.

**Comment by arnetheduck** [comment]
https://github.com/status-im/nimbus-eth2/blob/unstable/beacon_chain/conf.nim#L334

**Comment by tersec** [comment]
> https://github.com/status-im/nimbus-eth2/blob/unstable/beacon_chain/conf.nim#L334

https://github.com/status-im/nimbus-eth2/pull/6010

**Comment by tersec** [comment]
https://github.com/ethereum/consensus-specs/pull/3866#issuecomment-2276195113
