### ISSUE TITLE
Provide a way to detect next proposal time

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#6025]
**Is your feature request related to a problem? Please describe.**
Currently there is a metric called `next_action_wait` which allows to avoid missing an attestation on a node with low number of validators. This is neat and all, but for notes with large numbers of validators that metric isn't really that useful, because you can hardly find more than 30 second between attestations on a node with ~30 validators, which means you might as well just restart without consulting the metric.

**Describe the solution you'd like**
What would be great is a `next_proposal_wait` metric that would allow us to avoid missing proposals, which are far more important.
There's very little harm in missing a few attestations compared to missing a proposal.

**Describe alternatives you've considered**
Alternatively an API endpoint would also be useful. A log message is nice too, but a metric is easier to use in scripts.

**Additional context**
We currently use `next_action_wait` metric a restart script in our Ansible roles:
https://github.com/status-im/infra-role-beacon-node-linux/blob/master/templates/scripts/restart.sh.j2

But it would be great to add support to it for also checking for future proposals.

**Comment by tersec** [comment]
`nextProposalSlot` is in the same `Slot end` log as `nextActionWait`.

**Comment by jakubgs** [comment]
Okay, but can we get a metric?

**Comment by etan-status** [comment]
Would this one work for you?

- https://github.com/status-im/nimbus-eth2/pull/6028

Proposals are not so frequent, so it would be set to `Inf` if time to next one is unknown.

And, also added a boolean one for sync committee – they last ~27hrs though with a signature every 12 seconds, but during that time profit is massively increased so it may still be worthwhile to delay maintenance to the next day if it's not critical?
If you don't need sync committee I can also remove it again from the PR.

**Comment by jakubgs** [comment]
Sync committee metric is also cool, thanks for this.

**Comment by cheatfate** [comment]
You really need a metric for this? We could provide a REST call.

**Comment by tersec** [comment]
There's more value in keeping REST calls to be as close to only-beacon-API as possible. The more Nimbus-specific calls there are, the less interoperability, which partly defeats the point.

Metrics weren't ever broadly interoperable to begin with, so better to put client-specific things in metrics where feasible.

**Comment by jakubgs** [comment]
Also, metrics have more uses than REST API calls. You can actually graph how often and how busy your node is.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/6028

**Comment by jakubgs** [comment]
I checked Prometheus for values of the new metric and it appears to work:

![image](https://github.com/status-im/nimbus-eth2/assets/2212681/b4b79692-11ed-483e-aec5-a5994e7c8d0c)

Thanks.
