### ISSUE TITLE
Unresponsive REST API and bursts of logs

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#6050]
**Describe the bug**
Our `testing-01` node on `linux-02.ih-eu-mda1.nimbus.mainnet` is exposed public under http://testing.mainnet.beacon-api.nimbus.team/.

Recently it has been becoming unresponsive to API calls:
```
jakubgs@linux-02.ih-eu-mda1.nimbus.mainnet:~ % curl -v 0:9301/eth/v1/node/syncing
*   Trying 0.0.0.0:9301...
* connect to 0.0.0.0 port 9301 failed: Connection timed out
* Failed to connect to 0.0.0.0 port 9301 after 129641 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to 0.0.0.0 port 9301 after 129641 ms: Connection timed out
```
And logs behave in a weird way, where nothing is logged for 30 seconds and then a burst of logs appears.

The version is `v24.2.2-fc9c72`.

**Additional context**
Not sure releated but logs contain errors like this:
```json
{
  "lvl": "DBG",
  "ts": "2024-03-08 14:06:42.698+00:00",
  "msg": "Error occured while sending response",
  "topics": "beacnde",
  "meth": "GET",
  "peer": "78.130.168.30:43252",
  "uri": "/eth/v1/beacon/states/8200672/validators?id=25880,25881,25882,25883,25884,25885,25886,25887,25888,25889,25890,25891,25892,25893,25894,25895,25896,25897,25898",
  "reason": "Unable to send response body, reason: Stream finished or remote side dropped connection"
}
```

**Comment by arnetheduck** [comment]
On these servers, a request for a state that old will take time to process - _likely_ the client fetching the data times out before a response can be generated (which is what the error says), and the unresponsiveness is simply an outcome of the server being overloaded with these requests..

for the public-facing servers, the health check should probably have a sensitivity of a few minutes, ie failures under 5 minutes are to be expected during times of load/spam

**Comment by jakubgs** [comment]
Okay, then if you consider this normal behavior for such an overloaded system due to REST API being publicly exposed we can lose this issue. I have already reduced sensitivity of Consul healthchecks anyway for all fleets:

- [`infra-nimbus#d1d762a6`](https://github.com/status-im/infra-nimbus/commit/d1d762a6) - nimbus.fluffy: lower sensitivity for consul checks
- [`infra-nimbus#60dd11a8`](https://github.com/status-im/infra-nimbus/commit/60dd11a8) - holesky,mainnet,sepolia: lower consul sensitivity

And so now these alerts should not trigger most of the time.
