### ISSUE TITLE
Identity REST API endpoint returns 0.0.0.0 address

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#6060]
**Describe the bug**
Currently the `/eth/v1/node/identity` REST API endpoint returns incorrect multiaddress under `p2p_addresses`:
```
jakubgs@linux-01.ih-eu-mda1.nimbus.sepolia:~ % c -s 0:9311/eth/v1/node/identity | jq '.data | { p2p_addresses, discovery_addresses }'
{
  "p2p_addresses": [
    "/ip4/0.0.0.0/tcp/9011/p2p/16Uiu2HAmQEmCoEfKQ7ZdPyw1vkMYPLfosfksRUJwssvyDzAosGgm"
  ],
  "discovery_addresses": [
    "/ip4/185.181.230.77/udp/9011/p2p/16Uiu2HAmQEmCoEfKQ7ZdPyw1vkMYPLfosfksRUJwssvyDzAosGgm"
  ]
}
```
As can be seen the `discovery_addresses` is correctly using the known public IP address - most probably thanks to the correct value of the `--nat=extip:...` flag - while `p2p_addresses` returns `0.0.0.0`.

**Additional context**
Present currently for all 4 main branches:
```
jakubgs@linux-01.ih-eu-mda1.nimbus.sepolia:~ % for port in $(seq 9311 9314); do c 0:$port/eth/v1/node/identity | jq -c .data.p2p_addresses; done
["/ip4/0.0.0.0/tcp/9011/p2p/16Uiu2HAmQEmCoEfKQ7ZdPyw1vkMYPLfosfksRUJwssvyDzAosGgm"]
["/ip4/0.0.0.0/tcp/9012/p2p/16Uiu2HAm5rcnvjSbXMtzosDnGBsgwi5REfxCNCjeqcYDnHf86XsF"]
["/ip4/0.0.0.0/tcp/9013/p2p/16Uiu2HAmCDZ2qDxdoRYdYGYentnSndWfTYuSSh9jzzK3Qc6QGd1q"]
["/ip4/0.0.0.0/tcp/9014/p2p/16Uiu2HAmGXdiCU2VX9GpuTq3GPm28gBncaBLWEcN8MZaskXcYhYb"]
```

**Comment by cheatfate** [comment]
This is `libp2p` known issue and probably limitation.

**Comment by jakubgs** [comment]
What do you mean by "limitation"? I'd assume that If it works for discovery it can be made to work for the p2p address.

**Comment by cheatfate** [comment]
Usually developers prefer to use `0.0.0.0` which forces OS to bound server to all available interfaces. But this comes with limitation that when you will request local address of bound socket you will receive `0.0.0.0:<some port>` instead of real interface address. To get this addresses you need to enumerate all the interfaces and bound to their IP addresses manually. But there is no such functionality in `nim-libp2p` yet, so REST server reports what `nim-libp2p` provides to it.
And to note that that provided multiaddresses are 100% correct, but i agree this addresses are unusable...

**Comment by cheatfate** [comment]
By word "limitation" i mean that `nim-libp2p` developers do not implemented this functionality yet and i have not seen such functionality in plans.

**Comment by jakubgs** [comment]
>To get this addresses you need to enumerate all the interfaces and bound to their IP addresses manually. But there is no such functionality in nim-libp2p yet, so REST server reports what nim-libp2p provides to it.

I though that's what `--nat=extip:...` is for. To avoid having to guess which interface is the correct one.

**Comment by cheatfate** [comment]
`libp2p` should collect its own addresses while talking with other nodes during identify phase. And replace `0.0.0.0` with this addresses.

**Comment by jakubgs** [comment]
I see, well, then I guess the only sensible thing is to patch it after querying the API since fixing this is too difficult?

**Comment by cheatfate** [comment]
One more issue discovered
https://github.com/vacp2p/nim-libp2p/issues/1147

**Comment by cheatfate** [comment]
This issue fixed in `unstable` https://github.com/status-im/nimbus-eth2/pull/6422
