### ISSUE TITLE
POST to `eth/v1/builder/blinded_blocks` missing header

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#6075]
**Describe the bug**

When receiving a POST to `/eth/v1/builder/blinded_blocks` the spec says that we should obtain the version of the blinded block in the `Eth-Consensus-Version` header, however this is not set by Nimbus.

```
Nimbus beacon node v24.2.2-fc9c72-stateofus
Copyright (c) 2019-2024 Status Research & Development GmbH

eth2 specification v1.4.0-beta.7-hotfix

Nim Compiler Version 1.6.18 [Linux: amd64]
```

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/6256
