### ISSUE TITLE
Dump beacon blocks with invalid execution payloads

### ISSUE THREAD

**Issue by Savid** [status-im/nim-beacon-chain#6077]
**Describe the bug**
When the execution payload is invalid for a beacon block, it appears it will never be dumped to the `dump/invalid` directory when the dump flag is enabled.

https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/gossip_processing/block_processor.nim#L499

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/6144
