### ISSUE TITLE
Nimbus CL < > Lodestar VC incompatibility

### ISSUE THREAD

**Issue by barnabasbusa** [status-im/nim-beacon-chain#6176]
### Describe the bug

We are in the process to test cross beacon <> validator client compatibility, and found a bug when testing nimbus CL with lodestar VC. 

Lodestar reports:
```sh
Apr-05 14:25:06.155[]                error: Error proposing block slot=29, validator=0xb05c…679b - JSON expected key slot is undefined - Failed to produce block
Error: JSON expected key slot is undefined - Failed to produce block
    at ContainerType.fromJson (/usr/app/node_modules/@chainsafe/ssz/src/type/container.ts:347:15)
    at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:156:44)
    at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:198:15)
    at Object.fromJson (file:///usr/app/packages/api/src/beacon/routes/validator.ts:778:91)
    at Object.request [as produceBlockV3] (file:///usr/app/packages/api/src/utils/client/client.ts:91:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlockProposingService.produceBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:205:17)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:144:29)
    at async Promise.all (index 0)
```

Nimbus reports:
```sh
nothing out of the ordinary
```

Snooper between cl <> vc reports:
```sh
nothing out of the ordinary
```

### Expected behavior

I would expect all client combinations would work. 

### Steps to reproduce

config.yaml: 
```yaml
participants:
  - cl_type: nimbus
    vc_type: lodestar
additional_services:
  - dora
snooper_enabled: true
global_log_level: debug
```

`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file config.yaml`

### Additional context

[Current BN <> VC Compatibility list tracker](https://github.com/kurtosis-tech/ethereum-package?tab=readme-ov-file#beacon-node--validator-client-compatibility)

![Screenshot 2024-04-05 at 14 08 53](https://github.com/ChainSafe/lodestar/assets/21987084/4ba19a53-36d3-4d39-b563-3dc1f90b2fef)

### Operating system

Linux

### Nimbus version or commit hash

`statusim/nimbus-eth2:multiarch-latest - sha256:8e79e02b37351bdcf0a4b07c9cb5a8dd23afdf83144a0d948644b72884cdd10d`

cc: @pk910

**Comment by barnabasbusa** [comment]
Same issue: https://github.com/ChainSafe/lodestar/issues/6636

**Comment by nflaig** [comment]
A possible reason for this could be that Nimbus is sending execution_payload_blinded as a [string value](https://github.com/status-im/nimbus-eth2/blob/dc19b082a9850bf9333e2371ea22230b61c2d501/beacon_chain/spec/eth2_apis/eth2_rest_serialization.nim#L3365) instead of [boolean as per spec](https://github.com/ethereum/beacon-APIs/blob/fc89ec5c5f0904a0057fc543f0eb4ddaa480f04e/apis/validator/block.v3.yaml#L102-L104).

See https://github.com/ChainSafe/lodestar/issues/6636#issuecomment-2039946095, maybe someone from Nimbus can confirm this, otherwise would require more logs / information about the response payload.

**Comment by kinsi55** [comment]
What nflaig said is correct and will also cause failed proposals with Lighthouse

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/6204
