### ISSUE TITLE
Handle 404 errors in getAggregatedAttestation response

### ISSUE THREAD

**Issue by nflaig** [status-im/nim-beacon-chain#6184]
As per spec the [getAggregatedAttestation](https://ethereum.github.io/beacon-APIs/#/Validator/getAggregatedAttestation) could return a 404 status code if no aggregated attestation is available

[apis/validator/aggregate_attestation.yaml#L11-L12](https://github.com/ethereum/beacon-APIs/blob/fc89ec5c5f0904a0057fc543f0eb4ddaa480f04e/apis/validator/aggregate_attestation.yaml#L11-L12)
> A 404 error must be returned if no attestation is available for the requested `attestation_data_root`.

But it looks like Nimbus does not specifically handle this case right now which would lead to an error that looks critical but are somewhat expected if Nimbus VC is connected to multiple BNs (see https://github.com/ChainSafe/lodestar/issues/6634#issuecomment-2042672443)
https://github.com/status-im/nimbus-eth2/blob/dc19b082a9850bf9333e2371ea22230b61c2d501/beacon_chain/validator_client/api.nim#L1716-L1718

We have been getting user reports about this https://github.com/ChainSafe/lodestar/issues/6631 which we already addressed on the Lodestar bn (https://github.com/ChainSafe/lodestar/pull/6648) but based on how our attestation cache works Lodestar bn might not be able to serve this request.

Maybe Nimbus VC could also consider to log this differently to avoid user concerns, as based on how Nimbus handles this, if one of the connected BNs is not able to serve the request, it's not critical.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/6254
