### ISSUE TITLE
Checkpoint-synced nodes appear to not use ERA files

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-beacon-chain#6275]
**Describe the bug**
During investigation of issue with one of our public API endpoints: https://unstable.mainnet.beacon-api.nimbus.team/

- https://github.com/status-im/nimbus-eth2/issues/6271

It was found out that the endpoint was mapped to the wrong unstable beacon node on `linux-01.ih-eu-mda1.nimbus.mainnet` host.

The node in question had enabled regular checkpoint sync:
```yaml
# Periodic resync to save space
beacon_node_resync_enabled: true
beacon_node_resync_timer_enabled: '{{ (idx % 2 == 1) and not node.get("public_api") }}'
beacon_node_resync_timer_frequency: 'monthly'
```
https://github.com/status-im/infra-nimbus/blob/931c9f38/ansible/group_vars/nimbus.mainnet.yml#L98-L101

But in theory that should not matter for the `/eth/v2/debug/beacon/states/*` requests since the node is configured to use ERA files:
```yaml
beacon_node_era_dir_path: '{{ nimbus_era_files_timer_path }}'
```
https://github.com/status-im/infra-nimbus/blob/931c9f38/ansible/group_vars/nimbus.mainnet.yml#L44

Which can be seen on the host:
```
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % s cat beacon-node-mainnet-unstable-02 | grep era
    --era-dir=/data/era \
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % ls /data/era | wc -l
1101
```
And yet the node was unable to respond to requests like `/eth/v2/debug/beacon/states/9010832` and would fail with:
```json
{"code":404,"message":"Could not get requested state"}
```
Which would suggest that the ERA files were not actually being utilized.

**Additional context**
The `verify` timer runs regularly and succeeds:
```
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % j -ocat -n3 -u nimbus-era-files-verify
nimbus-era-files-verify.service: Deactivated successfully.
Finished Verify Nimbus beacon node ERA files.
nimbus-era-files-verify.service: Consumed 11h 35min 56.961s CPU time.
```
And the ERA files in the `/data/era` folder have no gaps:
```
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % for idx in $(seq -w 1 1100); do ls /data/era/mainnet-0${idx}-* > /dev/null; done
jakubgs@linux-01.ih-eu-mda1.nimbus.mainnet:~ % 
```

**Comment by arnetheduck** [comment]
For era files to be used for state serving in particular, they need to be [reindexed](https://nimbus.guide/trusted-node-sync.html#recreate-historical-state-access-indices) - without that, we can only serve blocks.

**Comment by jakubgs** [comment]
Good to know, thanks.
