### ISSUE TITLE
Require flag when resuming from past-weak-subjectivity database / genesis

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#6306]
This proposal introduces a new flag, `--long-range-sync`, that takes effect whenever the most recent state in the database (or genesis, if no database) is older than the weak subjectivity period and no trusted pivot point is given:

* `--long-range-sync=light`, default - light client protocol is required to verify the long-range sync (https://github.com/metacraft-labs/DendrETH/tree/main/docs/long-range-syncing)
  - client shuts down otherwise with a message suggesting TNS or lenient
* `--long-range-sync=lenient` - allows forward-syncing beyond WSP, including syncing from genesis

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/6361
