### ISSUE TITLE
Metrics/Public Grafana dashboard of the testnet

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#637]
Since the testnet is much more stable, the metrics of the testnet would probably be interesting despite the current star topology.

@djrtwo wanted in particular to view:
- how long block processing takes for a given net/config
- how long fork choice takes
- state hashing
- Running DB size
- and I expect anything else related to memory or performance.

**Comment by zah** [comment]
Thanks to @jakubgs's hard work, we now have a fully public Grafana dashboard for our testnets here:
https://metrics.status.im/d/public/nimbus-metrics?orgId=1

The next step would be implementing more of the requested metrics and tweaking the dashboard to show the most interesting items.

**Comment by mratsim** [comment]
Closed outdated by public testnets
