### ISSUE TITLE
blob_sidecars with empty response

### ISSUE THREAD

**Issue by dwampa** [status-im/nim-beacon-chain#6493]
**Describe the bug**
eth/v1/beacon/blob_sidecars request of an unexisting blob will answer with an empty array.

**To Reproduce**
```shell
curl -X 'GET' \
 'https://BEACON_ENDPOINT/eth/v1/beacon/blob_sidecars/5644698?indices=11' \
 -H 'accept: application/json'
``` 

Response:
```shell
{"data":[]}
```

**Additional context**
Please add the error message instead of an empty array.

**Comment by tersec** [comment]
Where does https://ethereum.github.io/beacon-APIs/#/Beacon/getBlobSidecars specify the behavior/response you're asking for?

**Comment by dwampa** [comment]
@tersec You are correct, it is not there. I guess this should be a feature request rather than a bug then.

**Comment by tersec** [comment]
This "feature request" would be incompatible with the existing beacon API.

**Comment by tersec** [comment]
If you'd like, you can file an issue with https://github.com/ethereum/beacon-APIs/issues but this is an implementation of a specific and specified API.
