### ISSUE TITLE
Nimus as Beacon for pivate chain

### ISSUE THREAD

**Issue by artjoma** [status-im/nim-beacon-chain#6593]
Is it possible setup Nimbus as beacon node for private network ?

**Comment by arnetheduck** [comment]
Yes - all you need to do is to use the `--network:directory` option where `directory` points to a folder containing the configuration of your private network (see https://github.com/eth-clients/mainnet/tree/main/metadata for the format).

This is similar to launching a testnet - see also this script: https://github.com/status-im/nimbus-eth2/blob/stable/scripts/launch_local_testnet.sh

**Comment by artjoma** [comment]
And second question. Is it possible make chain: Geth(execution node) + Nimbus(beacon node) + Prysm (validator node) or validator should be Nimbus ?

**Comment by cheatfate** [comment]
> And second question. Is it possible make chain: Geth(execution node) + Nimbus(beacon node) + Prysm (validator node) or validator should be Nimbus ?

All the validator clients should work over HTTP/REST protocol which specification is here https://ethereum.github.io/beacon-APIs/#/, so if Prysm validator client supports it it can be used to manage Nimbus(beacon node), but there is no benefits on using Prysm validator client over Nimbus validator client, i could even say that Nimbus validator client has features which Prysm does not.

**Comment by arnetheduck** [comment]
you should be able to use prysm as validator as well, as long as you don't use grpc which is their own bn-vc communications protocol - check their docs for how to use the "standard" api.

**Comment by artjoma** [comment]
Thank you guys!
