### ISSUE TITLE
Migrate docker images to debian 12

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#6685]
Per [docs](https://github.com/status-im/nimbus-eth2/blob/unstable/docs/the_nimbus_book/src/docker.md#docker-images), we use debian 11 (bullseye) as base image which reached EOL on [2024-08-14](https://www.debian.org/releases/)

**Comment by tersec** [comment]
- https://github.com/status-im/nimbus-eth2/pull/6740
