### ISSUE TITLE
Unhandled exception: Cannot allocate memory [LmdbError] on Raspberry Pi 4B 4 GB RAM with 16 GB SD Card

### ISSUE THREAD

**Issue by Michael-A-Heuer** [status-im/nim-beacon-chain#688]
Hi, I am trying to install nim-beacon-chain on my Raspberry Pi 4B with 4 GB RAM, 16 GB SD card, running Raspbian Buster Lite (Kernel version 4.19) and [CPU overclocked to 2.14 GHz, GPU overclocked to 750 MHz](https://www.electronicsweekly.com/news/business/clocking-raspberry-pi-4-2019-10/).
 

During execution of `make test`, I got the following test failure:

```
[Suite] LMDB
/home/pi/status/nim-beacon-chain/beacon_chain/kvstore_lmdb.nim(50) raiseLmdbError

    Unhandled exception: Cannot allocate memory [LmdbError]
  [FAILED] KVStore interface
```
[...]

```
10 longest individual test durations
------------------------------------
 18.90s for Passes through epoch update, empty block [Preset: mainnet]
  5.39s for sanity check genesis roundtrip [Preset: mainnet]
  4.82s for sanity check states [Preset: mainnet]
  3.08s for Passes through epoch update, no block [Preset: mainnet]
  1.97s for Interop genesis
  0.86s for Attestation gets processed at epoch [Preset: mainnet]
  0.78s for Valid attestation from previous epoch
  0.71s for Smoke test initialize_beacon_state_from_eth1 [Preset: mainnet]
  0.64s for Passes from genesis state, empty block [Preset: mainnet]
  0.60s for Valid attestation
  0.58s for Empty aggregation bit
Error: execution of an external program failed: '/home/pi/status/nim-beacon-chain/build/all_tests '
stack trace: (most recent call last)
/home/pi/status/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(393, 18)
/home/pi/status/nim-beacon-chain/beacon_chain.nimble(49, 15) testTask
/home/pi/status/nim-beacon-chain/beacon_chain.nimble(44, 8) buildBinary
/home/pi/status/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(252, 7) exec
/home/pi/status/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(252, 7) Error: unhandled exception: FAILED: nim c --out:./build/all_tests -r -d:release -d:chronicles_log_level=ERROR -d:const_preset=mainnet --verbosity:0 --hints:off --warnings:off -d:usePcreHeader --passL:"-lpcre" tests/all_tests.nim  [OSError]
make: *** [Makefile:96: test] Error 1
```
Is the problem that I don't have enough free disk space? 

Currently, I have 4.1 GB of free space. Because I am planning to run a node (as in this setup: [Running an Ethereum Full Node on a Raspberry Pi 4 (model B)](https://kauri.io/running-an-ethereum-full-node-on-a-raspberrypi-4-(model-b)/9695fcca217f46feb355245275835fc0/a)) as well, I bought a 500 GB SSD arriving in the next days. Will this solve the issue?

**Comment by stefantalpalaru** [comment]
RAM must be the limiting factor here, not storage size, but mmap() should only add to the virtual memory size, not the resident set size.

If you're on a 32-bit userspace, like I suspect you are, LMDB will try to mmap 1 GiB. This, plus the RSS of the test program should not even come close to the maximum of 3 GiB per process.

Let's see how much memory you can overcommit on that system. Please paste the output of:

```text
cat /proc/sys/vm/overcommit_memory
cat /proc/sys/vm/overcommit_ratio
```

**Comment by Michael-A-Heuer** [comment]
@stefantalpalaru Yes, I am using `Raspbian Buster Lite (Kernel version 4.19)`, which is still 32-bit (64-bit is currently under development).

I got the following outputs:
```
pi@ethnode2:~ $ cat /proc/sys/vm/overcommit_memory
>>> 0
pi@ethnode2:~ $ cat /proc/sys/vm/overcommit_ratio
>>> 50
```

**Comment by Michael-A-Heuer** [comment]
Are you planning to support it or should I wait until Raspbian fully supports ARM64? In this case, which Linux distribution would you suggest to me? (I am familiar with Ubuntu on a normal user level.)

**Comment by arnetheduck** [comment]
rPI will be supported - getting there is a matter of deciding which database to use - `lmdb` is an experiment that has some attractive properties but there are also issues like this, with platform support, that we have to consider. sqlite is an alternative.

**Comment by arnetheduck** [comment]
replaced with sqlite on `devel`

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/809 removes LMDB support from `nim-beacon-chain`.
