### ISSUE TITLE
Incorrect merkle validation in `process_deposit`

### ISSUE THREAD

**Issue by gnattishness** [status-im/nim-beacon-chain#703]
### What is wrong?

`process_deposit` accepts deposits with an invalid merkle proof as valid

https://github.com/status-im/nim-beacon-chain/blob/257771d9af971621dc73b572c56d5e856ac75ad5/beacon_chain/spec/beaconstate.nim#L57-L70

### How can it be fixed

1. `process_deposit` should fail if `is_valid_merkle_branch()` is false e.g. `return false`
2. `is_valid_merkle_branch()` should be called with `depth=DEPOSIT_CONTRACT_TREE_DEPTH + 1` according to the spec (https://github.com/ethereum/eth2.0-specs/blob/v0.10.1/specs/phase0/beacon-chain.md#deposits)

### How it was found

Discovered via [`beacon-fuzz`](https://github.com/sigp/beacon-fuzz/) (initial testing of [`deposit` fuzzer](https://github.com/sigp/beacon-fuzz/tree/add_targets/files/fuzzers/deposit)).
Triggering case: [nim-deposit-crash-5d4907f2962783d3806b93bfe1a5f4c808b1c3bf](https://drive.google.com/file/d/1sYX3dqahjweb5FGFfJvLTdDtjWba2tHE/view?usp=sharing) with the following [`beacon_state`s](https://github.com/sigp/beacon-fuzz-corpora/tree/1c2d95a67a2136b94511908250e8b21d550a09d0/0-9-1/mainnet/beaconstate)
Or the pre-processed input [deposit_preprocessed_invalid_merkle.ssz](https://drive.google.com/file/d/1sukDqNVMpVqji5wJb017eO9dPZccqFpy/view?usp=sharing) can be directly passed to the nimbus harness [`nfuzz_deposit`](https://github.com/status-im/nim-beacon-chain/blob/libnfuzz/nfuzz/libnfuzz.nim)

**Comment by djrtwo** [comment]
Interesting, we have a case to cover an invalid merkle branch in the consensus tests here -- https://github.com/ethereum/eth2.0-specs/blob/7b76808a1c28dc44d449dee7619e301130066959/tests/core/pyspec/eth2spec/test/phase_0/block_processing/test_process_deposit.py#L228-L240

I'll see if I can figure out what the difference between this case is and why it's not adequately covered in our vectors

**Comment by tersec** [comment]
Feel free to re-open if this doesn't fix things.
