### ISSUE TITLE
Finalization tests in CI

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#718]
Feb 2020 milestone target

**Comment by stefantalpalaru** [comment]
The infrastructure for this is in place on Jenkins, on Linux: https://github.com/status-im/nim-beacon-chain/pull/753

It will be enabled once we have a passing test.

TODO: allow running multiple "launch_local_testnet.sh" instances in parallel on the same Jenkins node. This means custom beacon_node binary names and custom ports for each instance. The data dir is already customisable.

**Comment by stefantalpalaru** [comment]
Testnet0 finalisation test added to Jenkins: https://github.com/status-im/nim-beacon-chain/pull/798

**Comment by stefantalpalaru** [comment]
Testnet1 finalisation test added to Jenkins: https://github.com/status-im/nim-beacon-chain/pull/802
