### ISSUE TITLE
Fork choice: reimplementation

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#719]
Feb 2020 milestone

- See proto-array (https://github.com/protolambda/lmd-ghost / https://medium.com/prysmatic-labs/eth-2-0-dev-update-42-rapid-iteration-7abdd62109e3 / https://blog.ethereum.org/2020/02/04/eth2-quick-update-no-8/)
- Pending EF official tests (currently there are 2 versions competing in the eth2-specs repo)

**Comment by arnetheduck** [comment]
https://github.com/sigp/lighthouse/pull/804

**Comment by mratsim** [comment]
and Harmony format: https://github.com/ethereum/eth2.0-spec-tests/issues/17

**Comment by mratsim** [comment]
Status: passing all the unit test but stuck with finalization issues #965

**Comment by mratsim** [comment]
Closed by #1238
