### ISSUE TITLE
[Apr20] Start mainnet testnet

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#722]

**Comment by stefantalpalaru** [comment]
Plan: make this "testnet2" - a new separate testnet.

**Comment by stefantalpalaru** [comment]
New plan: once testnet1 is stable, make it the new testnet0, then switch testnet1 to the mainnet profile.

**Comment by stefantalpalaru** [comment]
Testnet1 moved to mainnet.
