### ISSUE TITLE
[Stretch] RPC for block explorers

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#723]
- eth2-api repo: RPC for block explorers

**Comment by zah** [comment]
Since we don't have a Chronos-based HTTP server yet, the initial goal is to integrate [nim-json-rpc](https://github.com/status-im/nim-json-rpc) just like it's done in [nimbus](https://github.com/status-im/nimbus/tree/master/nimbus/rpc).

**Comment by JGcarv** [comment]
Hello! 

Can I try this one?

The goal here is to expose the methods on [eth2-apis](https://github.com/ethereum/eth2.0-apis) and attach it to the beacon node, correct?

**Comment by zah** [comment]
Sorry @JGcarv, just few days ago we've increased the priority of this task and as a result we started making progress on the implementation internally. The work is already close to being completed.

**Comment by zah** [comment]
Initial implementation was done here:
https://github.com/status-im/nim-beacon-chain/pull/815

Further progress towards a more complete RESTful API will be tracked here:
https://github.com/status-im/nim-beacon-chain/issues/993
