### ISSUE TITLE
[Stretch] Tooling for debugging

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#725]
Stretch goal for Feb 2020 milestone

- Example: log inspector to detect issues of finalization, slashing, ...

**Comment by mratsim** [comment]
@cheatfate to push his log inspector tool that allow detecting networking issues from nbc issues

**Comment by cheatfate** [comment]
Initial work was done in https://github.com/status-im/nim-beacon-chain/pull/799
