### ISSUE TITLE
Peer count wrong

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#727]
When running testnet, at the bottom there's is a status line saying `Peers: 1` - this number remains regardless if peers are connected or not.

f20127f4c65444f286c2749eabac7252d31ea0d2

**Comment by zah** [comment]
https://github.com/status-im/nim-beacon-chain/pull/730 includes a fix for this

**Comment by kdeme** [comment]
The status bar value does get updated now so I'll close this.

There is however still an issue when peers drop, but that problem has a deeper origin, see: https://github.com/status-im/nim-beacon-chain/issues/775
