### ISSUE TITLE
suspiciously high number of new futures being created in the local sim

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nim-beacon-chain#779]
Peaks of 25K new futures created per second by one of the four beacon_node instances started by `make eth2_network_simulation`: ![futures](https://i.imgur.com/rbVOAia.png)

The main source of new futures is those being used as some sort of async mutexes by BufferStream read operations (when a fixed-length read doesn't get all the bytes it wants from the internal buffer, it adds a new future to a queue and awaits its completion which signals that new bytes are available in that internal buffer; rinse, repeat until it's done reading all it wants to read), but read events peak somewhere around 30/40 per second: ![read events](https://i.imgur.com/JrUahtx.png)

What causes this huge number of read attempts when so few read events need to be processed?

This is also a performance issue, since creating futures (each one does a stack trace dump, which explains our particularly high overhead with Nim's default stack traces) and processing them in the Chronos event loop is CPU-intensive.

**Comment by stefantalpalaru** [comment]
The number of new futures per second dropped drastically in devel, with maximum values around 2K/s:

![new futures](https://i.imgur.com/xia3YCN.png)

**Comment by tersec** [comment]
What counts as resolved here? I know we have some basically long-term tracking bugs, but this presumably should be resolved when it hits a reasonable point, being time-bound.

**Comment by stefantalpalaru** [comment]
For that, we need to decide how many new futures are acceptable for our 50 read + 100 write events per second peaks. I hope we can bring that 2K value down some more.

**Comment by stefantalpalaru** [comment]
Mostly fixed. Will open a more specific one for what's left.
