### ISSUE TITLE
[ongoing] Network stability

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#784]
This is an ongoing issue to identify and track networking performance and stability issues in `nim-libp2p` and `NBC`.

### libp2p memory leaks
  - [x] https://github.com/status-im/nim-beacon-chain/issues/778
  - [x] https://github.com/status-im/nim-beacon-chain/issues/779
    - Potential fix - https://github.com/status-im/nim-libp2p/pull/128

### Performance
  - Continuing tracking performance issues, in particular the current implementation should allow:
    - pubsub messages to propagate quickly enough to allow finalization
    - block syncing should allow quick block retrieval with minimum resource usage

### Tracking and monitoring
  - Increase monitoring to include missing counts for libp2p and NBC

**Comment by stefantalpalaru** [comment]
Depends on:

- [ ] https://github.com/status-im/nim-beacon-chain/issues/778
- [ ] https://github.com/status-im/nim-beacon-chain/issues/779

**Comment by mratsim** [comment]
TODO: define April scope so that we can actually now when to close this, see #867

**Comment by dryajov** [comment]
Closing this as the main stability issue has been identified and fixed.
