### ISSUE TITLE
Plan audit

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#785]
Initial steps for audit include scoping and describing the work as well as bringing auditors onboard.

- [x] prepare RFP for audit
- [x] describe auditable parts of code
- [x] describe audit priorities

**Comment by arnetheduck** [comment]
Work in progress code organization overview: https://miro.com/app/board/o9J_kvfytDI=/

**Comment by arnetheduck** [comment]
WIP audit rfp: https://notes.status.im/nbc-security-audit#

**Comment by arnetheduck** [comment]
https://our.status.im/nimbus-eth2-0-security-audit-request-for-proposal/ - audit prep underway
