### ISSUE TITLE
[Tentative] RPC interface

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#786]
Tentative objective for Mar 2020 sprint

Target 1: RPC as Tooling to help debug and investigation

For stretch goal (RPC for block explorers) there is a separate (follow-up) issue: https://github.com/status-im/nim-beacon-chain/issues/723

**Comment by kdeme** [comment]
From zah

> Since we don't have a Chronos-based HTTP server yet, the initial goal is to integrate [nim-json-rpc](https://github.com/status-im/nim-json-rpc) just like it's done in [nimbus](https://github.com/status-im/nimbus/tree/master/nimbus/rpc).

**Comment by zah** [comment]
This has been delivered here (https://github.com/status-im/nim-beacon-chain/pull/815)

Further enhancements to the API will be introduced in (https://github.com/status-im/nim-beacon-chain/issues/767) and (https://github.com/status-im/nim-beacon-chain/issues/856).
