### ISSUE TITLE
[Tentative] Drop libp2p daemon

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#790]
Tentative objective for Mar2020 sprint

**Comment by tersec** [comment]
If https://github.com/status-im/nim-beacon-chain/pull/804 proves stable over the next couple of weeks, this might be feasible.

**Comment by stefantalpalaru** [comment]
We also need a stable testnet1. Now it's leaking memory and producing too many logs.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/824 did this.
