### ISSUE TITLE
[Apr20] Add an example custom preset

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#821]
Documentation:

Add an `examples` folder and put a custom preset in there that can be read with
`-d:const_preset=path/to/example_preset`

https://github.com/status-im/nim-beacon-chain/blob/e1fb18d7dbb5c40e5520f06a71196b31827487ac/beacon_chain/spec/datatypes.nim#L56-L57
https://github.com/status-im/nim-beacon-chain/blob/e1fb18d7dbb5c40e5520f06a71196b31827487ac/beacon_chain/spec/presets/custom.nim#L124

**Comment by arnetheduck** [comment]
`make schlesi` is an example
