### ISSUE TITLE
memory leak during block syncing

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nim-beacon-chain#850]
To replicate, run a local sim in one terminal tab:
```text
make NIMFLAGS="-d:insecure" eth2_network_simulation
```
In another tab, start the Prometheus daemon (after the sim starts running, so the conf file has been generated):
```text
cd tests/simulation/prometheus
prometheus
```
Wait a couple of minutes, then connect an external node that will start syncing blocks (from a third tab):
```text
./tests/simulation/run_node.sh 4
```
You can do a quick-and-dirty metric visualisation from [Prometheus' web interface](http://localhost:9090/graph?g0.range_input=5m&g0.stacked=1&g0.expr=rate(chronos_processed_callbacks_total%7Bnode%3D%220%22%7D%5B2s%5D)&g0.tab=0&g1.range_input=5m&g1.stacked=1&g1.expr=rate(chronos_loop_timers_total%7Bnode%3D%220%22%7D%5B2s%5D)&g1.tab=0&g2.range_input=5m&g2.stacked=1&g2.expr=chronos_loop_timers_queue%7Bnode%3D%220%22%7D&g2.tab=0&g3.range_input=5m&g3.stacked=0&g3.expr=rate(chronos_poll_events_total%7Bnode%3D%220%22%7D%5B2s%5D)&g3.tab=0&g4.range_input=5m&g4.expr=rate(chronos_future_callbacks_total%7Bnode%3D%220%22%7D%5B2s%5D)&g4.tab=0&g5.range_input=5m&g5.stacked=1&g5.expr=rate(chronos_new_future_total%7Bnode%3D%220%22%7D%5B2s%5D)&g5.tab=0&g6.range_input=5m&g6.stacked=1&g6.expr=rate(chronos_poll_ticks_total%7Bnode%3D%220%22%7D%5B2s%5D)&g6.tab=0&g7.range_input=5m&g7.expr=nim_gc_heap_instance_occupied_bytes%7Bnode%3D%220%22%7D&g7.tab=0&g8.range_input=5m&g8.stacked=0&g8.expr=chronos_pending_futures%7Bnode%3D%220%22%7D&g8.tab=0). Relevant graphs (you also want the "metrics" branch of "vendor/nim-chronos"):

GC's heap:
![GC heap](https://i.imgur.com/yEdIWGg.png)

Pending futures:
![pending futures](https://i.imgur.com/b41E9Og.png)

**Comment by stefantalpalaru** [comment]
Fixed by https://github.com/status-im/nim-beacon-chain/pull/874

**Comment by stefantalpalaru** [comment]
It's back ("Blob" is "seq[byte]"):

![img](https://i.imgur.com/UgCnOrf.png)

**Comment by dryajov** [comment]
Potentially addressed by https://github.com/status-im/nim-libp2p/pull/187

**Comment by stefantalpalaru** [comment]
Now we're leaking strings:

![img](https://i.imgur.com/j27797j.png)

**Comment by dryajov** [comment]
yes, notices that, but wasn't 100% sure, `seq[byte]` is gone completely?

**Comment by stefantalpalaru** [comment]
> `seq[byte]` is gone completely?

No, but looks like it slowed down considerably. Here it is in the second node:

![img](https://i.imgur.com/hH99IoP.png)

**Comment by dryajov** [comment]
Latest master for libp2p has some additional fixes that might address some of this further, but I've definitely seen string leaks even with those, so more digging is required.

**Comment by stefantalpalaru** [comment]
Metrics from a witti client runing on an empty db show memory leaks, open file descriptor leaks and libp2p connection leaks.

```text
make clean-witti
make NIMFLAGS="-d:insecure" SCRIPT_PARAMS="--skipGoerliKey" witti
```

![img](https://i.imgur.com/lLSoyVf.png)

**Comment by dryajov** [comment]
> Metrics from a witti client runing on an empty db show memory leaks, open file descriptor leaks and libp2p connection leaks.
> 
> ```
> make clean-witti
> make NIMFLAGS="-d:insecure" SCRIPT_PARAMS="--skipGoerliKey" witti
> ```
> 
> ![img](https://camo.githubusercontent.com/1051c44042628d6774821b0facb819e176bf994f/68747470733a2f2f692e696d6775722e636f6d2f6c4c536f7956662e706e67)

this is potentially fixed in latest master in libp2p, nbc needs to be updated with it.

**Comment by arnetheduck** [comment]
resolved by https://github.com/status-im/nim-chronos/pull/130
