### ISSUE TITLE
[Apr20] Per-topic log-level

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#872]
Logging is our main tool to understand, debug and fix issues in nim-beacon-chain, especially for non-deterministic issues like those caused by the networking modules.

At the moment, enabling TRACE level log will enable trace for all services, networking, consensus, block/validator/attestation pool, fork choice, ... Given our very extensive logging this causes some issues:
- The sheer size of logs can quickly fill gigabytes of memory
- It's hard and/or time-consuming to parse manually

Usually when debugging we focus on a single component like networking and only need the regular info/warning/error for the others.

There is another budget concern. A significant portion of our AWS budget is consumed by extra space to hold the logs. Being able to have the stable part of NBC using less logging while the unstable part use more would allow us to run more validator nodes for the same budget.

Similarly, low-power devices might have at most a couple GB and we should focus the logs on the critical parts.

**Comment by stefantalpalaru** [comment]
> A significant portion of our AWS budget is consumed by extra space to hold the logs.

It's not that much. We only keep logs for the last 4 hours:

```text
stefan@master-01.aws-eu-central-1a.nimbus.test:~$ du -sh /var/log/docker/
1.3G	/var/log/docker/
stefan@master-01.aws-eu-central-1a.nimbus.test:~$ ll -h /var/log/docker/beacon-node-testnet1-1/
total 596M
drwxr-xr-x 2 syslog syslog 4.0K Apr  7 14:17 ./
drwxr-xr-x 6 syslog adm    4.0K Mar 12 12:32 ../
-rw-r--r-- 1 syslog adm    247M Apr  7 15:01 docker.log
-rw-r--r-- 1 syslog adm    335M Apr  7 14:17 docker.log.1
-rw-r--r-- 1 syslog adm    6.9M Apr  7 13:17 docker.log.2.gz
-rw-r--r-- 1 syslog adm    6.9M Apr  7 12:17 docker.log.3.gz
```

**Comment by mratsim** [comment]
Is 4 hours of logs enough though?

**Comment by zah** [comment]
Implemented in 
https://github.com/status-im/nim-beacon-chain/commit/7237a370babdc6a5205336aad54a9f843fade8ee

Check out the additions to the Makefile to see how to control the traced topics
