### ISSUE TITLE
[Crash/Fuzzing] AssertionError during Deposit SSZ parsing.

### ISSUE THREAD

**Issue by pventuzelo** [status-im/nim-beacon-chain#895]
Hi,

During fuzzing with [beacon-fuzz](https://github.com/sigp/beacon-fuzz), I triggered an `AssertionError` during parsing of `Deposit` ssz file with `mainnet` preset.

Error:
`Error: unhandled exception: XXX/nim-beacon-chain/beacon_chain/spec/crypto.nim(290, 12) 'value.kind == Real'  [AssertionError]`

# Reproducing

Download: 
[assert_nimbus_deposit.zip](https://github.com/status-im/nim-beacon-chain/files/4486223/assert_nimbus_deposit.zip)

commit: `96431bfd861be168ecc4cefb14fdb77d28108a24`

Load the file using `ncli_pretty`:
``` sh
$ cd ncli

$ ../env.sh nim c -d:const_preset=mainnet ncli_pretty

$ ./ncli_pretty --kind=deposit --file=assert_nimbus_deposit.ssz 
Traceback (most recent call last, using override)
XXX/nim-beacon-chain/vendor/nim-confutils/confutils.nim(981) confutils
XXX/nim-beacon-chain/vendor/nim-serialization/serialization.nim(41) CLI
XXX/nim-beacon-chain/vendor/nim-serialization/serialization.nim(27) encodeImpl
XXX/nim-beacon-chain/vendor/nim-serialization/serialization/object_serialization.nim(173) writeValue
XXX/nim-beacon-chain/vendor/nim-serialization/serialization/object_serialization.nim(173) writeValue
XXX/nim-beacon-chain/beacon_chain/spec/crypto.nim(290) writeValue
XXX/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(29) failedAssertImpl
XXX/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(22) raiseAssert
XXX/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(51) sysFatal
XXX/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(407) reportUnhandledError
XXX/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(358) reportUnhandledErrorAux
Error: unhandled exception: XXX/nim-beacon-chain/beacon_chain/spec/crypto.nim(290, 12) `value.kind == Real`  [AssertionError]
```

**Comment by tersec** [comment]
I can reproduce this on `96431bfd861be168ecc4cefb14fdb77d28108a24` but not current `devel` -- https://github.com/status-im/nim-beacon-chain/commit/7b8d6ea61c46ceb0edce1418a38275d7859f1334

**Comment by pventuzelo** [comment]
For `devel` brach, commit `7b8d6ea61c46ceb0edce1418a38275d7859f1334`

try this sample: 
[assert_nimbus_devel_deposit.zip](https://github.com/status-im/nim-beacon-chain/files/4486393/assert_nimbus_devel_deposit.zip)

**Comment by tersec** [comment]
Same lack of crash here on `devel`:
```
nim-beacon-chain/ncli$ ./ncli_pretty --kind=deposit --file=../../assert_nimbus_devel_deposit.ssz | head && echo exit value is 0
{
  "proof": [
    {
      "data": [
        0,
        0,
        0,
        0,
        0,
        0,
exit value is 0
```

**Comment by pventuzelo** [comment]
my bad, on `devel` it's good ;)

**Comment by tersec** [comment]
Good to know, and glad to have verified this was fixed.
