### ISSUE TITLE
[bug/Fuzzing] Incorrect validation of pre-state attestation & malformed block signature during state transition (nim)

### ISSUE THREAD

**Issue by pventuzelo** [status-im/nim-beacon-chain#944]
Hi guys, 

After fuzzing with [beacon-fuzz](https://github.com/sigp/beacon-fuzz), we found an issue in prysm and I reported it here:
[[bug/fuzzing] Incorrect validation of pre-state attestation & malformed block signature during state transition](https://github.com/prysmaticlabs/prysm/issues/5658).

Download: [incorrect_ssz_validation_prysm.zip](https://github.com/status-im/nim-beacon-chain/files/4545459/incorrect_ssz_validation_prysm.zip)

Based on testing with `./ncli_transition`, you also have the same issues:
``` sh
$ make

$ cd ncli

$ ../env.sh nim c -d:const_preset=mainnet ncli_transition

$ ./ncli_transition --pre= incorrect_ssz_validation_state_prysm.ssz --blck= incorrect_ssz_validation_block_prysm.ssz --post= post.ssz
...
# process continued without any errors
```

### Environment

preset: `mainnet` preset
branch: `devel`
commit: fada11e1e94ad346d44846fc817b8c444b54a204

**Comment by tersec** [comment]
According to discussion from https://github.com/status-im/nim-beacon-chain/pull/955 it's not clear we'll fix this as such. I'll leave this open for now, pending further discussion.
