### ISSUE TITLE
Validator duties: duplicate rewinding

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#967]
The proc related to validator duties are doing a lot of state rewinding to ultimately work on the same state:

`getProposer` in the blockpool, called in `handleProposal`
https://github.com/status-im/nim-beacon-chain/blob/01e9df97cb2f0035df2f7cea72ef14213eb0cc0f/beacon_chain/block_pool.nim#L1050-L1066

`handleAttestations` in beacon_node
https://github.com/status-im/nim-beacon-chain/blob/01e9df97cb2f0035df2f7cea72ef14213eb0cc0f/beacon_chain/beacon_node.nim#L570-L587

`proposeBlock` in beacon_node
https://github.com/status-im/nim-beacon-chain/blob/01e9df97cb2f0035df2f7cea72ef14213eb0cc0f/beacon_chain/beacon_node.nim#L386-L435

Edit, in debugging mode we have a 4th rewind while dumping in block proposal:
https://github.com/status-im/nim-beacon-chain/blob/01e9df97cb2f0035df2f7cea72ef14213eb0cc0f/beacon_chain/beacon_node.nim#L451-L455

**Comment by tersec** [comment]
Indeed. It's also a state that was already seen/calculated, then thrown away. This should be mostly caught by now by the caches, but it's one of the cases where the caches shouldn't even kick in, these deterministically accessing it.

**Comment by arnetheduck** [comment]
in the case the exact same state is needed for multiple operations, `updateStateData` will detect this and not do any work at all - I didn't check the latest changes, but ideally the caches should not be used either.

A thing to consider here is the out-of-order execution introduced with `await` - the reason it was written this way was that a "local" check that the state is in the right spot ensures that we're resilient against accidental state corruption - ie better check and be safe than use the wrong state - code that "looks" sequential often really isn't.

**Comment by mratsim** [comment]
Not an issue anymore. Now rewinding only happens in very seldom places https://github.com/status-im/nim-beacon-chain/search?q=withState, in particular the dedicated EpochRef and doesn't appear in profiling.

Furthermore there is proper caching and warning on cache misses: https://github.com/status-im/nim-beacon-chain/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/block_pools/chain_dag.nim#L609-L630
