### ISSUE TITLE
nil checks missed on ref objects (BlockRef)

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#987]
It seems like in some cases there is no nil checks on `BlockRef` which lead to strange issues with an Eth2Digest passed as a nil pointer in the assembly code:

The fix was: https://github.com/status-im/nim-beacon-chain/pull/965/commits/0067c8d3186b4fa2a3d5ce4c24dc2756ebf8d860

but we might want to rework the API to use options or result.

Manifestation:

- Couldn't use the option type to pass a parent: https://github.com/status-im/nim-beacon-chain/pull/965#discussion_r419563477
- Segfault on logging: 
![image](https://user-images.githubusercontent.com/22738317/81282152-12335880-905b-11ea-9e6c-49083d3db9c5.png)

**Comment by arnetheduck** [comment]
I'm not sure what the action item is here? check `ref` for nil? option won't be different, it needs to be checked for none etc
